export const minerals = {
    a: [
        {name: 'ACANTHITE', sciName: '(Silver Sulfide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Acanthite_-_Chispas_Mine%2C_Arizpe%2C_Sonora%2C_Mexico.jpg/217px-Acanthite_-_Chispas_Mine%2C_Arizpe%2C_Sonora%2C_Mexico.jpg'},
        {name: 'ACTINOLITE', sciName: '(Calcium Magnesium Iron Silicate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Actinolite_Portugal.jpg/260px-Actinolite_Portugal.jpg'},
        {name: 'ADAMITE', sciName: '(Zinc Arsenate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Adamite-179841.jpg/240px-Adamite-179841.jpg'},
        {name: 'AEGIRINE', sciName: '(Sodium Iron Silicate)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Aegirine-Feldspar-Group-233473.jpg/260px-Aegirine-Feldspar-Group-233473.jpg'},
        {name: 'AESCHYNITE', sciName: '(Yttrium Calcium Iron Thorium Titanium Niobium Oxide Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Aeschynite-%28Y%29-180743.jpg/240px-Aeschynite-%28Y%29-180743.jpg'},
        {name: 'AGATE', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Agate_banded_750pix.jpg/260px-Agate_banded_750pix.jpg'},
        {name: 'AJOITE', sciName: '(Hydrated Potassium Sodium Copper Aluminum Silicate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Ajoite-Quartz-tmu47f.jpg/260px-Ajoite-Quartz-tmu47f.jpg'},
        {name: 'ALBITE', sciName: '(Sodium Aluminum Silicate)', imgUrl: 'http://www.minerals.net/thumbnail.aspx?image=MineralImages/albite1.jpg&size=500'},
        {name: 'ALEXANDRITE', sciName: '(variety of Chrysoberyl- Beryllium Aluminum Oxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Alexandrite_26.75cts.jpg/220px-Alexandrite_26.75cts.jpg'},
        {name: 'ALLANITE', sciName: '(Calcium Cerium Lanthanum Yttrium Aluminum Iron Silicate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Allanite-%28Ce%29_-_Mary_Kathleen_Mine%2C_Mount_Isa%2C_Queensland%2C_Australia.jpg/240px-Allanite-%28Ce%29_-_Mary_Kathleen_Mine%2C_Mount_Isa%2C_Queensland%2C_Australia.jpg'},
        {name: 'ALMANDINE', sciName: '(Iron Aluminum Silicate)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Almandin.jpg/300px-Almandin.jpg'},
        {name: 'ALTAITE', sciName: '(Lead Telluride)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Altaite-170094.jpg/240px-Altaite-170094.jpg'},
        {name: 'ALUNITE', sciName: '(Potassium Aluminum Sulfate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Alunite_-_USGS_Mineral_Specimens_015.jpg/240px-Alunite_-_USGS_Mineral_Specimens_015.jpg'},
        {name: 'AMBER', sciName: '(Succinite: fossilized tree resin)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Amber2.jpg/220px-Amber2.jpg'},
        {name: 'AMBLYGONITE', sciName: '(Lithium Sodium Aluminum Phosphate Fluoride Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Mineral_Ambligonita_GDFL032.jpg/260px-Mineral_Ambligonita_GDFL032.jpg'},
        {name: 'AMETHYST', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Amethyst._Magaliesburg%2C_South_Africa.jpg/260px-Amethyst._Magaliesburg%2C_South_Africa.jpg'},
        {name: 'ANALCIME', sciName: '(Hydrated Sodium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Analcime%2C_Aegirine%2C_Natrolite-225835.jpg/260px-Analcime%2C_Aegirine%2C_Natrolite-225835.jpg'},
        {name: 'ANAPAITE', sciName: '(Hydrated Calcium Iron Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Anapaite-215130.jpg/240px-Anapaite-215130.jpg'},
        {name: 'ANATASE', sciName: '(Titanium Oxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Anatase_Oisans.jpg/260px-Anatase_Oisans.jpg'},
        {name: 'ANDALUSITE', sciName: '(Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/AndalousiteTyrol.jpg/260px-AndalousiteTyrol.jpg'},
        {name: 'ANDERSONITE', sciName: '(Hydrated Sodium Calcium Uranyl Carbonate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Andersonite-37032.jpg/260px-Andersonite-37032.jpg'},
        {name: 'ANDESINE', sciName: '(Sodium Calcium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Andesine-251551.jpg/260px-Andesine-251551.jpg'},
        {name: 'ANDRADITE', sciName: '(Calcium Iron Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Andradite-Mali.jpg/260px-Andradite-Mali.jpg'},
        {name: 'ANGELITE', sciName: '(trade name for Anhydrite)', imgUrl:'https://moonrisecrystals.com/wp-content/uploads/2014/07/angelite-raw-1-300x300.jpg'},
        {name: 'ANGLESITE', sciName: '(Lead Sulfate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Angl%C3%A9site%2C_gal%C3%A8ne%2C_soufre_300-4-5394.JPG/260px-Angl%C3%A9site%2C_gal%C3%A8ne%2C_soufre_300-4-5394.JPG'},
        {name: 'ANHYDRITE', sciName: '(Calcium Sulfate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Anhydrite_HMNH1.jpg/260px-Anhydrite_HMNH1.jpg'},
        {name: 'ANKERITE', sciName: '(Calcium Iron Carbonate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Ank%C3%A9rite_%28Grandfontaine%29-Mus%C3%A9e_de_min%C3%A9ralogie_de_Strasbourg.jpg/260px-Ank%C3%A9rite_%28Grandfontaine%29-Mus%C3%A9e_de_min%C3%A9ralogie_de_Strasbourg.jpg'},
        {name: 'ANNABERGITE', sciName: '(Hydrated Nickel Arsenate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Annabergite-Siderite-_Grece-1.jpg/220px-Annabergite-Siderite-_Grece-1.jpg'},
        {name: 'ANORTHITE', sciName: '(Calcium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Anorthite-rare08-38b.jpg/240px-Anorthite-rare08-38b.jpg'},
        {name: 'ANTHOPHYLLITE', sciName: '(Magnesium Iron Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Anthophyllite_Su%C3%A8de_Fond.jpg/260px-Anthophyllite_Su%C3%A8de_Fond.jpg'},
        {name: 'ANTLERITE', sciName: '(Copper Sulfate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Antlerite-40298.jpg/240px-Antlerite-40298.jpg'},
        {name: 'APATITE', sciName: '(Calcium Fluoro, Chloro, Hydroxyl Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Apatite_Canada.jpg/240px-Apatite_Canada.jpg'},
        {name: 'APOPHYLLITE', sciName: '(Hydrated Potassium Calcium Silicate Hydroxide Flouride)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Apophyllite-65547.jpg/260px-Apophyllite-65547.jpg'},
        {name: 'AQUAMARINE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Beryl-209736.jpg/220px-Beryl-209736.jpg'},
        {name: 'ARAGONITE', sciName: '(Calcium Carbonate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Aragonite_Salsigne_France.jpg/260px-Aragonite_Salsigne_France.jpg'},
        {name: 'ARFVEDSONITE', sciName: '(Sodium Iron Magnesium Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Arfvedsonite-20218.jpg/220px-Arfvedsonite-20218.jpg'},
        {name: 'ARGENTITE', sciName: '(Silver Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Argentite.jpg/220px-Argentite.jpg'},
        {name: 'ARGYRODITE', sciName: '(Silver Germanium Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Argyrodite-170093.jpg/240px-Argyrodite-170093.jpg'},
        {name: 'ARSENOPYRITE', sciName: '(Iron Arsenide Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Arsenopyrite-117874.jpg/260px-Arsenopyrite-117874.jpg'},
        {name: 'ARSENTSUMEBITE', sciName: '(Lead Copper Arsenate Sulfate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Naturkundemuseum_Berlin_-_Arsentsumebit_-_Tsumeb%2C_Namibia.jpg/250px-Naturkundemuseum_Berlin_-_Arsentsumebit_-_Tsumeb%2C_Namibia.jpg'},
        {name: 'ARTHURITE', sciName: '(Hydrated Copper Iron Arsenate Phosphate Sulfate)', imgUrl:'https://www.mindat.org/imagecache/8b/9d/01498820014948431533596.jpg'},
        {name: 'ARTINITE', sciName: '(Hydrated Magnesium Carbonate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Artinite-206168.jpg/260px-Artinite-206168.jpg'},
        {name: 'ASTROPHYLLITE', sciName: '(Potassium Iron Titanium Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Astrophyllite-168179.jpg/240px-Astrophyllite-168179.jpg'},
        {name: 'ATACAMITE', sciName: '(Copper Chloride Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Atacamite-235102.jpg/260px-Atacamite-235102.jpg'},
        {name: 'AUGELITE', sciName: '(Aluminum Phosphate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Augelite-78938.jpg/260px-Augelite-78938.jpg'},
        {name: 'AUGITE', sciName: '(Calcium Sodium Magnesium Aluminum Iron Titanium Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Augite_Rwanda.jpg/260px-Augite_Rwanda.jpg'},
        {name: 'AURICHALCITE', sciName: '(Zinc Copper Carbonate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Aurichalcite-Calcite-aur08b.jpg/260px-Aurichalcite-Calcite-aur08b.jpg'},
        {name: 'AUSTINITE', sciName: '(Calcium Zinc Arsenate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Austinite-177832.jpg/260px-Austinite-177832.jpg'},
        {name: 'AUTUNITE', sciName: '(Hydrated Calcium Uranyl Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Autunite-69257.jpg/240px-Autunite-69257.jpg'},
        {name: 'AXINITE', sciName: '(Calcium Iron Magnesium Manganese Aluminum Boro-Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Axinite-Oisan.jpg/240px-Axinite-Oisan.jpg'},
        {name: 'AZURITE', sciName: '(Copper Carbonate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Azurit.jpg/260px-Azurit.jpg'}
    ],
    b: [
        {name: 'BABINGTONITE', sciName: '(Calcium Iron Manganese Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Babingtonite_-_Newington.jpg/260px-Babingtonite_-_Newington.jpg'},
        {name: 'BAKERITE', sciName: '(Hydrated Calcium Boro-silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Bakerite.jpg/260px-Bakerite.jpg'},
        {name: 'BARATOVITE', sciName: '(Potassium Lithium Calcium Titanium Zirconium Silicate Fluoride)', imgUrl:'http://webmineral.com/specimens/photos/PG2MS/049-23Small.jpg'},
        {name: 'BARITE', sciName: '(Barium Sulfate)', imgUrl:'http://geology.com/minerals/photos/barite-rose-irocks.jpg'},
        {name: 'BASTNASITE', sciName: '(Cerium Lanthanum Yttrium Carbonate Fluoride)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Bastnaesit_Burundi.jpg/240px-Bastnaesit_Burundi.jpg'},
        {name: 'BAUMHAUERITE', sciName: '(Lead Arsenic Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Baumhauerite-177525.jpg/240px-Baumhauerite-177525.jpg'},
        {name: 'BAYLDONITE', sciName: '(Hydrated Copper Lead Arsenate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Bayldonite-Malachite-160206.jpg/240px-Bayldonite-Malachite-160206.jpg'},
        {name: 'BECQUERELITE', sciName: '(Hydrated Calcium Uranyl Oxide Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Becquerelite-Uranophane-Uraninite-201144.jpg/240px-Becquerelite-Uranophane-Uraninite-201144.jpg'},
        {name: 'BENITOITE', sciName: '(Barium Titanium Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/B%C3%A9nitoite_sous_U.V.%28USA%29.jpg/200px-B%C3%A9nitoite_sous_U.V.%28USA%29.jpg'},
        {name: 'BERAUNITE', sciName: '(Hydrated Iron Phosphate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Beraunite-Kidwellite-214676.jpg/260px-Beraunite-Kidwellite-214676.jpg'},
        {name: 'BERLINITE', sciName: '(Aluminum Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Berlinite.jpg/260px-Berlinite.jpg'},
        {name: 'BERTHIERITE', sciName: '(Iron Antimony Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Berthierite-224182.jpg/240px-Berthierite-224182.jpg'},
        {name: 'BERTRANDITE', sciName: '(Beryllium Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Bertrandite-38545.jpg/240px-Bertrandite-38545.jpg'},
        {name: 'BERYL', sciName: '(Berylium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Beryl09.jpg/260px-Beryl09.jpg'},
        {name: 'BERYLLONITE', sciName: '(Sodium Beryllium Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Beryllonite.jpg/260px-Beryllonite.jpg'},
        {name: 'BETAFITE', sciName: '(Calcium Sodium Uranium Titanium Niobium Tantalum Oxide Hydroxide Fluoride)', imgUrl:''},
        {name: 'BEUDANTITE', sciName: '(Lead Iron Arsenate Sulfate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Beudantite-ea12a.jpg/170px-Beudantite-ea12a.jpg'},
        {name: 'BAUXITE', sciName: '(Aluminum Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/BauxiteUSGOV.jpg/220px-BauxiteUSGOV.jpg'},
        {name: 'BIF', sciName: '(Banded Iron Formation aka Taconite)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Taconite.jpg/250px-Taconite.jpg'},
        {name: 'BIOTITE', sciName: '(Potassium Iron Magnesium Aluminum Silicate Hydroxide Fluoride)', imgUrl:'https://www.mindat.org/imagecache/95/7d/03545400014946555329533.jpg'},
        {name: 'BISMUTHINITE', sciName: '(Bismuth Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Bismuthinite-136224.jpg/220px-Bismuthinite-136224.jpg'},
        {name: 'BIXBYITE', sciName: '(Manganese Iron Oxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Bixbyite-160214.jpg/260px-Bixbyite-160214.jpg'},
        {name: 'BLODITE', sciName: '(Hydrated Sodium Magnesium Sulfate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Blodite-188275.jpg/220px-Blodite-188275.jpg'},
        {name: 'BLOODSTONE', sciName: '(aka Heliotrope, a variety of Chalcedony)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Quarz_-_Heliotrop_%28Blutjaspis%29.JPG/260px-Quarz_-_Heliotrop_%28Blutjaspis%29.JPG'},
        {name: 'BOLEITE', sciName: '(Hydrated Lead Copper Silver Chloride Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Boleite-rom51c.jpg/260px-Boleite-rom51c.jpg'},
        {name: 'BOLTWOODITE', sciName: '(Hydrated Potassium Uranyl Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Boltwoodite-34735.jpg/170px-Boltwoodite-34735.jpg'},
        {name: 'BORACITE', sciName: '(Magnesium Borate Chloride)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Boracite-169813.jpg/260px-Boracite-169813.jpg'},
        {name: 'BORAX', sciName: '(Hydrated Sodium Borate)', imgUrl:'https://www.mindat.org/imagecache/73/0b/07040790014946324145818.jpg'},
        {name: 'BORNITE', sciName: '(Copper Iron Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Mineraly.sk_-_bornit.jpg/220px-Mineraly.sk_-_bornit.jpg'},
        {name: 'BOULANGERITE', sciName: '(Lead Antimony Sulfide)', imgUrl:'https://www.mindat.org/imagecache/f4/a1/02667220014946301949964.jpg'},
        {name: 'BOURNONITE', sciName: '(Copper Lead Antimony Sulfide)', imgUrl:'https://www.mindat.org/imagecache/00/ba/08079880014946268828941.jpg'},
        {name: 'BRANNERITE', sciName: '(Uranium Calcium Titanium Iron Oxide)', imgUrl:'https://www.mindat.org/imagecache/b0/0a/01512340014947507322285.jpg'},
        {name: 'BRASS', sciName: '(Copper Zinc Alloy)', imgUrl:'https://www.mindat.org/imagecache/8c/2f/08523730014947147196139.png'},
        {name: 'BRAZILIANITE', sciName: '(Sodium Aluminum Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/cd/3a/01946590014948702845994.jpg'},
        {name: 'BROCHANTITE', sciName: '(Copper Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/89/b7/01996000014977679843557.jpg'},
        {name: 'BROOKITE', sciName: '(Titanium Oxide)', imgUrl:'https://www.mindat.org/imagecache/28/a5/08248920014946310484595.jpg'},
        {name: 'BRUCITE', sciName: '(Magnesium Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/0b/66/03290900014946250657502.jpg'},
        {name: 'BUERGERITE', sciName: '(Sodium Iron Aluminum Boro-silicate Oxide Fluoride)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Buergerite-179849.jpg/170px-Buergerite-179849.jpg'},
        {name: 'BURBANKITE', sciName: '(Sodium Calcium Strontium Barium Cerium Carbonate)', imgUrl:'https://www.mindat.org/imagecache/f9/27/00878640014958817144411.jpg'},
        {name: 'BUTTGENBACHITE', sciName: '(Hydrated Copper Nitrate Chloride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/47/3d/02647020014967899777937.jpg'},
        {name: 'BYTOWNITE', sciName: '(Calcium Sodium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/90/e1/05813930014961122159001.jpg'}
    ],
    c: [
        {name: 'CACOXENITE', sciName: '(Hydrated Iron Aluminum Phosphate Oxide Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/94/9a/01300350014951587312798.jpg'},
        {name: 'CALAVERITE', sciName: '(Gold Telluride)', imgUrl:'https://www.mindat.org/imagecache/21/70/00231710014954783741134.jpg'},
        {name: 'CALCIOVOLBORTHITE', sciName: '(Calcium Copper Vanadate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/a1/7d/01364890014946578902464.jpg'},
        {name: 'CALCITE', sciName: '(Calcium Carbonate)', imgUrl:'https://www.mindat.org/imagecache/6b/c3/06158290014946246527583.jpg'},
        {name: 'CALEDONITE', sciName: '(Copper Lead Carbonate Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/1f/a2/02938710014960990181090.jpg'},
        {name: 'CALOMEL', sciName: '(Mercury Chloride)', imgUrl:'https://www.mindat.org/imagecache/cc/7a/07419220014961798564400.jpg'},
        {name: 'CANCRINITE', sciName: '(Sodium Calcium Aluminum Silicate Carbonate)', imgUrl:'https://www.mindat.org/imagecache/8b/07/05657710014953483196018.jpg'},
        {name: 'CARBOCERNAITE', sciName: '(Calcium Sodium Strontium Cerium Barium Carbonate)', imgUrl:'https://www.mindat.org/imagecache/70/38/07278950014960893906636.jpg'},
        {name: 'CARLETONITE', sciName: '(Hydrated Potassium Sodium Calcium Carbonate Silicate Fluoride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/f1/f9/04314450014962496046499.jpg'},
        {name: 'CARNALLITE', sciName: '(Hydrated Potasium Magnesium Chloride)', imgUrl:'https://www.mindat.org/imagecache/0d/10/07220270014946711305325.jpg'},
        {name: 'CARNELIAN', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:'https://www.mindat.org/imagecache/50/82/00584150014946985948928.jpg'},
        {name: 'CARNOTITE', sciName: '(Hydrated Potassium Uranyl Vanadate)', imgUrl:'https://www.mindat.org/imagecache/f5/25/04733730014950143471563.jpg'},
        {name: 'CASSITERITE', sciName: '(Tin Oxide)', imgUrl:'https://www.mindat.org/imagecache/c0/96/03961760014946274339038.jpg'},
        {name: 'CATAPLEIITE', sciName: '(Hydrated Sodium Zirconium Silicate)', imgUrl:'https://www.mindat.org/imagecache/81/a1/00312910014949858343757.jpg'},
        {name: 'CAVANSITE', sciName: '(Hydrated Calcium Vanadium Silicate)', imgUrl:'https://www.mindat.org/imagecache/be/17/04512570014946306253624.jpg'},
        {name: 'CELESTITE', sciName: '(Strontium Sulfate)', imgUrl:'https://www.mindat.org/imagecache/48/68/02400040014947193441195.jpg'},
        {name: 'CERUSSITE', sciName: '(Lead Carbonate)', imgUrl:'https://www.mindat.org/imagecache/49/87/03437020014948928982947.jpg'},
        {name: 'CHABAZITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/ce/40/04421810015037769467124.jpg'},
        {name: 'CHALCANTHITE', sciName: '(Hydrated Copper Sulfate)', imgUrl:'https://www.mindat.org/imagecache/7c/a2/04246280014947021608361.jpg'},
        {name: 'CHALCEDONY', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:'https://www.mindat.org/imagecache/27/f0/04991900014946247584038.jpg'},
        {name: 'CHALCOCITE', sciName: '(Copper Sulfide)', imgUrl:'https://www.mindat.org/imagecache/0d/76/03830490014946259997200.jpg'},
        {name: 'CHALCOPHYLLITE', sciName: '(Hydrated Copper Aluminum Sulphate Arsenate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/d2/f4/04290470014947428074306.jpg'},
        {name: 'CHALCOPYRITE', sciName: '(Copper Iron Sulfide)', imgUrl:'https://www.mindat.org/imagecache/fe/2b/02518500014946260206642.jpg'},
        {name: 'CHALCOSIDERITE', sciName: '(Hydrated Copper Iron Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/0a/78/02510100014946538738146.jpg'},
        {name: 'CHALCOTRICHITE', sciName: '(variety of Cuprite, Copper Oxide)', imgUrl:'https://www.mindat.org/imagecache/bb/63/00918670014946701428073.jpg'},
        {name: 'CHAROITE', sciName: '(Hydrated Sodium Calcium Barium Strontium Silicate Hydroxide Fluoride)', imgUrl:'https://www.mindat.org/imagecache/08/45/02326930014946279683875.jpg'},
        {name: 'CHILDRENITE', sciName: '(Hydrated Iron Manganese Aluminum Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/c6/18/03632310014946306825871.jpg'},
        {name: 'CHKALOVITE', sciName: '(Sodium Beryllium Silicate)', imgUrl:'https://www.mindat.org/imagecache/1d/fc/03030170014947361339989.jpg'},
        {name: 'CHLORAPATITE', sciName: '(the chlorine rich apatite)', imgUrl:'https://www.mindat.org/imagecache/47/67/07323410014950401521765.jpg'},
        {name: 'CHLORARGYRITE', sciName: '(Silver Chloride)', imgUrl:'https://www.mindat.org/imagecache/0d/d8/02575720014946343149403.jpg'},
        {name: 'CHLORITE', sciName: '(Iron Magnesium Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/93/e9/07372000014946333514299.jpg'},
        {name: 'CHONDRODITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/5a/2e/03782300014946597926465.jpg'},
        {name: 'CHROMITE', sciName: '(Magnesium Iron Chromium Oxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Chromite.jpg/260px-Chromite.jpg'},
        {name: 'CHRYSOBERYL', sciName: '(Berylium Aluminum Oxide)', imgUrl:'https://www.mindat.org/imagecache/c5/5a/07391380014946634706299.jpg'},
        {name: 'CHRYSOCOLLA', sciName: '(Hydrated Copper Silicate)', imgUrl:'https://www.mindat.org/imagecache/9f/c9/08532920014960915811100.jpg'},
        {name: 'CHRYSOPRASE', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:'https://www.mindat.org/imagecache/3c/66/03462140014946297045727.jpg'},
        {name: 'CHRYSOTILE', sciName: '(variety of Serpentine, Magnesium Iron Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/f1/b8/00218260014946268134353.jpg'},
        {name: 'CHURCHITE', sciName: '(Hydrated Yttrium Erbium Phosphate)', imgUrl:'https://www.mindat.org/imagecache/1b/7d/09897740014961275196021.jpg'},
        {name: 'CINNABAR', sciName: '(Mercury Sulfide)', imgUrl:'https://www.mindat.org/imagecache/40/cb/05732490014946301723844.jpg'},
        {name: 'CITRINE', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:'https://www.mindat.org/imagecache/7b/94/07490410014946260115638.jpg'},
        {name: 'CLAUSTHALITE', sciName: '(Lead Selenide)', imgUrl:'https://www.mindat.org/imagecache/16/b4/01304000014947105995338.jpg'},
        {name: 'CLEAVELANDITE', sciName: '(variety of Albite, Sodium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/3d/ec/00085770014947891792737.jpg'},
        {name: 'CLIFFORDITE', sciName: '(Uranium Tellurate)', imgUrl:'https://www.mindat.org/imagecache/1d/9f/09094890014946264004890.jpg'},
        {name: 'CLINOCHLORE', sciName: '(Magnesium Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/93/e9/07372000014946333514299.jpg'},
        {name: 'CLINOCLASE', sciName: '(Copper Arsenate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/05/3b/04561750014946391445038.jpg'},
        {name: 'CLINOHEDRITE', sciName: '(Hydrated Calcium Zinc Silicate)', imgUrl:'https://www.mindat.org/imagecache/48/2b/02464540014949394332029.jpg'},
        {name: 'CLINOHUMITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/6a/71/02968640014946389499210.jpg'},
        {name: 'CLINOPTILOLITE', sciName: '(Hydrated Sodium Potassium Calcium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/9a/c7/08274210014946851984500.jpg'},
        {name: 'COBALTITE', sciName: '(Cobalt Arsenic Sulfide)', imgUrl:'https://www.mindat.org/imagecache/fb/5c/08934200014946311218013.jpg'},
        {name: 'COBALTOCALCITE', sciName: '(alternate name for Sphaerocobaltite)', imgUrl:'https://www.mindat.org/imagecache/2d/7c/00974240014950341337518.jpg'},
        {name: 'COCONINOITE', sciName: '(Hydrated Iron Aluminum Uranyl Phosphate Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/00/30/01093470014948151713176.jpg'},
        {name: 'COESITE', sciName: '(Silicon Dioxide)', imgUrl:'https://www.mindat.org/imagecache/83/49/04878190014946249019357.jpg'},
        {name: 'COLEMANITE', sciName: '(Hydrated Calcium Borate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/9d/57/09604210014946346192050.jpg'},
        {name: 'COLLINSITE', sciName: '(Hydrated Calcium Magnesium Iron Phosphate)', imgUrl:'https://www.mindat.org/imagecache/4c/bf/02124760014950477678027.jpg'},
        {name: 'COLUMBITE', sciName: '(Iron Magnesium Manganese Niobium Tantalum Oxide)', imgUrl:'https://www.mindat.org/imagecache/20/ee/06835770014946687814901.jpg'},
        {name: 'CONICHALCITE', sciName: '(Calcium Copper Arsenate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/e3/36/01045810014946378328481.jpg'},
        {name: 'CONNELLITE', sciName: '(Hydrated Copper Sulfate Chloride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/11/bf/00735260014960917511888.jpg'},
        {name: 'COPIAPITE', sciName: '(Hydrated Iron Magnesium Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/7d/4b/09960420014948023236159.jpg'},
        {name: 'CORDIERITE', sciName: '(Magnesium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/4a/96/09720090014946932965253.jpg'},
        {name: 'CORDYLITE', sciName: '(Barium Cerium Lanthanum Carbonate Fluoride)', imgUrl:'https://www.mindat.org/imagecache/ea/d9/08357120014947682282820.jpg'},
        {name: 'CORNETITE', sciName: '(Copper Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/f6/c3/01093030014946325064848.jpg'},
        {name: 'CORNWALLITE', sciName: '(Copper Arsenate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/a2/5d/06778730014946316886627.jpg'},
        {name: 'CORUNDUM', sciName: '(Aluminum Oxide)', imgUrl:'https://www.mindat.org/imagecache/11/3b/05249310014946376316370.jpg'},
        {name: 'COVELLITE', sciName: '(Copper Sulfide)', imgUrl:'https://www.mindat.org/imagecache/d2/60/09902870014950992964049.jpg'},
        {name: 'CREEDITE', sciName: '(Hydrated Calcium Aluminum Sulfate Fluoride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/b8/a9/09819570014946341301793.jpg'},
        {name: 'CRISTOBALITE', sciName: '(Silicon Dioxide)', imgUrl:'https://www.mindat.org/imagecache/de/a2/06564510014946287735653.jpg'},
        {name: 'CROCOITE', sciName: '(Lead Chromate)', imgUrl:'https://www.mindat.org/imagecache/f7/81/03688680014961059276714.jpg'},
        {name: 'CRYOLITE', sciName: '(Sodium Aluminum Fluoride)', imgUrl:'https://www.mindat.org/imagecache/b2/39/07068940014951184708336.jpg'},
        {name: 'CUBANITE', sciName: '(Copper Iron Sulfide)', imgUrl:'https://www.mindat.org/imagecache/27/0b/02158900014957063083613.jpg'},
        {name: 'CUMENGITE', sciName: '(Lead Copper Chloride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/89/48/06027410014946336498443.jpg'},
        {name: 'CUMMINGTONITE', sciName: '(Magnesium Iron Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/24/47/07546650014962199121462.jpg'},
        {name: 'CUPRITE', sciName: '(Copper Oxide)', imgUrl:'https://www.mindat.org/imagecache/4f/5c/05050230014946250477113.jpg'},
        {name: 'CUPROADAMITE', sciName: '(Copper Zinc Arsenate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/97/16/04360090014946649069979.jpg'},
        {name: 'CUPROSKLODOWSKITE', sciName: '(Hydrated Copper Uranyl Silicate)', imgUrl:'https://www.mindat.org/imagecache/94/d4/06407480014946994317461.jpg'},
        {name: 'CYANOTRICHITE', sciName: '(Hydrated Copper Aluminum Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/2f/ea/07179010014946605255009.jpg'},
        {name: 'CYLINDRITE', sciName: '(Iron Lead Tin Antimony Sulfide)', imgUrl:'https://www.mindat.org/imagecache/35/e4/02987280014946305863842.jpg'}
    ],
    d: [
        {name: 'DANBURITE', sciName: '(Calcium Boro-Silicate)', imgUrl:'https://www.mindat.org/imagecache/c0/eb/09753550014947137012475.jpg'},
        {name: 'DATOLITE', sciName: '(Calcium Boro-Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/89/e4/01926130014946263257725.jpg'},
        {name: 'DESCLOIZITE', sciName: '(Lead Zinc Vanadate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/bc/33/06282210014946928198294.jpg'},
        {name: 'DEMANTOID', sciName: '(variety of Andradite garnet)', imgUrl:'https://www.mindat.org/imagecache/c1/7e/03668380014946341799906.jpg'},
        {name: 'DIABOLEITE', sciName: '(Lead Copper Chloride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/12/0d/08473810014946511427078.jpg'},
        {name: 'DIAMOND', sciName: '(Carbon)', imgUrl:'https://www.mindat.org/imagecache/cf/b5/00533060014946244683365.jpg'},
        {name: 'DIGENITE', sciName: '(Copper Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Digenite.jpg/260px-Digenite.jpg'},
        {name: 'DIOPSIDE', sciName: '(Calcium Magnesium Silicate)', imgUrl:'https://www.mindat.org/imagecache/27/43/03571710014947899455082.jpg'},
        {name: 'DIOPTASE', sciName: '(Copper Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/5d/14/05761110014946259294604.jpg'},
        {name: 'DOLOMITE', sciName: '(Calcium Magnesium Carbonate)', imgUrl:'https://www.mindat.org/imagecache/82/b5/05084700014946244204604.jpg'},
        {name: 'DOMEYKITE', sciName: '(Copper Arsenide)', imgUrl:'https://www.mindat.org/imagecache/3d/34/03105450014962913347873.jpg'},
        {name: 'DRAVITE', sciName: '(complex Sodium Magnesium Iron Boro-Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/30/4a/05142670014950091701378.jpg'},
        {name: 'DUFRENITE', sciName: '(Hydrated Iron Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/81/82/00461400014949918446741.jpg'},
        {name: 'DUFTITE', sciName: '(Lead Calcium Copper Zinc Arsenate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/70/49/07214790014950956485592.jpg'},
        {name: 'DUMORTIERITE', sciName: '(Aluminum Borate Silicate Oxide)', imgUrl:'https://www.mindat.org/imagecache/ec/ab/09729080014946576468629.jpg'},
        {name: 'DUNDASITE', sciName: '(Hydrated Lead Aluminum Carbonate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/28/22/00640130014960831168903.jpg'},
        {name: 'DYSCRASITE', sciName: '(Silver Antimonide)', imgUrl:'https://www.mindat.org/imagecache/85/9f/08118450015004828506259.jpg'}
    ],
    e: [
        {name: 'EDENITE', sciName: '(Sodium Calcium Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/62/d1/01391140014960920304272.jpg'},
        {name: 'EDINGTONITE', sciName: '(Hydrated Barium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/df/bc/05093900014946244782529.jpg'},
        {name: 'ELBAITE', sciName: '(Sodium Lithium Aluminum Boro-Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/5a/c6/08630110014946276761464.jpg'},
        {name: 'ELPIDITE', sciName: '(Hydrated Sodium Zirconium Silicate)', imgUrl:'https://www.mindat.org/imagecache/3e/b2/01498700014947681899507.jpg'},
        {name: 'EMERALD', sciName: '(variety of Beryl- Berylium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/5e/f8/04122650014946250952182.jpg'},
        {name: 'EMMONSITE', sciName: '(Hydrated Iron Tellurite)', imgUrl:'https://www.mindat.org/imagecache/a1/39/02923290014950971361054.jpg'},
        {name: 'EMPLECTITE', sciName: '(Copper Bismuth Sulfide)', imgUrl:'https://www.mindat.org/imagecache/b7/44/01752830014946742556065.jpg'},
        {name: 'ENARGITE', sciName: '(Copper Arsenic Sulfide)', imgUrl:'https://www.mindat.org/imagecache/6c/7a/06096240014947102707411.jpg'},
        {name: 'ENSTATITE', sciName: '(Magnesium Silicate)', imgUrl:'https://www.mindat.org/imagecache/42/4c/07609290014950092061426.jpg'},
        {name: 'EOSPHORITE', sciName: '(Hydrated Manganese Aluminum Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/05/49/00851330014946272387507.jpg'},
        {name: 'EPIDIDYMITE', sciName: '(Sodium Beryllium Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/26/94/01481720014948468148672.jpg'},
        {name: 'EPIDOTE', sciName: '(Calcium Iron Aluminum Silicate Hydroxide)', imgUrl:'http://www.mineralminers.com/images/epidote/lrgh/epil101x-epidote-rough.jpg'},
        {name: 'EPISTILBITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/ba/15/07821340014977369792877.jpg'},
        {name: 'EPSOMITE', sciName: '(Hydrated Magnesium Sulfate)', imgUrl:'https://www.mindat.org/imagecache/bd/6f/09662270014948252182475.jpg'},
        {name: 'ERIONITE', sciName: '(Hydrated Potassium Sodium Calcium Magnesium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/8f/26/06170960014946287539878.jpg'},
        {name: 'ERYTHRITE', sciName: '(Hydrated Cobalt Arsenate)', imgUrl:'https://www.mindat.org/imagecache/a4/b3/09752570014946258316740.jpg'},
        {name: 'ESPERITE', sciName: '(Calcium Lead Zinc Silicate)', imgUrl:'https://www.mindat.org/imagecache/c3/eb/00834740014946267757606.jpg'},
        {name: 'ETTRINGITE', sciName: '(Hydrated Calcium Aluminum Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/93/c7/02809320014947262238337.jpg'},
        {name: 'EUCLASE', sciName: '(Beryllium Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/f6/ee/04898410014946295492411.jpg'},
        {name: 'EUCRYPTITE', sciName: '(Lithium Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/cf/37/06780660014946686354634.jpg'},
        {name: 'EUDIALYTE', sciName: '(Sodium Calcium Cerium Iron Manganese Zirconium Silicate Hydroxide Chloride)', imgUrl:'https://www.mindat.org/imagecache/3b/31/02312580014946284537229.jpg'},
        {name: 'EUDIDYMITE', sciName: '(Sodium Beryllium Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/2b/66/08549500014946634983781.jpg'},
        {name: 'EUXENITE', sciName: '(Yttrium Calcium Erbium Lanthanum Cerium Uranium Thorium Niobium Tantalum Titanium Oxide)', imgUrl:'https://www.mindat.org/imagecache/28/4f/00202300014946371498073.jpg'}
    ],
    f: [
        {name: 'FAYALITE', sciName: '(Magnesium Iron Silicate)', imgUrl:'https://www.mindat.org/imagecache/c1/4a/04802940014961948808802.jpg'},
        {name: 'FEDORITE', sciName: '(Hydrated Sodium Potassium Calcium Silicate Fluoride Chloride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/1b/b7/02297230014946694657352.jpg'},
        {name: 'FERBERITE', sciName: '(Iron Tungstate)', imgUrl:'https://www.mindat.org/imagecache/1e/e6/03384110014946255174001.jpg'},
        {name: 'FERRO-EDENITE', sciName:'(Sodium Calcium Iron Magnesium Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/c4/86/00189550014947069529967.jpg'},
        {name: 'FERROGLAUCOPHANE', sciName: '(Sodium Iron Magnesium Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/1a/8b/03054070014947845985133.jpg'},
        {name: 'FIEDLERITE', sciName: '(Lead Chloride Fluoride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/4f/b0/04992990014949494745719.jpg'},
        {name: 'FLINT', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:'https://www.mindat.org/imagecache/35/fa/07853370014947082787384.jpg'},
        {name: 'FLUORAPATITE', sciName: '(the fluorine rich apatite)', imgUrl:'https://www.mindat.org/imagecache/ed/9d/09772970014952597616179.jpg'},
        {name: 'FLUORITE', sciName: '(Calcium Fluoride)', imgUrl:'https://www.mindat.org/imagecache/d4/2c/00325690014946246489578.jpg'},
        {name: 'FLUORRICHTERITE', sciName: '(Sodium Calcium Magnesium Iron Silicate Hydroxide Fluoride)', imgUrl:'https://www.mindat.org/imagecache/bb/d6/07557810014946281191885.jpg'},
        {name: 'FORSTERITE', sciName: '(Iron Magnesium Silicate)', imgUrl:'https://www.mindat.org/imagecache/75/50/06365800014946252804950.jpg'},
        {name: 'FRANCKEITE', sciName: '(Lead Tin Iron Antimony Sulfide)', imgUrl:'https://www.mindat.org/imagecache/01/5c/07175520014946688937873.jpg'},
        {name: 'FRANKLINITE', sciName: '(Zinc Manganese Iron Oxide)', imgUrl:'https://www.mindat.org/imagecache/2d/b5/03592810014947916632841.jpg'},
        {name: 'FUCHSITE', sciName: '(the chromium-rich muscovite)', imgUrl:'https://www.mindat.org/imagecache/0b/b9/09354410014946252903946.jpg'},
        {name: 'FULGARITE', sciName: '(lightning-created Lechatelierite, Silicon Dioxide)', imgUrl:'https://www.mindat.org/imagecache/a3/7d/00784090014946318127527.jpg'}
    ],
    g: [
        {name: 'GADOLINITE', sciName: '(Yttrium Iron Beryllium Silicate)', imgUrl:''},
        {name: 'GAHNITE', sciName: '(Zinc Aluminum Oxide)', imgUrl:''},
        {name: 'GALENA', sciName: '(Lead Sulfide)', imgUrl:''},
        {name: 'GARNET', sciName: '(Group)', imgUrl:''},
        {name: 'GASPEITE', sciName: '(Nickel Magnesium Iron Carbonate)', imgUrl:''},
        {name: 'GAYLUSSITE', sciName: '(Hydrated Sodium Calcium Carbonate)', imgUrl:''},
        {name: 'GERSDORFFITE', sciName: '(Nickel Arsenide Sulfide)', imgUrl:''},
        {name: 'GIBBSITE', sciName: '(Aluminum Hydroxide)', imgUrl:''},
        {name: 'GLAUBERITE', sciName: '(Sodium Calcium Sulfate)', imgUrl:''},
        {name: 'GLAUCOPHANE', sciName: '(Sodium Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'GMELINITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'GOETHITE', sciName: '(Hydrated Iron Oxide)', imgUrl:''},
        {name: 'GOLD', sciName: '(Au)', imgUrl:''},
        {name: 'GOOSECREEKITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'GORMANITE', sciName: '(Hydrated Iron Magnesium Aluminum Phosphate Hydroxide)', imgUrl:''},
        {name: 'GOSHENITE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:''},
        {name: 'GRAEMITE', sciName: '(Hydrated Copper Tellurate)', imgUrl:''},
        {name: 'GRATONITE', sciName: '(Lead Arsenic Sulfide)', imgUrl:''},
        {name: 'GREENOCKITE', sciName: '(Cadmium Sulfide)', imgUrl:''},
        {name: 'GROSSULAR', sciName: '(Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'GYPSUM', sciName: '(Hydrated Calcium Sulfate)', imgUrl:''},
        {name: 'GYROLITE', sciName: '(Hydrated Calcium Silicate Hydroxide)', imgUrl:''}
    ],
    h: [
        {name: 'HACKMANITE', sciName: '(variety of Sodalite, Sodium Aluminum Silicate Chloride)', imgUrl:''},
        {name: 'HALITE', sciName: '(Sodium Chloride)', imgUrl:''},
        {name: 'HANKSITE', sciName: '(Potassium Sodium Sulfate Carbonate Chloride)', imgUrl:''},
        {name: 'HARDYSTONITE', sciName: '(Calcium Zinc Silicate)', imgUrl:''},
        {name: 'HARMOTOME', sciName: '(Hydrated Barium Potasium Aluminum Silicate)', imgUrl:''},
        {name: 'HAUSMANNITE', sciName: '(Manganese Oxide)', imgUrl:''},
        {name: 'HEDENBERGITE', sciName: '(Calcium Iron Silicate)', imgUrl:''},
        {name: 'HEDYPHANE', sciName: '(Lead Calcium Arsenate Chloride)', imgUrl:''},
        {name: 'HELIODOR', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:''},
        {name: 'HEMATITE', sciName: '(Iron Oxide)', imgUrl:''},
        {name: 'HEMIMORPHITE', sciName: '(Hydrated Zinc Silicate Hydroxide)', imgUrl:''},
        {name: 'HERDERITE', sciName: '(Calcium Beryllium Phosphate Fluoride Hydroxide)', imgUrl:''},
        {name: 'HESSITE', sciName: '(Silver Telluride)', imgUrl:''},
        {name: 'HESSONITE', sciName: '(variety of Grossular garnet)', imgUrl:''},
        {name: 'HEULANDITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'HIDDENITE', sciName: '(variety of Spodumene)', imgUrl:''},
        {name: 'HILAIRITE', sciName: '(Hydrated Sodium Zirconium Silicate)', imgUrl:''},
        {name: 'HINSDALITE', sciName: '(Lead Strontium Aluminum Phosphate Sulfate Hydroxide)', imgUrl:''},
        {name: 'HODGKINSONITE', sciName: '(Manganese Zinc Silicate Hydroxide)', imgUrl:''},
        {name: 'HOPEITE', sciName: '(Hydrated Zinc Phosphate)', imgUrl:''},
        {name: 'HORNBLEND', sciName: '(Calcium Sodium Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'HOWLITE', sciName: '(Calcium Boro-Silicate Hydroxide)', imgUrl:''},
        {name: 'HUEBNERITE', sciName: '(Manganese Tungstate)', imgUrl:''},
        {name: 'HUMITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)', imgUrl:''},
        {name: 'HUREAULITE', sciName: '(Hydrated Manganese Phosphate Hydroxide)', imgUrl:''},
        {name: 'HYDROBORACITE', sciName: '(Hydrated Calcium Magnesium Borate)', imgUrl:''},
        {name: 'HYDROMAGNESITE', sciName: '(Hydrated Magnesium Carbonate Hydroxide)', imgUrl:''},
        {name: 'HYDROXYLBASTNASITE', sciName: '(Cerium Lanthanum Neodymium Carbonate Hydroxide Fluoride)', imgUrl:''},
        {name: 'HYDROZINCITE', sciName: '(Hydrated Zinc Carbonate)', imgUrl:''},
        {name: 'HYPERSTHENE', sciName: '(Magnesium Iron Silicate)', imgUrl:''}
    ],
    i: [
        {name: 'IDOCRASE', sciName: '(alternate name of Vesuvianite)', imgUrl:'https://www.mindat.org/imagecache/8b/2f/02493850015065740941059.jpg'},
        {name: 'ILVAITE', sciName: '(Calcium Iron Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/09/b8/07101170014946262813684.jpg'},
        {name: 'ILMENITE', sciName: '(Iron Titanium Oxide)', imgUrl:'https://www.mindat.org/imagecache/03/e8/07032780014946253574005.jpg'},
        {name: 'INDICOLITE', sciName: '(blue variety of Elbaite tourmaline)', imgUrl:'https://www.mindat.org/imagecache/59/25/03274050014946257476581.jpg'},
        {name: 'INESITE', sciName: '(Hydrated Calcium Manganese Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/74/e2/06832510014962943878749.jpg'},
        {name: 'IOLITE', sciName: '(variety of Cordierite)', imgUrl:'https://www.mindat.org/imagecache/cd/eb/09772070014947045134795.jpg'}
    ],
    j: [
        {name: 'JADE', sciName: '(gem variety of both Jadeite and Nephrite (variety of Actinolite))', imgUrl:'https://www.mindat.org/imagecache/9a/66/04209570014946693579254.jpg'},
        {name: 'JADEITE', sciName: '(Sodium Iron Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/67/20/03291890014951404593433.jpg'},
        {name: 'JAMESONITE', sciName: '(Lead Iron Antimony Sulfide)', imgUrl:'https://www.mindat.org/imagecache/26/e2/05572510014949076408765.jpg'},
        {name: 'JAROSITE', sciName: '(Potassium Iron Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/4e/80/00125020014946273613770.jpg'},
        {name: 'JASPER', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:'https://www.mindat.org/imagecache/29/38/03006410014946264955009.jpg'},
        {name: 'JOAQUINITE', sciName: '(Barium Sodium Cesium Titanium Niobium Iron Silicate Hydroxide Fluoride)', imgUrl:'https://www.mindat.org/imagecache/fd/2c/01415550014961439104291.jpg'},
        {name: 'JORDANITE', sciName: '(Lead Arsenic Antimony Sulfide)', imgUrl:'https://www.mindat.org/imagecache/17/1d/05818710014977288332045.jpg'}
    ],
    k: [
        {name: 'KAOLINITE', sciName: '(Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/ac/3c/04167250014961268482745.jpg'},
        {name: 'KERMESITE', sciName: '(Antimony Oxysulfide)', imgUrl:'https://www.mindat.org/imagecache/e8/9e/06556210014946684124296.jpg'},
        {name: 'KERNITE', sciName: '(Hydrated Sodium Borate)', imgUrl:'https://www.mindat.org/imagecache/56/6e/01196400014947172503796.jpg'},
        {name: 'KIDWELLITE', sciName: '(Hydrated Sodium Iron Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/df/dd/05996760014946373563048.jpg'},
        {name: 'KIESERITE', sciName: '(Hydrated Magnesium Sulfate)', imgUrl:'https://www.mindat.org/imagecache/63/2b/01579560014947901362872.jpg'},
        {name: 'KINOITE', sciName: '(Hydrated Calcium Copper Silicate)', imgUrl:'https://www.mindat.org/imagecache/27/18/03054460014948471924404.jpg'},
        {name: 'KOLWEZITE', sciName: '(Copper Cobalt Carbonate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/7a/8f/01866410014947156016266.jpg'},
        {name: 'KORNERUPINE', sciName: '(Magnesium Aluminum Iron Boro-silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/fd/60/08842920014946472316563.jpg'},
        {name: 'KOTTIGITE', sciName: '(Hydrated Zinc Arsenate)', imgUrl:'https://www.mindat.org/imagecache/99/0a/04934080014977199627926.jpg'},
        {name: 'KOVDORSKITE', sciName: '(Hydrated Magnesium Carbonate Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/e7/87/05614130014946327295678.jpg'},
        {name: 'KTENASITE', sciName: '(Hydrated Copper Zinc Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/78/b7/02046850014947185106897.jpg'},
        {name: 'KULANITE', sciName: '(Barium Iron Manganese Magnesium Aluminum Phosphate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/77/e4/09494420014948989478211.jpg'},
        {name: 'KUNZITE', sciName: '(variety of Spodumene)', imgUrl:'https://www.mindat.org/imagecache/d3/74/03182690014946265376553.jpg'},
        {name: 'KUPLETSKITE', sciName: '(Potassium Sodium Manganese Iron Titanium Niobium Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/7c/97/06506850014947003276106.jpg'},
        {name: 'KUTNOHORITE', sciName: '(Calcium Magnesium Carbonate)', imgUrl:'https://www.mindat.org/imagecache/60/d8/05731320014946335823896.jpg'},
        {name: 'KYANITE', sciName: '(Aluminum Silicate)', imgUrl:'https://www.mindat.org/imagecache/7d/db/09152950014946251642500.jpg'}
    ],
    l: [
        {name: 'LABRADORITE', sciName: '(Calcium Sodium Aluminum Silicate)', imgUrl:''},
        {name: 'LARDERELLITE', sciName: '(Ammonium Borate Hydroxide)', imgUrl:''},
        {name: 'LARIMAR', sciName: '(variety of Pectolite)', imgUrl:''},
        {name: 'LAUEITE', sciName: '(Hydrated Manganese Iron Phosphate Hydroxide)', imgUrl:''},
        {name: 'LAUMONTITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'LAURIONITE', sciName: '(Lead Chloride Hydroxide)', imgUrl:''},
        {name: 'LAZULITE', sciName: '(Magnesium Aluminum Phosphate Hydroxide)', imgUrl:''},
        {name: 'LAZURITE', sciName: '(Sodium Calcium Aluminum Silicate Sulfate)', imgUrl:''},
        {name: 'LEADHILLITE', sciName: '(Lead Sulfate Carbonate Hydroxide)', imgUrl:''},
        {name: 'LECHATELIERITE', sciName: '(Silicon Dioxide)', imgUrl:''},
        {name: 'LEGRANDITE', sciName: '(Hydrated Zinc Arsenate Hydroxide)', imgUrl:''},
        {name: 'LEIFITE', sciName: '(Hydrated Sodium Beryllium Aluminum Silicate Hydroxide Fluoride)', imgUrl:''},
        {name: 'LEPIDOLITE', sciName: '(Potassium Lithium Aluminum Silicate Hydroxide Fluoride)', imgUrl:''},
        {name: 'LEUCITE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
        {name: 'LEUCOPHANITE', sciName: '(Sodium Calcium Beryllium Silicate Fluoride)', imgUrl:''},
        {name: 'LIBETHENITE', sciName: '(Copper Phosphate Hydroxide)', imgUrl:''},
        {name: 'LIMONITE', sciName: '(Hydrated Iron Oxide Hydroxide)', imgUrl:''},
        {name: 'LINARITE', sciName: '(Lead Copper Sulfate hydroxide)', imgUrl:''},
        {name: 'LINNAEITE', sciName: '(Cobalt Sulfide)', imgUrl:''},
        {name: 'LIROCONITE', sciName: '(Hydrated Copper Aluminum Arsenate Hydroxide)', imgUrl:''},
        {name: 'LITHIOPHILITE', sciName: '(Lithium Manganese Iron Phosphate)', imgUrl:''},
        {name: 'LOLLINGITE', sciName: '(Iron Arsenide)', imgUrl:''},
        {name: 'LORENZENITE', sciName: '(Sodium Titanium Silicate)', imgUrl:''},
        {name: 'LARIMAR', sciName: '(variety of Pectolite)', imgUrl:''},
        {name: 'LUDLAMITE', sciName: '(Hydrated Iron Magnesium Manganese Phosphate)', imgUrl:''}
    ],
    m: [
        {name: 'MACPHERSONITE', sciName: '(Lead Sulfate Carbonate Hydroxide)', imgUrl:''},
        {name: 'MAGNESITE', sciName: '(Magnesium Carbonate)', imgUrl:''},
        {name: 'MAGNETITE', sciName: '(Iron Oxide)', imgUrl:''},
        {name: 'MALACHITE', sciName: '(Hydrated Copper Carbonate)', imgUrl:''},
        {name: 'MANGANBABINGTONITE', sciName: '(Calcium Manganese Iron Silicate Hydroxide)', imgUrl:''},
        {name: 'MANGANITE', sciName: '(Manganese Oxide Hydroxide)', imgUrl:''},
        {name: 'MARCASITE', sciName: '(Iron Sulfide)', imgUrl:''},
        {name: 'MASSICOT', sciName: '(Lead Oxide)', imgUrl:''},
        {name: 'MELANOPHLOGITE', sciName: '(Silicon Oxide with organic compounds)', imgUrl:''},
        {name: 'MELANTERITE', sciName: '(Hydrated Iron Sulfate)', imgUrl:''},
        {name: 'MENEGHINITE', sciName: '(Lead Antimony Sulfide)', imgUrl:''},
        {name: 'MESOLITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'META-ANKOLEITE', sciName: '(Hydrated Potassium Uranyl Phosphate)', imgUrl:''},
        {name: 'META-AUTUNITE', sciName: '(Hydrated Calcium Uranyl Phosphate)', imgUrl:''},
        {name: 'META-TORBERNITE', sciName: '(Hydrated Copper Uranyl Phosphate)', imgUrl:''},
        {name: 'META-URANOCIRCITE', sciName: '(Hydrated Barium Uranyl Phosphate)', imgUrl:''},
        {name: 'META-VARISCITE', sciName: '(Hydrated Aluminum Phosphate)', imgUrl:''},
        {name: 'META-ZEUNERITE', sciName: '(Hydrated Copper Uranyl Arsenate)', imgUrl:''},
        {name: 'MIARGYRITE', sciName: '(Silver Antimony Sulfide)', imgUrl:''},
        {name: 'MICROCLINE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
        {name: 'MICROLITE', sciName: '(Calcium Sodium Tantalum Oxide Hydroxide Fluoride)', imgUrl:''},
        {name: 'MILARITE', sciName: '(Hydrated Potassium Calcium Aluminum Beryllium Silicate)', imgUrl:''},
        {name: 'MILLERITE', sciName: '(Nickel Sulfide)', imgUrl:''},
        {name: 'MIMETITE', sciName: '(Lead Chloroarsenate)', imgUrl:''},
        {name: 'MINASGERAISITE', sciName: '- (Y) (Calcium Yttrium Beryllium Silicate)', imgUrl:''},
        {name: 'MINIUM', sciName: '(Lead Oxide)', imgUrl:''},
        {name: 'MIXITE', sciName: '(Hydrated Bismuth Copper Arsenate Hydroxide)', imgUrl:''},
        {name: 'MOCTEZUMITE', sciName: '(Lead Uranyl Tellurite)', imgUrl:''},
        {name: 'MOISSANITE', sciName: '(Silicon Carbide)', imgUrl:''},
        {name: 'MOLDAVITE', sciName: '(variety of Tecktite: Meteoric Silica Glass)', imgUrl:''},
        {name: 'MOLYBDENITE', sciName: '(Molybdenum Sulfide)', imgUrl:''},
        {name: 'MONAZITE', sciName: '(Cerium Lanthanum Thorium Neodymium Yttrium Phosphate)', imgUrl:''},
        {name: 'MONTEBRASITE', sciName: '(Lithium Sodium Aluminum Phosphate Hydroxide Fluoride)', imgUrl:''},
        {name: 'MONTMORILLONITE', sciName: '(Hydrated Sodium Calcium Aluminum Magnesium Silicate Hydroxide)', imgUrl:''},
        {name: 'MOONSTONE', sciName: '(variety of Oligoclase, Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'MORDENITE', sciName: '(Hydrated Calcium Sodium Potassium Aluminum Silicate)', imgUrl:''},
        {name: 'MORGANITE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:''},
        {name: 'MOSCHELLANDSBERGITE', sciName: '(Silver Mercury or Silver Amalgam)', imgUrl:''},
        {name: 'MOTTRAMITE', sciName: '(Lead Copper Vanadate Hydroxide)', imgUrl:''},
        {name: 'MURMANITE', sciName: '(Hydrated Sodium Titanium Niobium Silicate)', imgUrl:''},
        {name: 'MUSCOVITE', sciName: '(Potassium Aluminum Silicate Hydroxide Fluoride)', imgUrl:''}
    ],
    n: [
        {name: 'NAGYAGITE', sciName: '(Lead Gold Antimony Bismuth Telluride Sulfide)', imgUrl:''},
        {name: 'NAHCOLITE', sciName: '(Sodium Bicarbonate)', imgUrl:''},
        {name: 'NARSARSUKITE', sciName: '(Sodium Titanium Iron Silicate Fluoride)', imgUrl:''},
        {name: 'NATROJAROSITE', sciName: '(Sodium Iron Sulfate Hydroxide)', imgUrl:''},
        {name: 'NATROLITE', sciName: '(Hydrated Sodium Aluminum Silicate)', imgUrl:''},
        {name: 'NEALITE', sciName: '(Lead Iron Arsenate Chloride)', imgUrl:''},
        {name: 'NEPHELINE', sciName: '(Sodium Potassium Aluminum Silicate)', imgUrl:''},
        {name: 'NEPHRITE', sciName: '(variety of Actinolite, Calcium Magnesium Iron Silicate Hydroxide)', imgUrl:''},
        {name: 'NEPTUNITE', sciName: '(Potassium Sodium Lithium Iron Manganese Titanium Silicate)', imgUrl:''},
        {name: 'NICKELINE', sciName: '(Nickel Arsenide)', imgUrl:''},
        {name: 'NITER', sciName: '(Potasium Nitrate)', imgUrl:''},
        {name: 'NITRATINE', sciName: '(Sodium Nitrate)', imgUrl:''},
        {name: 'NORBERGITE', sciName: '(Magnesium Silicate Fluoride Hydroxide)', imgUrl:''}
    ],
    o: [
        {name: 'OBSIDIAN', sciName: '(Volcanic Silica Glass)', imgUrl:''},
        {name: 'OKENITE', sciName: '(Hydrated Calcium Silicate)', imgUrl:''},
        {name: 'OLIGOCLASE', sciName: '(Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'OLIVINE', sciName: '(Magnesium Iron Silicate)', imgUrl:''},
        {name: 'OLIVENITE', sciName: '(Copper Arsenate Hydroxide)', imgUrl:''},
        {name: 'ONYX', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
        {name: 'OPAL', sciName: '(Hydrated Silica)', imgUrl:''},
        {name: 'ORPIMENT', sciName: '(Arsenic Sulfide)', imgUrl:''},
        {name: 'ORTHOCLASE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
        {name: 'OSBORNITE', sciName: '(Titanium Nitride)', imgUrl:''},
        {name: 'OSUMILITE', sciName: '(Hydrated Potassium Sodium Iron Magnesium Aluminum Silicate)', imgUrl:''},
        {name: 'OTAVITE', sciName: '(Cadmium Carbonate)', imgUrl:''}
    ],
    p: [
        {name: 'PACHNOLITE', sciName: '(Hydrated Sodium Calcium Aluminum Fluoride)', imgUrl:''},
        {name: 'PALYGORSKITE', sciName: '(Hydrated Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'PAPAGOITE', sciName: '(Calcium Copper Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'PARADAMITE', sciName: '(Zinc Arsenate Hydroxide)', imgUrl:''},
        {name: 'PARASYMPLESITE', sciName: '(Hydrated Iron Arsenate)', imgUrl:''},
        {name: 'PARAVAUXITE', sciName: '(Hydrated Iron Aluminum Phosphate Hydroxide)', imgUrl:''},
        {name: 'PARISITE', sciName: '(Calcium Cerium Lanthanum Neodymium Carbonate Fluoride)', imgUrl:''},
        {name: 'PECTOLITE', sciName: '(Sodium Calcium Silicate Hydroxide)', imgUrl:''},
        {name: 'PENTLANDITE', sciName: '(Iron Nickel Sulfide)', imgUrl:''},
        {name: 'PERICLASE', sciName: '(Magnesium Oxide)', imgUrl:''},
        {name: 'PEROVSKITE', sciName: '(Calcium Titanium Oxide)', imgUrl:''},
        {name: 'PHARMACOLITE', sciName: '(Hydrated Calcium Arsenate Hydroxide)', imgUrl:''},
        {name: 'PHARMACOSIDERITE', sciName: '(Hydrated Potassium Iron Arsenate Hydroxide)', imgUrl:''},
        {name: 'PHENAKITE', sciName: '(Berylium Silicate)', imgUrl:''},
        {name: 'PHILLIPSITE', sciName: '(Hydrated Potasium Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'PHLOGOPITE', sciName: '(Potassium Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'PHOSGENITE', sciName: '(Lead Carbonate Chloride)', imgUrl:''},
        {name: 'PHOSPHOPHYLLITE', sciName: '(Hydrated Zinc Iron Manganese Phosphate)', imgUrl:''},
        {name: 'PHOSPHURANYLITE', sciName: '(Hydrated Calcium Uranyl Phosphate Hydroxide)', imgUrl:''},
        {name: 'PICROMERITE', sciName: '(Hydrated Potassium Magnesium Sulfate)', imgUrl:''},
        {name: 'PIRSSONITE', sciName: '(Hydrated Sodium Calcium Carbonate)', imgUrl:''},
        {name: 'PLANCHEITE', sciName: '(Hydrated Copper Silicate Hydroxide)', imgUrl:''},
        {name: 'PLATINUM', sciName: '(Pt)', imgUrl:''},
        {name: 'PLATTNERITE', sciName: '(Lead Oxide)', imgUrl:''},
        {name: 'POLYBASITE', sciName: '(Silver Copper Antimony Sulfide)', imgUrl:''},
        {name: 'POLYHALITE', sciName: '(Hydrated Potassium Calcium Magnesium Sulfate)', imgUrl:''},
        {name: 'POLYLITHIONITE', sciName: '(Potassium Lithium Aluminum Silicate Fluoride)', imgUrl:''},
        {name: 'POWELLITE', sciName: '(Calcium Molybdenate)', imgUrl:''},
        {name: 'PRASIOLITE', sciName: '(variety of Quartz)', imgUrl:''},
        {name: 'PREHNITE', sciName: '(Calcium Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'PROUSTITE', sciName: '(Silver Arsenic Sulfide)', imgUrl:''},
        {name: 'PSEUDOBOLEITE', sciName: '(Lead Copper Chloride Hydroxide)', imgUrl:''},
        {name: 'PSEUDOBROOKITE', sciName: '(Iron Titanium Oxide)', imgUrl:''},
        {name: 'PSEUDOMALACHITE', sciName: '(Copper Phosphate Hydroxide)', imgUrl:''},
        {name: 'PSILOMELANE', sciName: '(Manganese Oxide)', imgUrl:''},
        {name: 'PUCHERITE', sciName: '(Bismuth Vanadate)', imgUrl:''},
        {name: 'PURPURITE', sciName: '(Manganese Phosphate)', imgUrl:''},
        {name: 'PYRARGYRITE', sciName: '(Silver Antimony Sulfide)', imgUrl:''},
        {name: 'PYRITE', sciName: '(Iron Sulfide)', imgUrl:''},
        {name: 'PYROAURITE', sciName: '(Hydrated Magnesium Iron Carbonate Hydroxide)', imgUrl:''},
        {name: 'PYROCHLORE', sciName: '(Calcium Sodium Niobium Oxide Hydroxide Fluoride)', imgUrl:''},
        {name: 'PYROLUSITE', sciName: '(Manganese Oxide)', imgUrl:''},
        {name: 'PYROMORPHITE', sciName: '(Lead Chlorophosphate)', imgUrl:''},
        {name: 'PYROPE', sciName: '(Magnesium Aluminum Silicate)', imgUrl:''},
        {name: 'PYROPHYLLITE', sciName: '(Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'PYRRHOTITE', sciName: '(Iron Sulfide)', imgUrl:''}
    ],
    q: [
        {name: 'QUARTZ', sciName: '(Silicon Oxide)', imgUrl:''},
        {name: 'QUETZALCOATLITE', sciName: '(Zinc Copper Tellurite Hydroxide)', imgUrl:''}
    ],
    r: [
        {name: 'RAITE', sciName: '(Hydrated Sodium Calcium Manganese Titanium Iron Silicate Hydroxide)', imgUrl:''},
        {name: 'RAMMELSBERGITE', sciName: '(Nickel Arsenide)', imgUrl:''},
        {name: 'RAMSDELLITE', sciName: '(Manganese Oxide)', imgUrl:''},
        {name: 'REALGAR', sciName: '(Arsenic Sulfide)', imgUrl:''},
        {name: 'RHABDOPHANE', sciName: '(Hydrated Cerium Lanthanum Neodymium Phosphate)', imgUrl:''},
        {name: 'RHENIITE', sciName: '(Rhenium Sulfide)', imgUrl:''},
        {name: 'RHODIZITE', sciName: '(Potassium Cesium Beryllium Aluminum Borate)', imgUrl:''},
        {name: 'RHODOCHROSITE', sciName: '(Manganese Carbonate)', imgUrl:''},
        {name: 'RHODOLITE', sciName: '(variety of PYROPE garnet, Magnesium Aluminum Silicate)', imgUrl:''},
        {name: 'RHODONITE', sciName: '(Manganese Iron Magnesium Calcium Silicate)', imgUrl:''},
        {name: 'RICHTERITE', sciName: '(Sodium Calcium Magnesium Iron Silicate Hydroxide)', imgUrl:''},
        {name: 'RIEBECKITE', sciName: '(Sodium Iron Magnesium Silicate Hydroxide)', imgUrl:''},
        {name: 'ROCKBRIDGEITE', sciName: '(Iron Manganese Phosphate Hydroxide)', imgUrl:''},
        {name: 'ROMANECHITE', sciName: '(Hydrated Barium Manganese Oxide)', imgUrl:''},
        {name: 'ROSASITE', sciName: '(Copper Zinc Carbonate Hydroxide)', imgUrl:''},
        {name: 'ROSE QUARTZ', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:''},
        {name: 'ROSELITE', sciName: '(Hydrated Calcium Cobalt Magnesium Arsenate)', imgUrl:''},
        {name: 'RUBY', sciName: '(variety of Corundum- Aluminum Oxide)', imgUrl:''},
        {name: 'RUTILE', sciName: '(Titanium Oxide)', imgUrl:''}
    ],
    s: [
        {name: 'SAFFLORITE', sciName: '(Cobalt Iron Arsenide)', imgUrl:''},
        {name: 'SAINFELDITE', sciName: '(Hydrated Calcium Arsenate Hydroxide)', imgUrl:''},
        {name: 'SAL AMMONIAC', sciName: '(Ammonium Chloride)', imgUrl:''},
        {name: 'SAMARSKITE', sciName: '(Yttrium Cerium Uranium Iron Niobium Tantalum Titanium Oxide)', imgUrl:''},
        {name: 'SANBORNITE', sciName: '(Barium Silicate)', imgUrl:''},
        {name: 'SANIDINE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
        {name: 'SAPPHIRE', sciName: '(variety of Corundum- Aluminum Oxide)', imgUrl:''},
        {name: 'SARD', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
        {name: 'SARDONYX', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
        {name: 'SARTORITE', sciName: '(Lead Arsenic Sulfide)', imgUrl:''},
        {name: 'SCAPOLITE', sciName: '(Sodium Calcium Aluminum Silicate Chloride Carbonate Sulfate)', imgUrl:''},
        {name: 'SCHEELITE', sciName: '(Calcium Tungstate)', imgUrl:''},
        {name: 'SCHMITTERITE', sciName: '(Uranyl Tellurite)', imgUrl:''},
        {name: 'SCHOLZITE', sciName: '(Hydrated Calcium Zinc Phosphate)', imgUrl:''},
        {name: 'SCHORL', sciName: '(complex Sodium Iron Boro-Aluminum Silicate)', imgUrl:''},
        {name: 'SCHROCKINGERITE', sciName: '(Hydrated Sodium Calcium Uranyl Sulfate Carbonate Fluoride)', imgUrl:''},
        {name: 'SCOLECITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'SCORODITE', sciName: '(Hydrated Iron Arsenate)', imgUrl:''},
        {name: 'SCORZALITE', sciName: '(Iron Magnesium Aluminum Phosphate Hydroxide)', imgUrl:''},
        {name: 'SELENITE', sciName: '(alternate name for Gypsum)', imgUrl:''},
        {name: 'SEMSEYITE', sciName: '(Lead Antimony Sulfide)', imgUrl:''},
        {name: 'SENARMONTITE', sciName: '(Antimony Oxide)', imgUrl:''},
        {name: 'SERANDITE', sciName: '(Sodium Manganese Calcium Silicate Hydroxide)', imgUrl:''},
        {name: 'SERPENTINE', sciName: '(Iron Magnesium Nickel Silicate Hydroxide)', imgUrl:''},
        {name: 'SHATTUCKITE', sciName: '(Copper Silicate Hydroxide)', imgUrl:''},
        {name: 'SIDERITE', sciName: '(Iron Carbonate)', imgUrl:''},
        {name: 'SILLIMANITE', sciName: '(Aluminum Silicate)', imgUrl:''},
        {name: 'SILVER', sciName: '(Ag)', imgUrl:''},
        {name: 'SINHALITE', sciName: '(Magnesium Aluminum Borate)', imgUrl:''},
        {name: 'SJOGRENITE', sciName: '(Hydrated Magnesium Iron Carbonate Hydroxide)', imgUrl:''},
        {name: 'SKLODOWSKITE', sciName: '(Hydrated Magnesium Uranyl Silicate)', imgUrl:''},
        {name: 'SKUTTERUDITE', sciName: '(Cobalt Arsenide)', imgUrl:''},
        {name: 'SMITHSONITE', sciName: '(Zinc Carbonate)', imgUrl:''},
        {name: 'SMOKY QUARTZ', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:''},
        {name: 'SODALITE', sciName: '(Sodium Aluminum Silicate Chloride)', imgUrl:''},
        {name: 'SPANGOLITE', sciName: '(Hydrated Copper Aluminum Sulfate Chloride Hydroxide)', imgUrl:''},
        {name: 'SPERRYLITE', sciName: '(Platinum Arsenide)', imgUrl:''},
        {name: 'SPESSARTINE', sciName: '(Manganese Aluminum Silicate)', imgUrl:''},
        {name: 'SPHAEROCOBALTITE', sciName: '(Cobalt Carbonate)', imgUrl:''},
        {name: 'SPHALERITE', sciName: '(Zinc Iron Sulfide)', imgUrl:''},
        {name: 'SPHENE', sciName: '(Calcium Titanium Silicate)', imgUrl:''},
        {name: 'SPINEL', sciName: '(Magnesium Aluminum Oxide)', imgUrl:''},
        {name: 'SPODUMENE', sciName: '(Lithium Aluminum Silicate)', imgUrl:''},
        {name: 'STAUROLITE', sciName: '(Iron Magnesium Zinc Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'STELLERITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'STEPHANITE', sciName: '(Silver Antimony Sulfide)', imgUrl:''},
        {name: 'STIBARSEN', sciName: '(Antimony Arsenic)', imgUrl:''},
        {name: 'STIBICONITE', sciName: '(Antimony Oxide Hydroxide)', imgUrl:''},
        {name: 'STIBNITE', sciName: '(Antimony Sulfide)', imgUrl:''},
        {name: 'STICHTITE', sciName: '(Hydrated Magnesium Chromium Carbonate Hydroxide)', imgUrl:''},
        {name: 'STILBITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'STISHOVITE', sciName: '(Silicon Dioxide)', imgUrl:''},
        {name: 'STRENGITE', sciName: '(Hydrated Iron Phosphate)', imgUrl:''},
        {name: 'STRONTIANITE', sciName: '(Strontium Carbonate)', imgUrl:''},
        {name: 'STRUNZITE', sciName: '(Calcium Zinc Arsenate Hydroxide)', imgUrl:''},
        {name: 'STURMANITE', sciName: '(Hydrated Calcium Iron Aluminum Manganese Sulfate Tetrahydroxoborate Hydroxide)', imgUrl:''},
        {name: 'SUGILITE', sciName: '(Potassium Sodium Lithium Iron Manganese Aluminum Silicate)', imgUrl:''},
        {name: 'SULFUR', sciName: '(S)', imgUrl:''},
        {name: 'SUNSTONE', sciName: '(variety of Oligoclase, Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'SUOLUNITE', sciName: '(Hydrated Calcium Silicate Hydroxide)', imgUrl:''},
        {name: 'SUSANNITE', sciName: '(Lead Sulfate Carbonate Hydroxide)', imgUrl:''},
        {name: 'SUSSEXITE', sciName: '(Manganese Borate Hydroxide)', imgUrl:''},
        {name: 'SVANBERGITE', sciName: '(Strontium Aluminum Phosphate Sulfate Hydroxide)', imgUrl:''},
        {name: 'SYLVANITE', sciName: '(Silver Gold Telluride)', imgUrl:''},
        {name: 'SYLVITE', sciName: '(Potassium Chloride)', imgUrl:''},
        {name: 'SYMPLESITE', sciName: '(Hydrated Iron Arsenate)', imgUrl:''},
        {name: 'SYNCHYSITE', sciName: '(Calcium Cerium Lanthanum Neodymium Yttrium Carbonate Fluoride)', imgUrl:''}
    ],
    t: [
        {name: 'TAAFFEITE', sciName: '(Beryllium Magnesium Aluminum Oxide)', imgUrl:''},
        {name: 'TAINIOLITE', sciName: '(Potassium Lithium Magnesium Silicate Fluoride)', imgUrl:''},
        {name: 'TALC', sciName: '(Magnesium Silicate Hydroxide)', imgUrl:''},
        {name: 'TANTALITE', sciName: '(Iron Manganese Tantalum Niobium Oxide)', imgUrl:''},
        {name: 'TANZANITE', sciName: '(gem variety of Zoisite)', imgUrl:''},
        {name: 'TARBUTTITE', sciName: '(Zinc Phosphate Hydroxide)', imgUrl:''},
        {name: 'TEALLITE', sciName: '(Lead Tin Sulfide)', imgUrl:''},
        {name: 'TEKTITES', sciName: '(Meteoric Silica Glass)', imgUrl:''},
        {name: 'TELLURIUM', sciName: '(Te)', imgUrl:''},
        {name: 'TENNANTITE', sciName: '(Copper Arsenic Sulfide)', imgUrl:''},
        {name: 'TEPHROITE', sciName: '(Manganese Silicate)', imgUrl:''},
        {name: 'TETRAHEDRITE', sciName: '(Copper Antimony Sulfide)', imgUrl:''},
        {name: 'THAUMASITE', sciName: '(Hydrated Calcium Silicon Carbonate Sulfate Hydroxide)', imgUrl:''},
        {name: 'THENARDITE', sciName: '(Sodium Sulfate)', imgUrl:''},
        {name: 'THOMSONITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
        {name: 'THORITE', sciName: '(Thorium Uranium Silicate)', imgUrl:''},
        {name: 'THOROGUMMITE', sciName: '(Thorium Uranium Silicate Hydroxide)', imgUrl:''},
        {name: 'TIN', sciName: '(Sn)', imgUrl:''},
        {name: 'TINAKSITE', sciName: '(Titanium Sodium Potasium Silicate Hydroxide)', imgUrl:''},
        {name: 'TINCALCONITE', sciName: '(Hydrated Sodium Borate)', imgUrl:''},
        {name: 'TITANIUM', sciName: '(Ti)', imgUrl:''},
        {name: 'TITANITE', sciName: '(alternate name for Sphene)', imgUrl:''},
        {name: 'TOPAZ', sciName: '(Aluminum Silicate Fluoride Hydroxide)', imgUrl:''},
        {name: 'TOPAZOLITE', sciName: '(the yellow variety of Andradite Garnet)', imgUrl:''},
        {name: 'TORBERNITE', sciName: '(Hydrated Copper Uranyl Phosphate)', imgUrl:''},
        {name: 'TOURMALINE', sciName: '(Group)', imgUrl:''},
        {name: 'TREMOLITE', sciName: '(Calcium Magnesium Iron Silicate Hydroxide)', imgUrl:''},
        {name: 'TRIDYMITE', sciName: '(Silicon Dioxide)', imgUrl:''},
        {name: 'TRIPHYLITE', sciName: '(Lithium Iron Manganese Phosphate)', imgUrl:''},
        {name: 'TRONA', sciName: '(Hydrated Sodium Bicarbonate Carbonate)', imgUrl:''},
        {name: 'TSAVORITE', sciName: '(variety of Grossular garnet)', imgUrl:''},
        {name: 'TSUMCORITE', sciName: '(Hydrated Lead Zinc Iron Arsenate)', imgUrl:''},
        {name: 'TSUMEBITE', sciName: '(Lead Copper Phosphate Sulfate)', imgUrl:''},
        {name: 'TURQUOISE', sciName: '(Hydrated Copper Aluminum Phosphate)', imgUrl:''},
        {name: 'TYUYAMUNITE', sciName: '(Hydrated Calcium Uranyl Vanadate)', imgUrl:''}
    ],
    u: [
        {name: 'ULEXITE', sciName: '(Sodium Calcium Borate Hydroxide)', imgUrl:''},
        {name: 'ULLMANNITE', sciName: '(Nickel Antimony Sulfide)', imgUrl:''},
        {name: 'URANINITE', sciName: '(Uranium Oxide)', imgUrl:''},
        {name: 'URANOCIRCITE', sciName: '(Hydrated Barium Uranyl Phosphate)', imgUrl:''},
        {name: 'URANOPHANE', sciName: '(Hydrated Calcium Uranyl Silicate)', imgUrl:''},
        {name: 'URANOPILITE', sciName: '(Hydrated Uranyl Sulfate Hydroxide)', imgUrl:''},
        {name: 'UVAROVITE', sciName: '(Calcium Chromium Silicate)', imgUrl:''},
        {name: 'UVITE', sciName: '(complex Calcium Sodium Magnesium Iron Boro-Aluminum Silicate Hydroxide)', imgUrl:''}
    ],
    v: [
        {name: 'VALENTINITE', sciName: '(Antimony Oxide)', imgUrl:''},
        {name: 'VANADINITE', sciName: '(Lead Chlorovanadinate)', imgUrl:''},
        {name: 'VARISCITE', sciName: '(Hydrated Aluminum Phosphate)', imgUrl:''},
        {name: 'VAUXITE', sciName: '(Hydrated Iron Aluminum Phosphate Hydroxide)', imgUrl:''},
        {name: 'VERMICULITE', sciName: '(Hydrated Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'VESUVIANITE', sciName: '(Calcium Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
        {name: 'VESZELYITE', sciName: '(Hydrated Copper Zinc Phosphate Hydroxide)', imgUrl:''},
        {name: 'VILLIAUMITE', sciName: '(Sodium Fluoride)', imgUrl:''},
        {name: 'VIVIANITE', sciName: '(Hydrated Iron Phosphate)', imgUrl:''},
        {name: 'VOLBORTHITE', sciName: '(Copper Vanadate Hydroxide)', imgUrl:''}
    ],
    w: [
        {name: 'WALPURGITE', sciName: '(Hydrated Bismuth Uranyl Arsenate Oxide)', imgUrl:''},
        {name: 'WARDITE', sciName: '(Hydrated Sodium Aluminum Phosphate Hydroxide)', imgUrl:''},
        {name: 'WAVELLITE', sciName: '(Hydrated Aluminum Phosphate Hydroxide)', imgUrl:''},
        {name: 'WELOGANITE', sciName: '(Hydrated Sodium Strontium Calcium Zirconium Carbonate)', imgUrl:''},
        {name: 'WERNERITE', sciName: '(properly called Scapolite, Sodium Calcium Aluminum Silicate Chloride Carbonate Sulfate)', imgUrl:''},
        {name: 'WHEWELLITE', sciName: '(Hydrated Calcium Oxalate)', imgUrl:''},
        {name: 'WHITEITE', sciName: '(Hydrated Calcium Iron Manganese Magnesium Aluminum Phosphate)', imgUrl:''},
        {name: 'WHITLOCKITE', sciName: '(Calcium Magnesium Iron Phosphate Hydroxide)', imgUrl:''},
        {name: 'WILLEMITE', sciName: '(Zinc Silicate)', imgUrl:''},
        {name: 'WITHERITE', sciName: '(Barium Carbonate)', imgUrl:''},
        {name: 'WOLFEITE', sciName: '(Iron Manganese Phosphate Hydroxide)', imgUrl:''},
        {name: 'WOLFRAMITE', sciName: '(Manganese Iron Tungstate)', imgUrl:''},
        {name: 'WOLLASTONITE', sciName: '(Calcium Silicate)', imgUrl:''},
        {name: 'WOODHOUSEITE', sciName: '(Calcium Aluminum Phosphate Sulfate Hydroxide)', imgUrl:''},
        {name: 'WULFENITE', sciName: '(Lead Molybdenate)', imgUrl:''},
        {name: 'WURTZITE', sciName: '(Zinc Iron Sulfide)', imgUrl:''}
    ],
    x: [
        {name: 'XENOTIME', sciName: '(Yttrium Phosphate)', imgUrl:''},
        {name: 'XONOTLITE', sciName: '(Calcium Silicate Hydroxide)', imgUrl:''}
    ],
    y: [
        {name: 'YUKSPORITE', sciName: '(Hydrated Potassium Barium Sodium Calcium Titanium Silicate Fluoride Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/30/18/05624630014947867066628.jpg'}
    ],
    z: [
        {name: 'ZEUNERITE', sciName: '(Hydrated Copper Uranyl Arsenate)', imgUrl:'https://www.mindat.org/imagecache/d8/8f/01579090014969121775340.jpg'},
        {name: 'ZINCITE', sciName: '(Zinc Manganese Oxide)', imgUrl:'https://www.mindat.org/imagecache/00/31/09497900014946345996832.jpg'},
        {name: 'ZINKENITE', sciName: '(Lead Antimony Sulfide)', imgUrl:'https://www.mindat.org/imagecache/fe/94/07226340014961061974095.jpg'},
        {name: 'ZINNWALDITE', sciName: '(Potassium Lithium Iron Aluminum Silicate Hydroxide Fluoride)', imgUrl:'https://www.mindat.org/imagecache/0d/c4/00079780014946328186714.jpg'},
        {name: 'ZIPPEITE', sciName: '(Hydrated Potassium Uranyl Sulfate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/b4/44/08486610014946994928355.jpg'},
        {name: 'ZIRCON', sciName: '(Zirconium Silicate)', imgUrl:'https://www.mindat.org/imagecache/a5/ec/05243950014946267153159.jpg'},
        {name: 'ZOISITE', sciName: '(Calcium Aluminum Silicate Hydroxide)', imgUrl:'https://www.mindat.org/imagecache/ce/e7/04096150014946273104080.jpg'}
    ]
};
