import { Injectable } from '@angular/core';

@Injectable()
export class RockService {

    constructor(){ }

    minerals = {
        a: [
            {name: 'ACANTHITE', sciName: '(Silver Sulfide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Acanthite_-_Chispas_Mine%2C_Arizpe%2C_Sonora%2C_Mexico.jpg/217px-Acanthite_-_Chispas_Mine%2C_Arizpe%2C_Sonora%2C_Mexico.jpg'},
            {name: 'ACTINOLITE', sciName: '(Calcium Magnesium Iron Silicate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Actinolite_Portugal.jpg/260px-Actinolite_Portugal.jpg'},
            {name: 'ADAMITE', sciName: '(Zinc Arsenate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Adamite-179841.jpg/240px-Adamite-179841.jpg'},
            {name: 'AEGIRINE', sciName: '(Sodium Iron Silicate)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Aegirine-Feldspar-Group-233473.jpg/260px-Aegirine-Feldspar-Group-233473.jpg'},
            {name: 'AESCHYNITE', sciName: '(Yttrium Calcium Iron Thorium Titanium Niobium Oxide Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Aeschynite-%28Y%29-180743.jpg/240px-Aeschynite-%28Y%29-180743.jpg'},
            {name: 'AGATE', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Agate_banded_750pix.jpg/260px-Agate_banded_750pix.jpg'},
            {name: 'AJOITE', sciName: '(Hydrated Potassium Sodium Copper Aluminum Silicate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Ajoite-Quartz-tmu47f.jpg/260px-Ajoite-Quartz-tmu47f.jpg'},
            {name: 'ALBITE', sciName: '(Sodium Aluminum Silicate)', imgUrl: 'http://www.minerals.net/thumbnail.aspx?image=MineralImages/albite1.jpg&size=500'},
            {name: 'ALEXANDRITE', sciName: '(variety of Chrysoberyl- Beryllium Aluminum Oxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Alexandrite_26.75cts.jpg/220px-Alexandrite_26.75cts.jpg'},
            {name: 'ALLANITE', sciName: '(Calcium Cerium Lanthanum Yttrium Aluminum Iron Silicate Hydroxide)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Allanite-%28Ce%29_-_Mary_Kathleen_Mine%2C_Mount_Isa%2C_Queensland%2C_Australia.jpg/240px-Allanite-%28Ce%29_-_Mary_Kathleen_Mine%2C_Mount_Isa%2C_Queensland%2C_Australia.jpg'},
            {name: 'ALMANDINE', sciName: '(Iron Aluminum Silicate)', imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Almandin.jpg/300px-Almandin.jpg'},
            {name: 'ALTAITE', sciName: '(Lead Telluride)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Altaite-170094.jpg/240px-Altaite-170094.jpg'},
            {name: 'ALUNITE', sciName: '(Potassium Aluminum Sulfate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Alunite_-_USGS_Mineral_Specimens_015.jpg/240px-Alunite_-_USGS_Mineral_Specimens_015.jpg'},
            {name: 'AMBER', sciName: '(Succinite: fossilized tree resin)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Amber2.jpg/220px-Amber2.jpg'},
            {name: 'AMBLYGONITE', sciName: '(Lithium Sodium Aluminum Phosphate Fluoride Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Mineral_Ambligonita_GDFL032.jpg/260px-Mineral_Ambligonita_GDFL032.jpg'},
            {name: 'AMETHYST', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Amethyst._Magaliesburg%2C_South_Africa.jpg/260px-Amethyst._Magaliesburg%2C_South_Africa.jpg'},
            {name: 'ANALCIME', sciName: '(Hydrated Sodium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Analcime%2C_Aegirine%2C_Natrolite-225835.jpg/260px-Analcime%2C_Aegirine%2C_Natrolite-225835.jpg'},
            {name: 'ANAPAITE', sciName: '(Hydrated Calcium Iron Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Anapaite-215130.jpg/240px-Anapaite-215130.jpg'},
            {name: 'ANATASE', sciName: '(Titanium Oxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Anatase_Oisans.jpg/260px-Anatase_Oisans.jpg'},
            {name: 'ANDALUSITE', sciName: '(Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/AndalousiteTyrol.jpg/260px-AndalousiteTyrol.jpg'},
            {name: 'ANDERSONITE', sciName: '(Hydrated Sodium Calcium Uranyl Carbonate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Andersonite-37032.jpg/260px-Andersonite-37032.jpg'},
            {name: 'ANDESINE', sciName: '(Sodium Calcium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Andesine-251551.jpg/260px-Andesine-251551.jpg'},
            {name: 'ANDRADITE', sciName: '(Calcium Iron Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Andradite-Mali.jpg/260px-Andradite-Mali.jpg'},
            {name: 'ANGELITE', sciName: '(trade name for Anhydrite)', imgUrl:'https://moonrisecrystals.com/wp-content/uploads/2014/07/angelite-raw-1-300x300.jpg'},
            {name: 'ANGLESITE', sciName: '(Lead Sulfate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Angl%C3%A9site%2C_gal%C3%A8ne%2C_soufre_300-4-5394.JPG/260px-Angl%C3%A9site%2C_gal%C3%A8ne%2C_soufre_300-4-5394.JPG'},
            {name: 'ANHYDRITE', sciName: '(Calcium Sulfate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Anhydrite_HMNH1.jpg/260px-Anhydrite_HMNH1.jpg'},
            {name: 'ANKERITE', sciName: '(Calcium Iron Carbonate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Ank%C3%A9rite_%28Grandfontaine%29-Mus%C3%A9e_de_min%C3%A9ralogie_de_Strasbourg.jpg/260px-Ank%C3%A9rite_%28Grandfontaine%29-Mus%C3%A9e_de_min%C3%A9ralogie_de_Strasbourg.jpg'},
            {name: 'ANNABERGITE', sciName: '(Hydrated Nickel Arsenate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Annabergite-Siderite-_Grece-1.jpg/220px-Annabergite-Siderite-_Grece-1.jpg'},
            {name: 'ANORTHITE', sciName: '(Calcium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Anorthite-rare08-38b.jpg/240px-Anorthite-rare08-38b.jpg'},
            {name: 'ANTHOPHYLLITE', sciName: '(Magnesium Iron Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Anthophyllite_Su%C3%A8de_Fond.jpg/260px-Anthophyllite_Su%C3%A8de_Fond.jpg'},
            {name: 'ANTLERITE', sciName: '(Copper Sulfate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Antlerite-40298.jpg/240px-Antlerite-40298.jpg'},
            {name: 'APATITE', sciName: '(Calcium Fluoro, Chloro, Hydroxyl Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Apatite_Canada.jpg/240px-Apatite_Canada.jpg'},
            {name: 'APOPHYLLITE', sciName: '(Hydrated Potassium Calcium Silicate Hydroxide Flouride)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Apophyllite-65547.jpg/260px-Apophyllite-65547.jpg'},
            {name: 'AQUAMARINE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Beryl-209736.jpg/220px-Beryl-209736.jpg'},
            {name: 'ARAGONITE', sciName: '(Calcium Carbonate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Aragonite_Salsigne_France.jpg/260px-Aragonite_Salsigne_France.jpg'},
            {name: 'ARFVEDSONITE', sciName: '(Sodium Iron Magnesium Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Arfvedsonite-20218.jpg/220px-Arfvedsonite-20218.jpg'},
            {name: 'ARGENTITE', sciName: '(Silver Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Argentite.jpg/220px-Argentite.jpg'},
            {name: 'ARGYRODITE', sciName: '(Silver Germanium Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Argyrodite-170093.jpg/240px-Argyrodite-170093.jpg'},
            {name: 'ARSENOPYRITE', sciName: '(Iron Arsenide Sulfide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Arsenopyrite-117874.jpg/260px-Arsenopyrite-117874.jpg'},
            {name: 'ARSENTSUMEBITE', sciName: '(Lead Copper Arsenate Sulfate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Naturkundemuseum_Berlin_-_Arsentsumebit_-_Tsumeb%2C_Namibia.jpg/250px-Naturkundemuseum_Berlin_-_Arsentsumebit_-_Tsumeb%2C_Namibia.jpg'},
            {name: 'ARTHURITE', sciName: '(Hydrated Copper Iron Arsenate Phosphate Sulfate)', imgUrl:'https://www.mindat.org/imagecache/8b/9d/01498820014948431533596.jpg'},
            {name: 'ARTINITE', sciName: '(Hydrated Magnesium Carbonate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Artinite-206168.jpg/260px-Artinite-206168.jpg'},
            {name: 'ASTROPHYLLITE', sciName: '(Potassium Iron Titanium Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Astrophyllite-168179.jpg/240px-Astrophyllite-168179.jpg'},
            {name: 'ATACAMITE', sciName: '(Copper Chloride Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Atacamite-235102.jpg/260px-Atacamite-235102.jpg'},
            {name: 'AUGELITE', sciName: '(Aluminum Phosphate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Augelite-78938.jpg/260px-Augelite-78938.jpg'},
            {name: 'AUGITE', sciName: '(Calcium Sodium Magnesium Aluminum Iron Titanium Silicate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Augite_Rwanda.jpg/260px-Augite_Rwanda.jpg'},
            {name: 'AURICHALCITE', sciName: '(Zinc Copper Carbonate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Aurichalcite-Calcite-aur08b.jpg/260px-Aurichalcite-Calcite-aur08b.jpg'},
            {name: 'AUSTINITE', sciName: '(Calcium Zinc Arsenate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Austinite-177832.jpg/260px-Austinite-177832.jpg'},
            {name: 'AUTUNITE', sciName: '(Hydrated Calcium Uranyl Phosphate)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Autunite-69257.jpg/240px-Autunite-69257.jpg'},
            {name: 'AXINITE', sciName: '(Calcium Iron Magnesium Manganese Aluminum Boro-Silicate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Axinite-Oisan.jpg/240px-Axinite-Oisan.jpg'},
            {name: 'AZURITE', sciName: '(Copper Carbonate Hydroxide)', imgUrl:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Azurit.jpg/260px-Azurit.jpg'}
        ],
        b: [
            {name: 'BABINGTONITE', sciName: '(Calcium Iron Manganese Silicate Hydroxide)', imgUrl:''},
            {name: 'BAKERITE', sciName: '(Hydrated Calcium Boro-silicate Hydroxide)', imgUrl:''},
            {name: 'BARATOVITE', sciName: '(Potassium Lithium Calcium Titanium Zirconium Silicate Fluoride)', imgUrl:''},
            {name: 'BARITE', sciName: '(Barium Sulfate)', imgUrl:''},
            {name: 'BASTNASITE', sciName: '(Cerium Lanthanum Yttrium Carbonate Fluoride)', imgUrl:''},
            {name: 'BAUMHAUERITE', sciName: '(Lead Arsenic Sulfide)', imgUrl:''},
            {name: 'BAYLDONITE', sciName: '(Hydrated Copper Lead Arsenate Hydroxide)', imgUrl:''},
            {name: 'BECQUERELITE', sciName: '(Hydrated Calcium Uranyl Oxide Hydroxide)', imgUrl:''},
            {name: 'BENITOITE', sciName: '(Barium Titanium Silicate)', imgUrl:''},
            {name: 'BERAUNITE', sciName: '(Hydrated Iron Phosphate Hydroxide)', imgUrl:''},
            {name: 'BERLINITE', sciName: '(Aluminum Phosphate)', imgUrl:''},
            {name: 'BERTHIERITE', sciName: '(Iron Antimony Sulfide)', imgUrl:''},
            {name: 'BERTRANDITE', sciName: '(Beryllium Silicate Hydroxide)', imgUrl:''},
            {name: 'BERYL', sciName: '(Berylium Aluminum Silicate)', imgUrl:''},
            {name: 'BERYLLONITE', sciName: '(Sodium Beryllium Phosphate)', imgUrl:''},
            {name: 'BETAFITE', sciName: '(Calcium Sodium Uranium Titanium Niobium Tantalum Oxide Hydroxide Fluoride)', imgUrl:''},
            {name: 'BEUDANTITE', sciName: '(Lead Iron Arsenate Sulfate Hydroxide)', imgUrl:''},
            {name: 'BIDEAUXITE', sciName: '(Lead Silver Chloride Fluoride Hydroxide)', imgUrl:''},
            {name: 'BIF', sciName: '(Banded Iron Formation aka Taconite)', imgUrl:''},
            {name: 'BINDHEIMITE', sciName: '(Lead Antimony Oxide)', imgUrl:''},
            {name: 'BIOTITE', sciName: '(Potassium Iron Magnesium Aluminum Silicate Hydroxide Fluoride)', imgUrl:''},
            {name: 'BISMUTHINITE', sciName: '(Bismuth Sulfide)', imgUrl:''},
            {name: 'BIXBYITE', sciName: '(Manganese Iron Oxide)', imgUrl:''},
            {name: 'BLODITE', sciName: '(Hydrated Sodium Magnesium Sulfate)', imgUrl:''},
            {name: 'BLOODSTONE', sciName: '(variety of Chalcedony)', imgUrl:''},
            {name: 'BOLEITE', sciName: '(Hydrated Lead Copper Silver Chloride Hydroxide)', imgUrl:''},
            {name: 'BOLTWOODITE', sciName: '(Hydrated Potassium Uranyl Silicate Hydroxide)', imgUrl:''},
            {name: 'BORACITE', sciName: '(Magnesium Borate Chloride)', imgUrl:''},
            {name: 'BORAX', sciName: '(Hydrated Sodium Borate)', imgUrl:''},
            {name: 'BORNITE', sciName: '(Copper Iron Sulfide)', imgUrl:''},
            {name: 'BOULANGERITE', sciName: '(Lead Antimony Sulfide)', imgUrl:''},
            {name: 'BOURNONITE', sciName: '(Copper Lead Antimony Sulfide)', imgUrl:''},
            {name: 'BRANNERITE', sciName: '(Uranium Calcium Titanium Iron Oxide)', imgUrl:''},
            {name: 'BRASS', sciName: '(Copper Zinc Alloy)', imgUrl:''},
            {name: 'BRAZILIANITE', sciName: '(Sodium Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'BROCHANTITE', sciName: '(Copper Sulfate Hydroxide)', imgUrl:''},
            {name: 'BROOKITE', sciName: '(Titanium Oxide)', imgUrl:''},
            {name: 'BRUCITE', sciName: '(Magnesium Hydroxide)', imgUrl:''},
            {name: 'BUERGERITE', sciName: '(Sodium Iron Aluminum Boro-silicate Oxide Fluoride)', imgUrl:''},
            {name: 'BURBANKITE', sciName: '(Sodium Calcium Strontium Barium Cerium Carbonate)', imgUrl:''},
            {name: 'BUTTGENBACHITE', sciName: '(Hydrated Copper Nitrate Chloride Hydroxide)', imgUrl:''},
            {name: 'BYTOWNITE', sciName: '(Calcium Sodium Aluminum Silicate)', imgUrl:''}
        ],
        c: [
            {name: 'CACOXENITE', sciName: '(Hydrated Iron Aluminum Phosphate Oxide Hydroxide)', imgUrl:''},
            {name: 'CALAVERITE', sciName: '(Gold Telluride)', imgUrl:''},
            {name: 'CALCIOVOLBORTHITE', sciName: '(Calcium Copper Vanadate Hydroxide)', imgUrl:''},
            {name: 'CALCITE', sciName: '(Calcium Carbonate)', imgUrl:''},
            {name: 'CALEDONITE', sciName: '(Copper Lead Carbonate Sulfate Hydroxide)', imgUrl:''},
            {name: 'CALOMEL', sciName: '(Mercury Chloride)', imgUrl:''},
            {name: 'CANCRINITE', sciName: '(Sodium Calcium Aluminum Silicate Carbonate)', imgUrl:''},
            {name: 'CARBOCERNAITE', sciName: '(Calcium Sodium Strontium Cerium Barium Carbonate)', imgUrl:''},
            {name: 'CARLETONITE', sciName: '(Hydrated Potassium Sodium Calcium Carbonate Silicate Fluoride Hydroxide)', imgUrl:''},
            {name: 'CARNALLITE', sciName: '(Hydrated Potasium Magnesium Chloride)', imgUrl:''},
            {name: 'CARNELIAN', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'CARNOTITE', sciName: '(Hydrated Potassium Uranyl Vanadate)', imgUrl:''},
            {name: 'CASSITERITE', sciName: '(Tin Oxide)', imgUrl:''},
            {name: 'CATAPLEIITE', sciName: '(Hydrated Sodium Zirconium Silicate)', imgUrl:''},
            {name: 'CAVANSITE', sciName: '(Hydrated Calcium Vanadium Silicate)', imgUrl:''},
            {name: 'CELESTITE', sciName: '(Strontium Sulfate)', imgUrl:''},
            {name: 'CERUSSITE', sciName: '(Lead Carbonate)', imgUrl:''},
            {name: 'CHABAZITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'CHALCANTHITE', sciName: '(Hydrated Copper Sulfate)', imgUrl:''},
            {name: 'CHALCEDONY', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'CHALCOCITE', sciName: '(Copper Sulfide)', imgUrl:''},
            {name: 'CHALCOPHYLLITE', sciName: '(Hydrated Copper Aluminum Sulphate Arsenate Hydroxide)', imgUrl:''},
            {name: 'CHALCOPYRITE', sciName: '(Copper Iron Sulfide)', imgUrl:''},
            {name: 'CHALCOSIDERITE', sciName: '(Hydrated Copper Iron Phosphate Hydroxide)', imgUrl:''},
            {name: 'CHALCOTRICHITE', sciName: '(variety of Cuprite, Copper Oxide)', imgUrl:''},
            {name: 'CHAROITE', sciName: '(Hydrated Sodium Calcium Barium Strontium Silicate Hydroxide Fluoride)', imgUrl:''},
            {name: 'CHENGDEITE', sciName: '(Iridium Iron)', imgUrl:''},
            {name: 'CHILDRENITE', sciName: '(Hydrated Iron Manganese Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'CHKALOVITE', sciName: '(Sodium Beryllium Silicate)', imgUrl:''},
            {name: 'CHLORAPATITE', sciName: '(the chlorine rich apatite)', imgUrl:''},
            {name: 'CHLORARGYRITE', sciName: '(Silver Chloride)', imgUrl:''},
            {name: 'CHLORITE', sciName: '(Iron Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'CHONDRODITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)', imgUrl:''},
            {name: 'CHROMITE', sciName: '(Magnesium Iron Chromium Oxide)', imgUrl:''},
            {name: 'CHROMIUM', sciName: '(Cr)', imgUrl:''},
            {name: 'CHRYSOBERYL', sciName: '(Berylium Aluminum Oxide)', imgUrl:''},
            {name: 'CHRYSOCOLLA', sciName: '(Hydrated Copper Silicate)', imgUrl:''},
            {name: 'CHRYSOPRASE', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'CHRYSOTILE', sciName: '(variety of Serpentine, Magnesium Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'CHURCHITE', sciName: '(Hydrated Yttrium Erbium Phosphate)', imgUrl:''},
            {name: 'CINNABAR', sciName: '(Mercury Sulfide)', imgUrl:''},
            {name: 'CITRINE', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:''},
            {name: 'CLAUSTHALITE', sciName: '(Lead Selenide)', imgUrl:''},
            {name: 'CLEAVELANDITE', sciName: '(variety of Albite, Sodium Aluminum Silicate)', imgUrl:''},
            {name: 'CLIFFORDITE', sciName: '(Uranium Tellurate)', imgUrl:''},
            {name: 'CLINOCHLORE', sciName: '(Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'CLINOCLASE', sciName: '(Copper Arsenate Hydroxide)', imgUrl:''},
            {name: 'CLINOHEDRITE', sciName: '(Hydrated Calcium Zinc Silicate)', imgUrl:''},
            {name: 'CLINOHUMITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)', imgUrl:''},
            {name: 'CLINOPTILOLITE', sciName: '(Hydrated Sodium Potassium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'COBALTITE', sciName: '(Cobalt Arsenic Sulfide)', imgUrl:''},
            {name: 'COBALTOCALCITE', sciName: '(alternate name for Sphaerocobaltite)', imgUrl:''},
            {name: 'COCONINOITE', sciName: '(Hydrated Iron Aluminum Uranyl Phosphate Sulfate Hydroxide)', imgUrl:''},
            {name: 'COESITE', sciName: '(Silicon Dioxide)', imgUrl:''},
            {name: 'COLEMANITE', sciName: '(Hydrated Calcium Borate Hydroxide)', imgUrl:''},
            {name: 'COLLINSITE', sciName: '(Hydrated Calcium Magnesium Iron Phosphate)', imgUrl:''},
            {name: 'COLUMBITE', sciName: '(Iron Magnesium Manganese Niobium Tantalum Oxide)', imgUrl:''},
            {name: 'CONICHALCITE', sciName: '(Calcium Copper Arsenate Hydroxide)', imgUrl:''},
            {name: 'CONNELLITE', sciName: '(Hydrated Copper Sulfate Chloride Hydroxide)', imgUrl:''},
            {name: 'COPIAPITE', sciName: '(Hydrated Iron Magnesium Sulfate Hydroxide)', imgUrl:''},
            {name: 'CORDIERITE', sciName: '(Magnesium Aluminum Silicate)', imgUrl:''},
            {name: 'CORDYLITE', sciName: '(Barium Cerium Lanthanum Carbonate Fluoride)', imgUrl:''},
            {name: 'CORNETITE', sciName: '(Copper Phosphate Hydroxide)', imgUrl:''},
            {name: 'CORNWALLITE', sciName: '(Copper Arsenate Hydroxide)', imgUrl:''},
            {name: 'CORUNDUM', sciName: '(Aluminum Oxide)', imgUrl:''},
            {name: 'COVELLITE', sciName: '(Copper Sulfide)', imgUrl:''},
            {name: 'CREEDITE', sciName: '(Hydrated Calcium Aluminum Sulfate Fluoride Hydroxide)', imgUrl:''},
            {name: 'CRISTOBALITE', sciName: '(Silicon Dioxide)', imgUrl:''},
            {name: 'CROCOITE', sciName: '(Lead Chromate)', imgUrl:''},
            {name: 'CROCIDOLITE', sciName: '(asbestiform variety of Riebeckite, Sodium Iron Magnesium Silicate Hydroxide)', imgUrl:''},
            {name: 'CRYOLITE', sciName: '(Sodium Aluminum Fluoride)', imgUrl:''},
            {name: 'CUBANITE', sciName: '(Copper Iron Sulfide)', imgUrl:''},
            {name: 'CUMENGITE', sciName: '(Lead Copper Chloride Hydroxide)', imgUrl:''},
            {name: 'CUMMINGTONITE', sciName: '(Magnesium Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'CUPRITE', sciName: '(Copper Oxide)', imgUrl:''},
            {name: 'CUPROADAMITE', sciName: '(Copper Zinc Arsenate Hydroxide)', imgUrl:''},
            {name: 'CUPROSKLODOWSKITE', sciName: '(Hydrated Copper Uranyl Silicate)', imgUrl:''},
            {name: 'CYANOTRICHITE', sciName: '(Hydrated Copper Aluminum Sulfate Hydroxide)', imgUrl:''},
            {name: 'CYLINDRITE', sciName: '(Iron Lead Tin Antimony Sulfide)', imgUrl:''}
        ],
        d: [
            {name: 'DANBURITE', sciName: '(Calcium Boro-Silicate)', imgUrl:''},
            {name: 'DATOLITE', sciName: '(Calcium Boro-Silicate Hydroxide)', imgUrl:''},
            {name: 'DESCLOIZITE', sciName: '(Lead Zinc Vanadate Hydroxide)', imgUrl:''},
            {name: 'DEMANTOID', sciName: '(variety of Andradite garnet)', imgUrl:''},
            {name: 'DEPOSITS', sciName: '(unconsolidated sediments)', imgUrl:''},
            {name: 'DIABOLEITE', sciName: '(Lead Copper Chloride Hydroxide)', imgUrl:''},
            {name: 'DIAMOND', sciName: '(Carbon)', imgUrl:''},
            {name: 'DIGENITE', sciName: '(Copper Sulfide)', imgUrl:''},
            {name: 'DIOPSIDE', sciName: '(Calcium Magnesium Silicate)', imgUrl:''},
            {name: 'DIOPTASE', sciName: '(Copper Silicate Hydroxide)', imgUrl:''},
            {name: 'DOLOMITE', sciName: '(Calcium Magnesium Carbonate)', imgUrl:''},
            {name: 'DOMEYKITE', sciName: '(Copper Arsenide)', imgUrl:''},
            {name: 'DRAVITE', sciName: '(complex Sodium Magnesium Iron Boro-Aluminum Silicate)', imgUrl:''},
            {name: 'DUFRENITE', sciName: '(Hydrated Iron Phosphate Hydroxide)', imgUrl:''},
            {name: 'DUFTITE', sciName: '(Lead Calcium Copper Zinc Arsenate Hydroxide)', imgUrl:''},
            {name: 'DUMORTIERITE', sciName: '(Aluminum Borate Silicate Oxide)', imgUrl:''},
            {name: 'DUNDASITE', sciName: '(Hydrated Lead Aluminum Carbonate Hydroxide)', imgUrl:''},
            {name: 'DYSCRASITE', sciName: '(Silver Antimonide)', imgUrl:''}
        ],
        e: [
            {name: 'EDENITE', sciName: '(Sodium Calcium Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'EDINGTONITE', sciName: '(Hydrated Barium Aluminum Silicate)', imgUrl:''},
            {name: 'ELBAITE', sciName: '(Sodium Lithium Aluminum Boro-Silicate Hydroxide)', imgUrl:''},
            {name: 'ELPIDITE', sciName: '(Hydrated Sodium Zirconium Silicate)', imgUrl:''},
            {name: 'EMERALD', sciName: '(variety of Beryl- Berylium Aluminum Silicate)', imgUrl:''},
            {name: 'EMMONSITE', sciName: '(Hydrated Iron Tellurite)', imgUrl:''},
            {name: 'EMPLECTITE', sciName: '(Copper Bismuth Sulfide)', imgUrl:''},
            {name: 'ENARGITE', sciName: '(Copper Arsenic Sulfide)', imgUrl:''},
            {name: 'ENSTATITE', sciName: '(Magnesium Silicate)', imgUrl:''},
            {name: 'EOSPHORITE', sciName: '(Hydrated Manganese Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'EPIDIDYMITE', sciName: '(Sodium Beryllium Silicate Hydroxide)', imgUrl:''},
            {name: 'EPIDOTE', sciName: '(Calcium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'EPISTILBITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'EPSOMITE', sciName: '(Hydrated Magnesium Sulfate)', imgUrl:''},
            {name: 'ERIONITE', sciName: '(Hydrated Potassium Sodium Calcium Magnesium Aluminum Silicate)', imgUrl:''},
            {name: 'ERYTHRITE', sciName: '(Hydrated Cobalt Arsenate)', imgUrl:''},
            {name: 'ESPERITE', sciName: '(Calcium Lead Zinc Silicate)', imgUrl:''},
            {name: 'ETTRINGITE', sciName: '(Hydrated Calcium Aluminum Sulfate Hydroxide)', imgUrl:''},
            {name: 'EUCLASE', sciName: '(Beryllium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'EUCRYPTITE', sciName: '(Lithium Aluminum Silicate)', imgUrl:''},
            {name: 'EUDIALYTE', sciName: '(Sodium Calcium Cerium Iron Manganese Zirconium Silicate Hydroxide Chloride)', imgUrl:''},
            {name: 'EUDIDYMITE', sciName: '(Sodium Beryllium Silicate Hydroxide)', imgUrl:''},
            {name: 'EUXENITE', sciName: '(Yttrium Calcium Erbium Lanthanum Cerium Uranium Thorium Niobium Tantalum Titanium Oxide)', imgUrl:''}
        ],
        f: [
            {name: 'FAYALITE', sciName: '(Magnesium Iron Silicate)', imgUrl:''},
            {name: 'FEDORITE', sciName: '(Hydrated Sodium Potassium Calcium Silicate Fluoride Chloride Hydroxide)', imgUrl:''},
            {name: 'FERBERITE', sciName: '(Iron Tungstate)', imgUrl:''},
            {name: 'FERRO-EDENITE ', sciName:'(Sodium Calcium Iron Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'FERROGLAUCOPHANE', sciName: '(Sodium Iron Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'FIEDLERITE', sciName: '(Lead Chloride Fluoride Hydroxide)', imgUrl:''},
            {name: 'FLINT', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'FLUORAPATITE', sciName: '(the fluorine rich apatite)', imgUrl:''},
            {name: 'FLUORITE', sciName: '(Calcium Fluoride)', imgUrl:''},
            {name: 'FLUORRICHTERITE', sciName: '(Sodium Calcium Magnesium Iron Silicate Hydroxide Fluoride)', imgUrl:''},
            {name: 'FORSTERITE', sciName: '(Iron Magnesium Silicate)', imgUrl:''},
            {name: 'FRANCKEITE', sciName: '(Lead Tin Iron Antimony Sulfide)', imgUrl:''},
            {name: 'FRANKLINITE', sciName: '(Zinc Manganese Iron Oxide)', imgUrl:''},
            {name: 'FUCHSITE', sciName: '(the chromium-rich muscovite)', imgUrl:''},
            {name: 'FULGARITE', sciName: '(lightning created Lechatelierite, Silicon Dioxide)', imgUrl:''}
        ],
        g: [
            {name: 'GADOLINITE', sciName: '(Yttrium Iron Beryllium Silicate)', imgUrl:''},
            {name: 'GAHNITE', sciName: '(Zinc Aluminum Oxide)', imgUrl:''},
            {name: 'GALENA', sciName: '(Lead Sulfide)', imgUrl:''},
            {name: 'GARNET', sciName: '(Group)', imgUrl:''},
            {name: 'GASPEITE', sciName: '(Nickel Magnesium Iron Carbonate)', imgUrl:''},
            {name: 'GAYLUSSITE', sciName: '(Hydrated Sodium Calcium Carbonate)', imgUrl:''},
            {name: 'GERSDORFFITE', sciName: '(Nickel Arsenide Sulfide)', imgUrl:''},
            {name: 'GIBBSITE', sciName: '(Aluminum Hydroxide)', imgUrl:''},
            {name: 'GLAUBERITE', sciName: '(Sodium Calcium Sulfate)', imgUrl:''},
            {name: 'GLAUCOPHANE', sciName: '(Sodium Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'GMELINITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'GOETHITE', sciName: '(Hydrated Iron Oxide)', imgUrl:''},
            {name: 'GOLD', sciName: '(Au)', imgUrl:''},
            {name: 'GOOSECREEKITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'GORMANITE', sciName: '(Hydrated Iron Magnesium Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'GOSHENITE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:''},
            {name: 'GRAEMITE', sciName: '(Hydrated Copper Tellurate)', imgUrl:''},
            {name: 'GRATONITE', sciName: '(Lead Arsenic Sulfide)', imgUrl:''},
            {name: 'GREENOCKITE', sciName: '(Cadmium Sulfide)', imgUrl:''},
            {name: 'GROSSULAR', sciName: '(Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'GYPSUM', sciName: '(Hydrated Calcium Sulfate)', imgUrl:''},
            {name: 'GYROLITE', sciName: '(Hydrated Calcium Silicate Hydroxide)', imgUrl:''}
        ],
        h: [
            {name: 'HACKMANITE', sciName: '(variety of Sodalite, Sodium Aluminum Silicate Chloride)', imgUrl:''},
            {name: 'HALITE', sciName: '(Sodium Chloride)', imgUrl:''},
            {name: 'HANKSITE', sciName: '(Potassium Sodium Sulfate Carbonate Chloride)', imgUrl:''},
            {name: 'HARDYSTONITE', sciName: '(Calcium Zinc Silicate)', imgUrl:''},
            {name: 'HARMOTOME', sciName: '(Hydrated Barium Potasium Aluminum Silicate)', imgUrl:''},
            {name: 'HAUSMANNITE', sciName: '(Manganese Oxide)', imgUrl:''},
            {name: 'HEDENBERGITE', sciName: '(Calcium Iron Silicate)', imgUrl:''},
            {name: 'HEDYPHANE', sciName: '(Lead Calcium Arsenate Chloride)', imgUrl:''},
            {name: 'HELIODOR', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:''},
            {name: 'HEMATITE', sciName: '(Iron Oxide)', imgUrl:''},
            {name: 'HEMIMORPHITE', sciName: '(Hydrated Zinc Silicate Hydroxide)', imgUrl:''},
            {name: 'HERDERITE', sciName: '(Calcium Beryllium Phosphate Fluoride Hydroxide)', imgUrl:''},
            {name: 'HESSITE', sciName: '(Silver Telluride)', imgUrl:''},
            {name: 'HESSONITE', sciName: '(variety of Grossular garnet)', imgUrl:''},
            {name: 'HEULANDITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'HIDDENITE', sciName: '(variety of Spodumene)', imgUrl:''},
            {name: 'HILAIRITE', sciName: '(Hydrated Sodium Zirconium Silicate)', imgUrl:''},
            {name: 'HINSDALITE', sciName: '(Lead Strontium Aluminum Phosphate Sulfate Hydroxide)', imgUrl:''},
            {name: 'HODGKINSONITE', sciName: '(Manganese Zinc Silicate Hydroxide)', imgUrl:''},
            {name: 'HOPEITE', sciName: '(Hydrated Zinc Phosphate)', imgUrl:''},
            {name: 'HORNBLEND', sciName: '(Calcium Sodium Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'HOWLITE', sciName: '(Calcium Boro-Silicate Hydroxide)', imgUrl:''},
            {name: 'HUEBNERITE', sciName: '(Manganese Tungstate)', imgUrl:''},
            {name: 'HUMITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)', imgUrl:''},
            {name: 'HUREAULITE', sciName: '(Hydrated Manganese Phosphate Hydroxide)', imgUrl:''},
            {name: 'HYDROBORACITE', sciName: '(Hydrated Calcium Magnesium Borate)', imgUrl:''},
            {name: 'HYDROMAGNESITE', sciName: '(Hydrated Magnesium Carbonate Hydroxide)', imgUrl:''},
            {name: 'HYDROXYLBASTNASITE', sciName: '(Cerium Lanthanum Neodymium Carbonate Hydroxide Fluoride)', imgUrl:''},
            {name: 'HYDROZINCITE', sciName: '(Hydrated Zinc Carbonate)', imgUrl:''},
            {name: 'HYPERSTHENE', sciName: '(Magnesium Iron Silicate)', imgUrl:''}
        ],
        i: [
            {name: 'ICE', sciName: '(Hydrogen Oxide)', imgUrl:''},
            {name: 'IDOCRASE', sciName: '(alternate name of Vesuvianite)', imgUrl:''},
            {name: 'ILVAITE', sciName: '(Calcium Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'ILMENITE', sciName: '(Iron Titanium Oxide)', imgUrl:''},
            {name: 'INDICOLITE', sciName: '(blue variety of Elbaite tourmaline)', imgUrl:''},
            {name: 'INESITE', sciName: '(Hydrated Calcium Manganese Silicate Hydroxide)', imgUrl:''},
            {name: 'IOLITE', sciName: '(variety of Cordierite)', imgUrl:''}
        ],
        j: [
            {name: 'JADE', sciName: '(gem variety of both Jadeite and Nephrite (variety of Actinolite))', imgUrl:''},
            {name: 'JADEITE', sciName: '(Sodium Iron Aluminum Silicate)', imgUrl:''},
            {name: 'JAMESONITE', sciName: '(Lead Iron Antimony Sulfide)', imgUrl:''},
            {name: 'JAROSITE', sciName: '(Potassium Iron Sulfate Hydroxide)', imgUrl:''},
            {name: 'JASPER', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'JOAQUINITE', sciName: '(Barium Sodium Cesium Titanium Niobium Iron Silicate Hydroxide Fluoride)', imgUrl:''},
            {name: 'JORDANITE', sciName: '(Lead Arsenic Antimony Sulfide)', imgUrl:''}
        ],
        k: [
            {name: 'KAEMMERERITE', sciName: '(the chromium rich variety of cliniclore)', imgUrl:''},
            {name: 'KAOLINITE', sciName: '(Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'KERMESITE', sciName: '(Antimony Oxysulfide)', imgUrl:''},
            {name: 'KERNITE', sciName: '(Hydrated Sodium Borate)', imgUrl:''},
            {name: 'KIDWELLITE', sciName: '(Hydrated Sodium Iron Phosphate Hydroxide)', imgUrl:''},
            {name: 'KIESERITE', sciName: '(Hydrated Magnesium Sulfate)', imgUrl:''},
            {name: 'KINOITE', sciName: '(Hydrated Calcium Copper Silicate)', imgUrl:''},
            {name: 'KNAUFITE', sciName: '(alternate name for VOLBORTHITE, Copper Vanadate Hydroxide)', imgUrl:''},
            {name: 'KOLWEZITE', sciName: '(Copper Cobalt Carbonate Hydroxide)', imgUrl:''},
            {name: 'KORNERUPINE', sciName: '(Magnesium Aluminum Iron Boro-silicate Hydroxide)', imgUrl:''},
            {name: 'KOTTIGITE', sciName: '(Hydrated Zinc Arsenate)', imgUrl:''},
            {name: 'KOVDORSKITE', sciName: '(Hydrated Magnesium Carbonate Phosphate Hydroxide)', imgUrl:''},
            {name: 'KTENASITE', sciName: '(Hydrated Copper Zinc Sulfate Hydroxide)', imgUrl:''},
            {name: 'KULANITE', sciName: '(Barium Iron Manganese Magnesium Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'KUNZITE', sciName: '(variety of Spodumene)', imgUrl:''},
            {name: 'KUPLETSKITE', sciName: '(Potassium Sodium Manganese Iron Titanium Niobium Silicate Hydroxide)', imgUrl:''},
            {name: 'KUTNOHORITE', sciName: '(Calcium Magnesium Carbonate)', imgUrl:''},
            {name: 'KYANITE', sciName: '(Aluminum Silicate)', imgUrl:''}
        ],
        l: [
            {name: 'LABRADORITE', sciName: '(Calcium Sodium Aluminum Silicate)', imgUrl:''},
            {name: 'LARDERELLITE', sciName: '(Ammonium Borate Hydroxide)', imgUrl:''},
            {name: 'LARIMAR', sciName: '(variety of Pectolite)', imgUrl:''},
            {name: 'LAUEITE', sciName: '(Hydrated Manganese Iron Phosphate Hydroxide)', imgUrl:''},
            {name: 'LAUMONTITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'LAURIONITE', sciName: '(Lead Chloride Hydroxide)', imgUrl:''},
            {name: 'LAZULITE', sciName: '(Magnesium Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'LAZURITE', sciName: '(Sodium Calcium Aluminum Silicate Sulfate)', imgUrl:''},
            {name: 'LEAD', sciName: '(Pb)', imgUrl:''},
            {name: 'LEADHILLITE', sciName: '(Lead Sulfate Carbonate Hydroxide)', imgUrl:''},
            {name: 'LECHATELIERITE', sciName: '(Silicon Dioxide)', imgUrl:''},
            {name: 'LEGRANDITE', sciName: '(Hydrated Zinc Arsenate Hydroxide)', imgUrl:''},
            {name: 'LEIFITE', sciName: '(Hydrated Sodium Beryllium Aluminum Silicate Hydroxide Fluoride)', imgUrl:''},
            {name: 'LEPIDOLITE', sciName: '(Potassium Lithium Aluminum Silicate Hydroxide Fluoride)', imgUrl:''},
            {name: 'LEUCITE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
            {name: 'LEUCOCHALCITE', sciName: '(variety of Olivenite)', imgUrl:''},
            {name: 'LEUCOPHANITE', sciName: '(Sodium Calcium Beryllium Silicate Fluoride)', imgUrl:''},
            {name: 'LIBETHENITE', sciName: '(Copper Phosphate Hydroxide)', imgUrl:''},
            {name: 'LIMONITE', sciName: '(Hydrated Iron Oxide Hydroxide)', imgUrl:''},
            {name: 'LINARITE', sciName: '(Lead Copper Sulfate hydroxide)', imgUrl:''},
            {name: 'LINNAEITE', sciName: '(Cobalt Sulfide)', imgUrl:''},
            {name: 'LIROCONITE', sciName: '(Hydrated Copper Aluminum Arsenate Hydroxide)', imgUrl:''},
            {name: 'LITHIOPHILITE', sciName: '(Lithium Manganese Iron Phosphate)', imgUrl:''},
            {name: 'LOLLINGITE', sciName: '(Iron Arsenide)', imgUrl:''},
            {name: 'LORENZENITE', sciName: '(Sodium Titanium Silicate)', imgUrl:''},
            {name: 'LARIMAR', sciName: '(variety of Pectolite)', imgUrl:''},
            {name: 'LUDLAMITE', sciName: '(Hydrated Iron Magnesium Manganese Phosphate)', imgUrl:''}
        ],
        m: [
            {name: 'MACPHERSONITE', sciName: '(Lead Sulfate Carbonate Hydroxide)', imgUrl:''},
            {name: 'MAGNESITE', sciName: '(Magnesium Carbonate)', imgUrl:''},
            {name: 'MAGNETITE', sciName: '(Iron Oxide)', imgUrl:''},
            {name: 'MALACHITE', sciName: '(Hydrated Copper Carbonate)', imgUrl:''},
            {name: 'MANGANBABINGTONITE', sciName: '(Calcium Manganese Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'MANGANESE', sciName: '(Mn)', imgUrl:''},
            {name: 'MANGANITE', sciName: '(Manganese Oxide Hydroxide)', imgUrl:''},
            {name: 'MARCASITE', sciName: '(Iron Sulfide)', imgUrl:''},
            {name: 'MASSICOT', sciName: '(Lead Oxide)', imgUrl:''},
            {name: 'MELANITE', sciName: '(the black variety of Andradite Garnet)', imgUrl:''},
            {name: 'MELANOPHLOGITE', sciName: '(Silicon Oxide with organic compounds)', imgUrl:''},
            {name: 'MELANTERITE', sciName: '(Hydrated Iron Sulfate)', imgUrl:''},
            {name: 'MENEGHINITE', sciName: '(Lead Antimony Sulfide)', imgUrl:''},
            {name: 'MESOLITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'META-ANKOLEITE', sciName: '(Hydrated Potassium Uranyl Phosphate)', imgUrl:''},
            {name: 'META-AUTUNITE', sciName: '(Hydrated Calcium Uranyl Phosphate)', imgUrl:''},
            {name: 'META-TORBERNITE', sciName: '(Hydrated Copper Uranyl Phosphate)', imgUrl:''},
            {name: 'META-URANOCIRCITE', sciName: '(Hydrated Barium Uranyl Phosphate)', imgUrl:''},
            {name: 'META-VARISCITE', sciName: '(Hydrated Aluminum Phosphate)', imgUrl:''},
            {name: 'META-ZEUNERITE', sciName: '(Hydrated Copper Uranyl Arsenate)', imgUrl:''},
            {name: 'MIARGYRITE', sciName: '(Silver Antimony Sulfide)', imgUrl:''},
            {name: 'MICROCLINE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
            {name: 'MICROLITE', sciName: '(Calcium Sodium Tantalum Oxide Hydroxide Fluoride)', imgUrl:''},
            {name: 'MILARITE', sciName: '(Hydrated Potassium Calcium Aluminum Beryllium Silicate)', imgUrl:''},
            {name: 'MILKY QUARTZ', sciName: '(variety of Quartz)', imgUrl:''},
            {name: 'MILLERITE', sciName: '(Nickel Sulfide)', imgUrl:''},
            {name: 'MIMETITE', sciName: '(Lead Chloroarsenate)', imgUrl:''},
            {name: 'MINASGERAISITE', sciName: '- (Y) (Calcium Yttrium Beryllium Silicate)', imgUrl:''},
            {name: 'MINIUM', sciName: '(Lead Oxide)', imgUrl:''},
            {name: 'MIXITE', sciName: '(Hydrated Bismuth Copper Arsenate Hydroxide)', imgUrl:''},
            {name: 'MOCTEZUMITE', sciName: '(Lead Uranyl Tellurite)', imgUrl:''},
            {name: 'MOISSANITE', sciName: '(Silicon Carbide)', imgUrl:''},
            {name: 'MOLDAVITE', sciName: '(variety of Tecktite: Meteoric Silica Glass)', imgUrl:''},
            {name: 'MOLYBDENUM', sciName: '(the element Molybdenum)', imgUrl:''},
            {name: 'MOLYBDENITE', sciName: '(Molybdenum Sulfide)', imgUrl:''},
            {name: 'MONAZITE', sciName: '(Cerium Lanthanum Thorium Neodymium Yttrium Phosphate)', imgUrl:''},
            {name: 'MONTEBRASITE', sciName: '(Lithium Sodium Aluminum Phosphate Hydroxide Fluoride)', imgUrl:''},
            {name: 'MONTMORILLONITE', sciName: '(Hydrated Sodium Calcium Aluminum Magnesium Silicate Hydroxide)', imgUrl:''},
            {name: 'MOONSTONE', sciName: '(variety of Oligoclase, Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'MORDENITE', sciName: '(Hydrated Calcium Sodium Potassium Aluminum Silicate)', imgUrl:''},
            {name: 'MORGANITE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)', imgUrl:''},
            {name: 'MOSCHELLANDSBERGITE', sciName: '(Silver Mercury or Silver Amalgam)', imgUrl:''},
            {name: 'MOTTRAMITE', sciName: '(Lead Copper Vanadate Hydroxide)', imgUrl:''},
            {name: 'MURMANITE', sciName: '(Hydrated Sodium Titanium Niobium Silicate)', imgUrl:''},
            {name: 'MUSCOVITE', sciName: '(Potassium Aluminum Silicate Hydroxide Fluoride)', imgUrl:''}
        ],
        n: [
            {name: 'NAGYAGITE', sciName: '(Lead Gold Antimony Bismuth Telluride Sulfide)', imgUrl:''},
            {name: 'NAHCOLITE', sciName: '(Sodium Bicarbonate)', imgUrl:''},
            {name: 'NARSARSUKITE', sciName: '(Sodium Titanium Iron Silicate Fluoride)', imgUrl:''},
            {name: 'NATROJAROSITE', sciName: '(Sodium Iron Sulfate Hydroxide)', imgUrl:''},
            {name: 'NATROLITE', sciName: '(Hydrated Sodium Aluminum Silicate)', imgUrl:''},
            {name: 'NEALITE', sciName: '(Lead Iron Arsenate Chloride)', imgUrl:''},
            {name: 'NEPHELINE', sciName: '(Sodium Potassium Aluminum Silicate)', imgUrl:''},
            {name: 'NEPHRITE', sciName: '(variety of Actinolite, Calcium Magnesium Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'NEPTUNITE', sciName: '(Potassium Sodium Lithium Iron Manganese Titanium Silicate)', imgUrl:''},
            {name: 'NICKEL', sciName: '(the element Nickel)', imgUrl:''},
            {name: 'NICKELINE', sciName: '(Nickel Arsenide)', imgUrl:''},
            {name: 'NITER', sciName: '(Potasium Nitrate)', imgUrl:''},
            {name: 'NITRATINE', sciName: '(Sodium Nitrate)', imgUrl:''},
            {name: 'NORBERGITE', sciName: '(Magnesium Silicate Fluoride Hydroxide)', imgUrl:''}
        ],
        o: [
            {name: 'OBSIDIAN', sciName: '(Volcanic Silica Glass)', imgUrl:''},
            {name: 'OKENITE', sciName: '(Hydrated Calcium Silicate)', imgUrl:''},
            {name: 'OLIGOCLASE', sciName: '(Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'OLIVINE', sciName: '(Magnesium Iron Silicate)', imgUrl:''},
            {name: 'OLIVENITE', sciName: '(Copper Arsenate Hydroxide)', imgUrl:''},
            {name: 'ONYX', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'OPAL', sciName: '(Hydrated Silica)', imgUrl:''},
            {name: 'ORPIMENT', sciName: '(Arsenic Sulfide)', imgUrl:''},
            {name: 'ORTHOCLASE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
            {name: 'OSBORNITE', sciName: '(Titanium Nitride)', imgUrl:''},
            {name: 'OSUMILITE', sciName: '(Hydrated Potassium Sodium Iron Magnesium Aluminum Silicate)', imgUrl:''},
            {name: 'OTAVITE', sciName: '(Cadmium Carbonate)', imgUrl:''}
        ],
        p: [
            {name: 'PACHNOLITE', sciName: '(Hydrated Sodium Calcium Aluminum Fluoride)', imgUrl:''},
            {name: 'PALYGORSKITE', sciName: '(Hydrated Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'PAPAGOITE', sciName: '(Calcium Copper Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'PARADAMITE', sciName: '(Zinc Arsenate Hydroxide)', imgUrl:''},
            {name: 'PARASYMPLESITE', sciName: '(Hydrated Iron Arsenate)', imgUrl:''},
            {name: 'PARAVAUXITE', sciName: '(Hydrated Iron Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'PARISITE', sciName: '(Calcium Cerium Lanthanum Neodymium Carbonate Fluoride)', imgUrl:''},
            {name: 'PECTOLITE', sciName: '(Sodium Calcium Silicate Hydroxide)', imgUrl:''},
            {name: 'PENTLANDITE', sciName: '(Iron Nickel Sulfide)', imgUrl:''},
            {name: 'PERICLASE', sciName: '(Magnesium Oxide)', imgUrl:''},
            {name: 'PERIDOT', sciName: '(variety of Olivine)', imgUrl:''},
            {name: 'PEROVSKITE', sciName: '(Calcium Titanium Oxide)', imgUrl:''},
            {name: 'PHARMACOLITE', sciName: '(Hydrated Calcium Arsenate Hydroxide)', imgUrl:''},
            {name: 'PHARMACOSIDERITE', sciName: '(Hydrated Potassium Iron Arsenate Hydroxide)', imgUrl:''},
            {name: 'PHENAKITE', sciName: '(Berylium Silicate)', imgUrl:''},
            {name: 'PHILLIPSITE', sciName: '(Hydrated Potasium Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'PHLOGOPITE', sciName: '(Potassium Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'PHOSGENITE', sciName: '(Lead Carbonate Chloride)', imgUrl:''},
            {name: 'PHOSPHOPHYLLITE', sciName: '(Hydrated Zinc Iron Manganese Phosphate)', imgUrl:''},
            {name: 'PHOSPHURANYLITE', sciName: '(Hydrated Calcium Uranyl Phosphate Hydroxide)', imgUrl:''},
            {name: 'PICROMERITE', sciName: '(Hydrated Potassium Magnesium Sulfate)', imgUrl:''},
            {name: 'PIRSSONITE', sciName: '(Hydrated Sodium Calcium Carbonate)', imgUrl:''},
            {name: 'PLANCHEITE', sciName: '(Hydrated Copper Silicate Hydroxide)', imgUrl:''},
            {name: 'PLATINUM', sciName: '(Pt)', imgUrl:''},
            {name: 'PLATTNERITE', sciName: '(Lead Oxide)', imgUrl:''},
            {name: 'POLYBASITE', sciName: '(Silver Copper Antimony Sulfide)', imgUrl:''},
            {name: 'POLYHALITE', sciName: '(Hydrated Potassium Calcium Magnesium Sulfate)', imgUrl:''},
            {name: 'POLYLITHIONITE', sciName: '(Potassium Lithium Aluminum Silicate Fluoride)', imgUrl:''},
            {name: 'POWELLITE', sciName: '(Calcium Molybdenate)', imgUrl:''},
            {name: 'PRASIOLITE', sciName: '(variety of Quartz)', imgUrl:''},
            {name: 'PREHNITE', sciName: '(Calcium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'PROUSTITE', sciName: '(Silver Arsenic Sulfide)', imgUrl:''},
            {name: 'PSEUDOBOLEITE', sciName: '(Lead Copper Chloride Hydroxide)', imgUrl:''},
            {name: 'PSEUDOBROOKITE', sciName: '(Iron Titanium Oxide)', imgUrl:''},
            {name: 'PSEUDOMALACHITE', sciName: '(Copper Phosphate Hydroxide)', imgUrl:''},
            {name: 'PSILOMELANE', sciName: '(Manganese Oxide)', imgUrl:''},
            {name: 'PUCHERITE', sciName: '(Bismuth Vanadate)', imgUrl:''},
            {name: 'PURPURITE', sciName: '(Manganese Phosphate)', imgUrl:''},
            {name: 'PYRARGYRITE', sciName: '(Silver Antimony Sulfide)', imgUrl:''},
            {name: 'PYRITE', sciName: '(Iron Sulfide)', imgUrl:''},
            {name: 'PYROAURITE', sciName: '(Hydrated Magnesium Iron Carbonate Hydroxide)', imgUrl:''},
            {name: 'PYROCHLORE', sciName: '(Calcium Sodium Niobium Oxide Hydroxide Fluoride)', imgUrl:''},
            {name: 'PYROLUSITE', sciName: '(Manganese Oxide)', imgUrl:''},
            {name: 'PYROMORPHITE', sciName: '(Lead Chlorophosphate)', imgUrl:''},
            {name: 'PYROPE', sciName: '(Magnesium Aluminum Silicate)', imgUrl:''},
            {name: 'PYROPHYLLITE', sciName: '(Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'PYRRHOTITE', sciName: '(Iron Sulfide)', imgUrl:''}
        ],
        q: [
            {name: 'QUARTZ', sciName: '(Silicon Oxide)', imgUrl:''},
            {name: 'QUETZALCOATLITE', sciName: '(Zinc Copper Tellurite Hydroxide)', imgUrl:''}
        ],
        r: [
            {name: 'RAITE', sciName: '(Hydrated Sodium Calcium Manganese Titanium Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'RAMMELSBERGITE', sciName: '(Nickel Arsenide)', imgUrl:''},
            {name: 'RAMSDELLITE', sciName: '(Manganese Oxide)', imgUrl:''},
            {name: 'REALGAR', sciName: '(Arsenic Sulfide)', imgUrl:''},
            {name: 'RHABDOPHANE', sciName: '(Hydrated Cerium Lanthanum Neodymium Phosphate)', imgUrl:''},
            {name: 'RHENIITE', sciName: '(Rhenium Sulfide)', imgUrl:''},
            {name: 'RHODIZITE', sciName: '(Potassium Cesium Beryllium Aluminum Borate)', imgUrl:''},
            {name: 'RHODOCHROSITE', sciName: '(Manganese Carbonate)', imgUrl:''},
            {name: 'RHODOLITE', sciName: '(variety of PYROPE garnet, Magnesium Aluminum Silicate)', imgUrl:''},
            {name: 'RHODONITE', sciName: '(Manganese Iron Magnesium Calcium Silicate)', imgUrl:''},
            {name: 'RICHTERITE', sciName: '(Sodium Calcium Magnesium Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'RIEBECKITE', sciName: '(Sodium Iron Magnesium Silicate Hydroxide)', imgUrl:''},
            {name: 'ROCKBRIDGEITE', sciName: '(Iron Manganese Phosphate Hydroxide)', imgUrl:''},
            {name: 'ROMANECHITE', sciName: '(Hydrated Barium Manganese Oxide)', imgUrl:''},
            {name: 'ROSASITE', sciName: '(Copper Zinc Carbonate Hydroxide)', imgUrl:''},
            {name: 'ROSE QUARTZ', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:''},
            {name: 'ROSELITE', sciName: '(Hydrated Calcium Cobalt Magnesium Arsenate)', imgUrl:''},
            {name: 'RUBY', sciName: '(variety of Corundum- Aluminum Oxide)', imgUrl:''},
            {name: 'RUTILE', sciName: '(Titanium Oxide)', imgUrl:''}
        ],
        s: [
            {name: 'SAFFLORITE', sciName: '(Cobalt Iron Arsenide)', imgUrl:''},
            {name: 'SAINFELDITE', sciName: '(Hydrated Calcium Arsenate Hydroxide)', imgUrl:''},
            {name: 'SAL AMMONIAC', sciName: '(Ammonium Chloride)', imgUrl:''},
            {name: 'SAMARSKITE', sciName: '(Yttrium Cerium Uranium Iron Niobium Tantalum Titanium Oxide)', imgUrl:''},
            {name: 'SANBORNITE', sciName: '(Barium Silicate)', imgUrl:''},
            {name: 'SANIDINE', sciName: '(Potasium Aluminum Silicate)', imgUrl:''},
            {name: 'SAPPHIRE', sciName: '(variety of Corundum- Aluminum Oxide)', imgUrl:''},
            {name: 'SARD', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'SARDONYX', sciName: '(variety of Quartz - Silicon Oxide)', imgUrl:''},
            {name: 'SARTORITE', sciName: '(Lead Arsenic Sulfide)', imgUrl:''},
            {name: 'SCAPOLITE', sciName: '(Sodium Calcium Aluminum Silicate Chloride Carbonate Sulfate)', imgUrl:''},
            {name: 'SCHEELITE', sciName: '(Calcium Tungstate)', imgUrl:''},
            {name: 'SCHMITTERITE', sciName: '(Uranyl Tellurite)', imgUrl:''},
            {name: 'SCHOLZITE', sciName: '(Hydrated Calcium Zinc Phosphate)', imgUrl:''},
            {name: 'SCHORL', sciName: '(complex Sodium Iron Boro-Aluminum Silicate)', imgUrl:''},
            {name: 'SCHROCKINGERITE', sciName: '(Hydrated Sodium Calcium Uranyl Sulfate Carbonate Fluoride)', imgUrl:''},
            {name: 'SCOLECITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'SCORODITE', sciName: '(Hydrated Iron Arsenate)', imgUrl:''},
            {name: 'SCORZALITE', sciName: '(Iron Magnesium Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'SELENITE', sciName: '(alternate name for Gypsum)', imgUrl:''},
            {name: 'SEMSEYITE', sciName: '(Lead Antimony Sulfide)', imgUrl:''},
            {name: 'SENARMONTITE', sciName: '(Antimony Oxide)', imgUrl:''},
            {name: 'SERANDITE', sciName: '(Sodium Manganese Calcium Silicate Hydroxide)', imgUrl:''},
            {name: 'SERPENTINE', sciName: '(Iron Magnesium Nickel Silicate Hydroxide)', imgUrl:''},
            {name: 'SHATTUCKITE', sciName: '(Copper Silicate Hydroxide)', imgUrl:''},
            {name: 'SIDERITE', sciName: '(Iron Carbonate)', imgUrl:''},
            {name: 'SILLIMANITE', sciName: '(Aluminum Silicate)', imgUrl:''},
            {name: 'SILVER', sciName: '(Ag)', imgUrl:''},
            {name: 'SINHALITE', sciName: '(Magnesium Aluminum Borate)', imgUrl:''},
            {name: 'SJOGRENITE', sciName: '(Hydrated Magnesium Iron Carbonate Hydroxide)', imgUrl:''},
            {name: 'SKLODOWSKITE', sciName: '(Hydrated Magnesium Uranyl Silicate)', imgUrl:''},
            {name: 'SKUTTERUDITE', sciName: '(Cobalt Arsenide)', imgUrl:''},
            {name: 'SMITHSONITE', sciName: '(Zinc Carbonate)', imgUrl:''},
            {name: 'SMOKY QUARTZ', sciName: '(variety of Quartz- Silicon Oxide)', imgUrl:''},
            {name: 'SODALITE', sciName: '(Sodium Aluminum Silicate Chloride)', imgUrl:''},
            {name: 'SPANGOLITE', sciName: '(Hydrated Copper Aluminum Sulfate Chloride Hydroxide)', imgUrl:''},
            {name: 'SPERRYLITE', sciName: '(Platinum Arsenide)', imgUrl:''},
            {name: 'SPESSARTINE', sciName: '(Manganese Aluminum Silicate)', imgUrl:''},
            {name: 'SPHAEROCOBALTITE', sciName: '(Cobalt Carbonate)', imgUrl:''},
            {name: 'SPHALERITE', sciName: '(Zinc Iron Sulfide)', imgUrl:''},
            {name: 'SPHENE', sciName: '(Calcium Titanium Silicate)', imgUrl:''},
            {name: 'SPINEL', sciName: '(Magnesium Aluminum Oxide)', imgUrl:''},
            {name: 'SPODUMENE', sciName: '(Lithium Aluminum Silicate)', imgUrl:''},
            {name: 'STAUROLITE', sciName: '(Iron Magnesium Zinc Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'STELLERITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'STEPHANITE', sciName: '(Silver Antimony Sulfide)', imgUrl:''},
            {name: 'STIBARSEN', sciName: '(Antimony Arsenic)', imgUrl:''},
            {name: 'STIBICONITE', sciName: '(Antimony Oxide Hydroxide)', imgUrl:''},
            {name: 'STIBNITE', sciName: '(Antimony Sulfide)', imgUrl:''},
            {name: 'STICHTITE', sciName: '(Hydrated Magnesium Chromium Carbonate Hydroxide)', imgUrl:''},
            {name: 'STILBITE', sciName: '(Hydrated Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'STISHOVITE', sciName: '(Silicon Dioxide)', imgUrl:''},
            {name: 'STRENGITE', sciName: '(Hydrated Iron Phosphate)', imgUrl:''},
            {name: 'STRONTIANITE', sciName: '(Strontium Carbonate)', imgUrl:''},
            {name: 'STRUNZITE', sciName: '(Calcium Zinc Arsenate Hydroxide)', imgUrl:''},
            {name: 'STURMANITE', sciName: '(Hydrated Calcium Iron Aluminum Manganese Sulfate Tetrahydroxoborate Hydroxide)', imgUrl:''},
            {name: 'SUGILITE', sciName: '(Potassium Sodium Lithium Iron Manganese Aluminum Silicate)', imgUrl:''},
            {name: 'SULFUR', sciName: '(S)', imgUrl:''},
            {name: 'SUNSTONE', sciName: '(variety of Oligoclase, Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'SUOLUNITE', sciName: '(Hydrated Calcium Silicate Hydroxide)', imgUrl:''},
            {name: 'SUSANNITE', sciName: '(Lead Sulfate Carbonate Hydroxide)', imgUrl:''},
            {name: 'SUSSEXITE', sciName: '(Manganese Borate Hydroxide)', imgUrl:''},
            {name: 'SVANBERGITE', sciName: '(Strontium Aluminum Phosphate Sulfate Hydroxide)', imgUrl:''},
            {name: 'SYLVANITE', sciName: '(Silver Gold Telluride)', imgUrl:''},
            {name: 'SYLVITE', sciName: '(Potassium Chloride)', imgUrl:''},
            {name: 'SYMPLESITE', sciName: '(Hydrated Iron Arsenate)', imgUrl:''},
            {name: 'SYNCHYSITE', sciName: '(Calcium Cerium Lanthanum Neodymium Yttrium Carbonate Fluoride)', imgUrl:''}
        ],
        t: [
            {name: 'TAAFFEITE', sciName: '(Beryllium Magnesium Aluminum Oxide)', imgUrl:''},
            {name: 'TAINIOLITE', sciName: '(Potassium Lithium Magnesium Silicate Fluoride)', imgUrl:''},
            {name: 'TALC', sciName: '(Magnesium Silicate Hydroxide)', imgUrl:''},
            {name: 'TANTALITE', sciName: '(Iron Manganese Tantalum Niobium Oxide)', imgUrl:''},
            {name: 'TANZANITE', sciName: '(gem variety of Zoisite)', imgUrl:''},
            {name: 'TARBUTTITE', sciName: '(Zinc Phosphate Hydroxide)', imgUrl:''},
            {name: 'TEALLITE', sciName: '(Lead Tin Sulfide)', imgUrl:''},
            {name: 'TEKTITES', sciName: '(Meteoric Silica Glass)', imgUrl:''},
            {name: 'TELLURIUM', sciName: '(Te)', imgUrl:''},
            {name: 'TENNANTITE', sciName: '(Copper Arsenic Sulfide)', imgUrl:''},
            {name: 'TEPHROITE', sciName: '(Manganese Silicate)', imgUrl:''},
            {name: 'TETRAHEDRITE', sciName: '(Copper Antimony Sulfide)', imgUrl:''},
            {name: 'THAUMASITE', sciName: '(Hydrated Calcium Silicon Carbonate Sulfate Hydroxide)', imgUrl:''},
            {name: 'THENARDITE', sciName: '(Sodium Sulfate)', imgUrl:''},
            {name: 'THOMSONITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)', imgUrl:''},
            {name: 'THORITE', sciName: '(Thorium Uranium Silicate)', imgUrl:''},
            {name: 'THOROGUMMITE', sciName: '(Thorium Uranium Silicate Hydroxide)', imgUrl:''},
            {name: 'TIN', sciName: '(Sn)', imgUrl:''},
            {name: 'TINAKSITE', sciName: '(Titanium Sodium Potasium Silicate Hydroxide)', imgUrl:''},
            {name: 'TINCALCONITE', sciName: '(Hydrated Sodium Borate)', imgUrl:''},
            {name: 'TITANIUM', sciName: '(Ti)', imgUrl:''},
            {name: 'TITANITE', sciName: '(alternate name for Sphene)', imgUrl:''},
            {name: 'TOPAZ', sciName: '(Aluminum Silicate Fluoride Hydroxide)', imgUrl:''},
            {name: 'TOPAZOLITE', sciName: '(the yellow variety of Andradite Garnet)', imgUrl:''},
            {name: 'TORBERNITE', sciName: '(Hydrated Copper Uranyl Phosphate)', imgUrl:''},
            {name: 'TOURMALINE', sciName: '(Group)', imgUrl:''},
            {name: 'TREMOLITE', sciName: '(Calcium Magnesium Iron Silicate Hydroxide)', imgUrl:''},
            {name: 'TRIDYMITE', sciName: '(Silicon Dioxide)', imgUrl:''},
            {name: 'TRIPHYLITE', sciName: '(Lithium Iron Manganese Phosphate)', imgUrl:''},
            {name: 'TRONA', sciName: '(Hydrated Sodium Bicarbonate Carbonate)', imgUrl:''},
            {name: 'TSAVORITE', sciName: '(variety of Grossular garnet)', imgUrl:''},
            {name: 'TSUMCORITE', sciName: '(Hydrated Lead Zinc Iron Arsenate)', imgUrl:''},
            {name: 'TSUMEBITE', sciName: '(Lead Copper Phosphate Sulfate)', imgUrl:''},
            {name: 'TURQUOISE', sciName: '(Hydrated Copper Aluminum Phosphate)', imgUrl:''},
            {name: 'TYUYAMUNITE', sciName: '(Hydrated Calcium Uranyl Vanadate)', imgUrl:''}
        ],
        u: [
            {name: 'ULEXITE', sciName: '(Sodium Calcium Borate Hydroxide)', imgUrl:''},
            {name: 'ULLMANNITE', sciName: '(Nickel Antimony Sulfide)', imgUrl:''},
            {name: 'URANINITE', sciName: '(Uranium Oxide)', imgUrl:''},
            {name: 'URANOCIRCITE', sciName: '(Hydrated Barium Uranyl Phosphate)', imgUrl:''},
            {name: 'URANOPHANE', sciName: '(Hydrated Calcium Uranyl Silicate)', imgUrl:''},
            {name: 'URANOPILITE', sciName: '(Hydrated Uranyl Sulfate Hydroxide)', imgUrl:''},
            {name: 'UVAROVITE', sciName: '(Calcium Chromium Silicate)', imgUrl:''},
            {name: 'UVITE', sciName: '(complex Calcium Sodium Magnesium Iron Boro-Aluminum Silicate Hydroxide)', imgUrl:''}
        ],
        v: [
            {name: 'VALENTINITE', sciName: '(Antimony Oxide)', imgUrl:''},
            {name: 'VANADINITE', sciName: '(Lead Chlorovanadinate)', imgUrl:''},
            {name: 'VARISCITE', sciName: '(Hydrated Aluminum Phosphate)', imgUrl:''},
            {name: 'VAUXITE', sciName: '(Hydrated Iron Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'VERMICULITE', sciName: '(Hydrated Magnesium Iron Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'VESUVIANITE', sciName: '(Calcium Magnesium Aluminum Silicate Hydroxide)', imgUrl:''},
            {name: 'VESZELYITE', sciName: '(Hydrated Copper Zinc Phosphate Hydroxide)', imgUrl:''},
            {name: 'VILLIAUMITE', sciName: '(Sodium Fluoride)', imgUrl:''},
            {name: 'VIVIANITE', sciName: '(Hydrated Iron Phosphate)', imgUrl:''},
            {name: 'VOLBORTHITE', sciName: '(Copper Vanadate Hydroxide)', imgUrl:''}
        ],
        w: [
            {name: 'WALPURGITE', sciName: '(Hydrated Bismuth Uranyl Arsenate Oxide)', imgUrl:''},
            {name: 'WARDITE', sciName: '(Hydrated Sodium Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'WAVELLITE', sciName: '(Hydrated Aluminum Phosphate Hydroxide)', imgUrl:''},
            {name: 'WELOGANITE', sciName: '(Hydrated Sodium Strontium Calcium Zirconium Carbonate)', imgUrl:''},
            {name: 'WERNERITE', sciName: '(properly called Scapolite, Sodium Calcium Aluminum Silicate Chloride Carbonate Sulfate)', imgUrl:''},
            {name: 'WHEWELLITE', sciName: '(Hydrated Calcium Oxalate)', imgUrl:''},
            {name: 'WHITEITE', sciName: '(Hydrated Calcium Iron Manganese Magnesium Aluminum Phosphate)', imgUrl:''},
            {name: 'WHITLOCKITE', sciName: '(Calcium Magnesium Iron Phosphate Hydroxide)', imgUrl:''},
            {name: 'WILLEMITE', sciName: '(Zinc Silicate)', imgUrl:''},
            {name: 'WITHERITE', sciName: '(Barium Carbonate)', imgUrl:''},
            {name: 'WOLFEITE', sciName: '(Iron Manganese Phosphate Hydroxide)', imgUrl:''},
            {name: 'WOLFRAMITE', sciName: '(Manganese Iron Tungstate)', imgUrl:''},
            {name: 'WOLLASTONITE', sciName: '(Calcium Silicate)', imgUrl:''},
            {name: 'WOODHOUSEITE', sciName: '(Calcium Aluminum Phosphate Sulfate Hydroxide)', imgUrl:''},
            {name: 'WULFENITE', sciName: '(Lead Molybdenate)', imgUrl:''},
            {name: 'WURTZITE', sciName: '(Zinc Iron Sulfide)', imgUrl:''}
        ],
        x: [
            {name: 'XENOTIME', sciName: '(Yttrium Phosphate)', imgUrl:''},
            {name: 'XONOTLITE', sciName: '(Calcium Silicate Hydroxide)', imgUrl:''}
        ],
        y: [
            {name: 'YUKSPORITE', sciName: '(Hydrated Potassium Barium Sodium Calcium Titanium Silicate Fluoride Hydroxide)', imgUrl:''}
        ],
        z: [
            {name: 'ZEUNERITE', sciName: '(Hydrated Copper Uranyl Arsenate)', imgUrl:''},
            {name: 'ZINC', sciName: '(Zn)', imgUrl:''},
            {name: 'ZINCITE', sciName: '(Zinc Manganese Oxide)', imgUrl:''},
            {name: 'ZINKENITE', sciName: '(Lead Antimony Sulfide)', imgUrl:''},
            {name: 'ZINNWALDITE', sciName: '(Potassium Lithium Iron Aluminum Silicate Hydroxide Fluoride)', imgUrl:''},
            {name: 'ZIPPEITE', sciName: '(Hydrated Potassium Uranyl Sulfate Hydroxide)', imgUrl:''},
            {name: 'ZIRCON', sciName: '(Zirconium Silicate)', imgUrl:''},
            {name: 'ZOISITE', sciName: '(Calcium Aluminum Silicate Hydroxide)', imgUrl:''}
        ]
    };

    public getRandomMineral(letter:string){
        //return a random mineral, given a letter.
    }

}
