import { Injectable } from '@angular/core';
import * as _ from 'lodash';
@Injectable()
export class RockService {
    private minerals: object;

    constructor() {

        minerals = {
            a: [
                { name: 'ACANTHITE', sciName: '(Silver Sulfide)' },
                { name: 'ACTINOLITE', sciName: '(Calcium Magnesium Iron Silicate Hydroxide)' },
                { name: 'ADAMITE', sciName: '(Zinc Arsenate Hydroxide)' },
                { name: 'AEGIRINE', sciName: '(Sodium Iron Silicate)' },
                { name: 'AESCHYNITE', sciName: '(Yttrium Calcium Iron Thorium Titanium Niobium Oxide Hydroxide)' },
                { name: 'AGATE', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'AJOITE', sciName: '(Hydrated Potassium Sodium Copper Aluminum Silicate Hydroxide)' },
                { name: 'ALBITE', sciName: '(Sodium Aluminum Silicate)' },
                { name: 'ALEXANDRITE', sciName: '(variety of Chrysoberyl- Beryllium Aluminum Oxide)' },
                { name: 'ALLANITE', sciName: '(Calcium Cerium Lanthanum Yttrium Aluminum Iron Silicate Hydroxide)' },
                { name: 'ALLUVIAL', sciName: '(a type of unconsolidated sediments)' },
                { name: 'ALMANDINE', sciName: '(Iron Aluminum Silicate)' },
                { name: 'ALTAITE', sciName: '(Lead Telluride)' },
                { name: 'ALUMINUM', sciName: '(Al)' },
                { name: 'ALUNITE', sciName: '(Potassium Aluminum Sulfate Hydroxide)' },
                { name: 'AMBER', sciName: '(Succinite: fossilized tree resin)' },
                { name: 'AMBLYGONITE', sciName: '(Lithium Sodium Aluminum Phosphate Fluoride Hydroxide)' },
                { name: 'AMETHYST', sciName: '(variety of Quartz- Silicon Oxide)' },
                { name: 'ANALCIME', sciName: '(Hydrated Sodium Aluminum Silicate)' },
                { name: 'ANAPAITE', sciName: '(Hydrated Calcium Iron Phosphate)' },
                { name: 'ANATASE', sciName: '(Titanium Oxide)' },
                { name: 'ANDALUSITE', sciName: '(Aluminum Silicate)' },
                { name: 'ANDERSONITE', sciName: '(Hydrated Sodium Calcium Uranyl Carbonate)' },
                { name: 'ANDESINE', sciName: '(Sodium Calcium Aluminum Silicate)' },
                { name: 'ANDESITE', sciName: '(an extrusive igneous rock)' },
                { name: 'ANDRADITE', sciName: '(Calcium Iron Silicate)' },
                { name: 'ANGELITE', sciName: '(trade name for Anhydrite)' },
                { name: 'ANGLESITE', sciName: '(Lead Sulfate)' },
                { name: 'ANHYDRITE', sciName: '(Calcium Sulfate)' },
                { name: 'ANKERITE', sciName: '(Calcium Iron Carbonate)' },
                { name: 'ANNABERGITE', sciName: '(Hydrated Nickel Arsenate)' },
                { name: 'ANORTHITE', sciName: '(Calcium Aluminum Silicate)' },
                { name: 'ANORTHOSITE', sciName: '(a plutonic igneous rock)' },
                { name: 'ANTHOPHYLLITE', sciName: '(Magnesium Iron Silicate Hydroxide)' },
                { name: 'ANTIMONY', sciName: '(Sb)' },
                { name: 'ANTLERITE', sciName: '(Copper Sulfate Hydroxide)' },
                { name: 'APATITE', sciName: '(Calcium Fluoro, Chloro, Hydroxyl Phosphate)' },
                { name: 'APOPHYLLITE', sciName: '(Hydrated Potassium Calcium Silicate Hydroxide Flouride)' },
                { name: 'AQUAMARINE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)' },
                { name: 'ARAGONITE', sciName: '(Calcium Carbonate)' },
                { name: 'ARFVEDSONITE', sciName: '(Sodium Iron Magnesium Silicate Hydroxide)' },
                { name: 'ARGENTITE', sciName: '(Silver Sulfide)' },
                { name: 'ARGYRODITE', sciName: '(Silver Germanium Sulfide)' },
                { name: 'ARSENIC', sciName: '(As)' },
                { name: 'ARSENOPYRITE', sciName: '(Iron Arsenide Sulfide)' },
                { name: 'ARSENTSUMEBITE', sciName: '(Lead Copper Arsenate Sulfate)' },
                { name: 'ARTHURITE', sciName: '(Hydrated Copper Iron Arsenate Phosphate Sulfate)' },
                { name: 'ARTINITE', sciName: '(Hydrated Magnesium Carbonate Hydroxide)' },
                { name: 'ASTEROIDS', sciName: '(primordial stony or metallic rocks in space)' },
                { name: 'ASTROPHYLLITE', sciName: '(Potassium Iron Titanium Silicate Hydroxide)' },
                { name: 'ATACAMITE', sciName: '(Copper Chloride Hydroxide)' },
                { name: 'AUGELITE', sciName: '(Aluminum Phosphate Hydroxide)' },
                { name: 'AUGITE', sciName: '(Calcium Sodium Magnesium Aluminum Iron Titanium Silicate)' },
                { name: 'AURICHALCITE', sciName: '(Zinc Copper Carbonate Hydroxide)' },
                { name: 'AUSTINITE', sciName: '(Calcium Zinc Arsenate Hydroxide)' },
                { name: 'AUTUNITE', sciName: '(Hydrated Calcium Uranyl Phosphate)' },
                { name: 'AXINITE', sciName: '(Calcium Iron Magnesium Manganese Aluminum Boro-Silicate Hydroxide)' },
                { name: 'AZURITE', sciName: '(Copper Carbonate Hydroxide)' }
            ],
            b: [
                { name: 'BABINGTONITE', sciName: '(Calcium Iron Manganese Silicate Hydroxide)' },
                { name: 'BAKERITE', sciName: '(Hydrated Calcium Boro-silicate Hydroxide)' },
                { name: 'BARATOVITE', sciName: '(Potassium Lithium Calcium Titanium Zirconium Silicate Fluoride)' },
                { name: 'BARITE', sciName: '(Barium Sulfate)' },
                { name: 'BASALT', sciName: '(the most common igneous rock)' },
                { name: 'BASTNASITE', sciName: '(Cerium Lanthanum Yttrium Carbonate Fluoride)' },
                { name: 'BAUMHAUERITE', sciName: '(Lead Arsenic Sulfide)' },
                { name: 'BAYLDONITE', sciName: '(Hydrated Copper Lead Arsenate Hydroxide)' },
                { name: 'BECQUERELITE', sciName: '(Hydrated Calcium Uranyl Oxide Hydroxide)' },
                { name: 'BENITOITE', sciName: '(Barium Titanium Silicate)' },
                { name: 'BERAUNITE', sciName: '(Hydrated Iron Phosphate Hydroxide)' },
                { name: 'BERLINITE', sciName: '(Aluminum Phosphate)' },
                { name: 'BERTHIERITE', sciName: '(Iron Antimony Sulfide)' },
                { name: 'BERTRANDITE', sciName: '(Beryllium Silicate Hydroxide)' },
                { name: 'BERYL', sciName: '(Berylium Aluminum Silicate)' },
                { name: 'BERYLLONITE', sciName: '(Sodium Beryllium Phosphate)' },
                { name: 'BETAFITE', sciName: '(Calcium Sodium Uranium Titanium Niobium Tantalum Oxide Hydroxide Fluoride)' },
                { name: 'BEUDANTITE', sciName: '(Lead Iron Arsenate Sulfate Hydroxide)' },
                { name: 'BIDEAUXITE', sciName: '(Lead Silver Chloride Fluoride Hydroxide)' },
                { name: 'BIF', sciName: '(Banded Iron Formation aka Taconite)' },
                { name: 'BINDHEIMITE', sciName: '(Lead Antimony Oxide)' },
                { name: 'BIOTITE', sciName: '(Potassium Iron Magnesium Aluminum Silicate Hydroxide Fluoride)' },
                { name: 'BISMUTH', sciName: '(Bi)' },
                { name: 'BISMUTHINITE', sciName: '(Bismuth Sulfide)' },
                { name: 'BIXBYITE', sciName: '(Manganese Iron Oxide)' },
                { name: 'BLODITE', sciName: '(Hydrated Sodium Magnesium Sulfate)' },
                { name: 'BLOODSTONE', sciName: '(variety of Chalcedony)' },
                { name: 'BOLEITE', sciName: '(Hydrated Lead Copper Silver Chloride Hydroxide)' },
                { name: 'BOLTWOODITE', sciName: '(Hydrated Potassium Uranyl Silicate Hydroxide)' },
                { name: 'BORACITE', sciName: '(Magnesium Borate Chloride)' },
                { name: 'BORAX', sciName: '(Hydrated Sodium Borate)' },
                { name: 'BORNITE', sciName: '(Copper Iron Sulfide)' },
                { name: 'BOULANGERITE', sciName: '(Lead Antimony Sulfide)' },
                { name: 'BOURNONITE', sciName: '(Copper Lead Antimony Sulfide)' },
                { name: 'BRANNERITE', sciName: '(Uranium Calcium Titanium Iron Oxide)' },
                { name: 'BRASS', sciName: '(Copper Zinc Alloy)' },
                { name: 'BRAZILIANITE', sciName: '(Sodium Aluminum Phosphate Hydroxide)' },
                { name: 'BRECCIA', sciName: '(a clastic sedimentary rock)' },
                { name: 'BROCHANTITE', sciName: '(Copper Sulfate Hydroxide)' },
                { name: 'BROOKITE', sciName: '(Titanium Oxide)' },
                { name: 'BRUCITE', sciName: '(Magnesium Hydroxide)' },
                { name: 'BUERGERITE', sciName: '(Sodium Iron Aluminum Boro-silicate Oxide Fluoride)' },
                { name: 'BURBANKITE', sciName: '(Sodium Calcium Strontium Barium Cerium Carbonate)' },
                { name: 'BUTTGENBACHITE', sciName: '(Hydrated Copper Nitrate Chloride Hydroxide)' },
                { name: 'BYTOWNITE', sciName: '(Calcium Sodium Aluminum Silicate)' }
            ],
            c: [
                { name: 'CACOXENITE', sciName: '(Hydrated Iron Aluminum Phosphate Oxide Hydroxide)' },
                { name: 'CALAVERITE', sciName: '(Gold Telluride)' },
                { name: 'CALCIOVOLBORTHITE', sciName: '(Calcium Copper Vanadate Hydroxide)' },
                { name: 'CALCITE', sciName: '(Calcium Carbonate)' },
                { name: 'CALEDONITE', sciName: '(Copper Lead Carbonate Sulfate Hydroxide)' },
                { name: 'CALOMEL', sciName: '(Mercury Chloride)' },
                { name: 'CANCRINITE', sciName: '(Sodium Calcium Aluminum Silicate Carbonate)' },
                { name: 'CARBOCERNAITE', sciName: '(Calcium Sodium Strontium Cerium Barium Carbonate)' },
                { name: 'CARLETONITE', sciName: '(Hydrated Potassium Sodium Calcium Carbonate Silicate Fluoride Hydroxide)' },
                { name: 'CARNALLITE', sciName: '(Hydrated Potasium Magnesium Chloride)' },
                { name: 'CARNELIAN', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'CARNOTITE', sciName: '(Hydrated Potassium Uranyl Vanadate)' },
                { name: 'CASSITERITE', sciName: '(Tin Oxide)' },
                { name: 'CATAPLEIITE', sciName: '(Hydrated Sodium Zirconium Silicate)' },
                { name: 'CAVANSITE', sciName: '(Hydrated Calcium Vanadium Silicate)' },
                { name: 'CELESTITE', sciName: '(Strontium Sulfate)' },
                { name: 'CERUSSITE', sciName: '(Lead Carbonate)' },
                { name: 'CHABAZITE', sciName: '(Hydrated Calcium Aluminum Silicate)' },
                { name: 'CHALCANTHITE', sciName: '(Hydrated Copper Sulfate)' },
                { name: 'CHALCEDONY', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'CHALCOCITE', sciName: '(Copper Sulfide)' },
                { name: 'CHALCOPHYLLITE', sciName: '(Hydrated Copper Aluminum Sulphate Arsenate Hydroxide)' },
                { name: 'CHALCOPYRITE', sciName: '(Copper Iron Sulfide)' },
                { name: 'CHALCOSIDERITE', sciName: '(Hydrated Copper Iron Phosphate Hydroxide)' },
                { name: 'CHALCOTRICHITE', sciName: '(variety of Cuprite, Copper Oxide)' },
                { name: 'CHALK', sciName: '(a sedimentary rock)' },
                { name: 'CHAROITE', sciName: '(Hydrated Sodium Calcium Barium Strontium Silicate Hydroxide Fluoride)' },
                { name: 'CHENGDEITE', sciName: '(Iridium Iron)' },
                { name: 'CHILDRENITE', sciName: '(Hydrated Iron Manganese Aluminum Phosphate Hydroxide)' },
                { name: 'CHKALOVITE', sciName: '(Sodium Beryllium Silicate)' },
                { name: 'CHLORAPATITE', sciName: '(the chlorine rich apatite)' },
                { name: 'CHLORARGYRITE', sciName: '(Silver Chloride)' },
                { name: 'CHLORITE', sciName: '(Iron Magnesium Aluminum Silicate Hydroxide)' },
                { name: 'CHONDRODITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)' },
                { name: 'CHROMITE', sciName: '(Magnesium Iron Chromium Oxide)' },
                { name: 'CHROMIUM', sciName: '(Cr)' },
                { name: 'CHRYSOBERYL', sciName: '(Berylium Aluminum Oxide)' },
                { name: 'CHRYSOCOLLA', sciName: '(Hydrated Copper Silicate)' },
                { name: 'CHRYSOPRASE', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'CHRYSOTILE', sciName: '(variety of Serpentine, Magnesium Iron Silicate Hydroxide)' },
                { name: 'CHURCHITE', sciName: '(Hydrated Yttrium Erbium Phosphate)' },
                { name: 'CINNABAR', sciName: '(Mercury Sulfide)' },
                { name: 'CITRINE', sciName: '(variety of Quartz- Silicon Oxide)' },
                { name: 'CLAUSTHALITE', sciName: '(Lead Selenide)' },
                { name: 'CLAYS', sciName: '(Group)' },
                { name: 'CLEAVELANDITE', sciName: '(variety of Albite, Sodium Aluminum Silicate)' },
                { name: 'CLIFFORDITE', sciName: '(Uranium Tellurate)' },
                { name: 'CLINOCHLORE', sciName: '(Magnesium Aluminum Silicate Hydroxide)' },
                { name: 'CLINOCLASE', sciName: '(Copper Arsenate Hydroxide)' },
                { name: 'CLINOHEDRITE', sciName: '(Hydrated Calcium Zinc Silicate)' },
                { name: 'CLINOHUMITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)' },
                { name: 'CLINOPTILOLITE', sciName: '(Hydrated Sodium Potassium Calcium Aluminum Silicate)' },
                { name: 'COAL', sciName: '(an organic sedimentary rock)' },
                { name: 'COBALT', sciName: '(Co)' },
                { name: 'COBALTITE', sciName: '(Group)' },
                { name: 'COBALTITE', sciName: '(Cobalt Arsenic Sulfide)' },
                { name: 'COBALTOCALCITE', sciName: '(alternate name for Sphaerocobaltite)' },
                { name: 'COCONINOITE', sciName: '(Hydrated Iron Aluminum Uranyl Phosphate Sulfate Hydroxide)' },
                { name: 'COESITE', sciName: '(Silicon Dioxide)' },
                { name: 'COLEMANITE', sciName: '(Hydrated Calcium Borate Hydroxide)' },
                { name: 'COLLINSITE', sciName: '(Hydrated Calcium Magnesium Iron Phosphate)' },
                { name: 'COLUMBITE', sciName: '(Iron Magnesium Manganese Niobium Tantalum Oxide)' },
                { name: 'COMETS', sciName: '(primordial icy rocks in space)' },
                { name: 'CONICHALCITE', sciName: '(Calcium Copper Arsenate Hydroxide)' },
                { name: 'CONNELLITE', sciName: '(Hydrated Copper Sulfate Chloride Hydroxide)' },
                { name: 'COPIAPITE', sciName: '(Hydrated Iron Magnesium Sulfate Hydroxide)' },
                { name: 'COPPER', sciName: '(Cu)' },
                { name: 'CORDIERITE', sciName: '(Magnesium Aluminum Silicate)' },
                { name: 'CORDYLITE', sciName: '(Barium Cerium Lanthanum Carbonate Fluoride)' },
                { name: 'CORNETITE', sciName: '(Copper Phosphate Hydroxide)' },
                { name: 'CORNWALLITE', sciName: '(Copper Arsenate Hydroxide)' },
                { name: 'CORUNDUM', sciName: '(Aluminum Oxide)' },
                { name: 'COVELLITE', sciName: '(Copper Sulfide)' },
                { name: 'CREEDITE', sciName: '(Hydrated Calcium Aluminum Sulfate Fluoride Hydroxide)' },
                { name: 'CRISTOBALITE', sciName: '(Silicon Dioxide)' },
                { name: 'CROCOITE', sciName: '(Lead Chromate)' },
                { name: 'CROCIDOLITE', sciName: '(asbestiform variety of Riebeckite, Sodium Iron Magnesium Silicate Hydroxide)' },
                { name: 'CRYOLITE', sciName: '(Sodium Aluminum Fluoride)' },
                { name: 'CUBANITE', sciName: '(Copper Iron Sulfide)' },
                { name: 'CUMENGITE', sciName: '(Lead Copper Chloride Hydroxide)' },
                { name: 'CUMMINGTONITE', sciName: '(Magnesium Iron Silicate Hydroxide)' },
                { name: 'CUPRITE', sciName: '(Copper Oxide)' },
                { name: 'CUPROADAMITE', sciName: '(Copper Zinc Arsenate Hydroxide)' },
                { name: 'CUPROSKLODOWSKITE', sciName: '(Hydrated Copper Uranyl Silicate)' },
                { name: 'CYANOTRICHITE', sciName: '(Hydrated Copper Aluminum Sulfate Hydroxide)' },
                { name: 'CYLINDRITE', sciName: '(Iron Lead Tin Antimony Sulfide)' }
            ],
            d: [
                { name: 'DANBURITE', sciName: '(Calcium Boro-Silicate)' },
                { name: 'DATOLITE', sciName: '(Group)' },
                { name: 'DATOLITE', sciName: '(Calcium Boro-Silicate Hydroxide)' },
                { name: 'DESCLOIZITE', sciName: '(Lead Zinc Vanadate Hydroxide)' },
                { name: 'DEMANTOID', sciName: '(variety of Andradite garnet)' },
                { name: 'DEPOSITS', sciName: '(unconsolidated sediments)' },
                { name: 'DIABOLEITE', sciName: '(Lead Copper Chloride Hydroxide)' },
                { name: 'DIAMOND', sciName: '(Carbon)' },
                { name: 'DIGENITE', sciName: '(Copper Sulfide)' },
                { name: 'DIOPSIDE', sciName: '(Calcium Magnesium Silicate)' },
                { name: 'DIOPTASE', sciName: '(Copper Silicate Hydroxide)' },
                { name: 'DOLOMITE', sciName: '(Calcium Magnesium Carbonate)' },
                { name: 'DOMEYKITE', sciName: '(Copper Arsenide)' },
                { name: 'DRAVITE', sciName: '(complex Sodium Magnesium Iron Boro-Aluminum Silicate)' },
                { name: 'DUFRENITE', sciName: '(Hydrated Iron Phosphate Hydroxide)' },
                { name: 'DUFTITE', sciName: '(Lead Calcium Copper Zinc Arsenate Hydroxide)' },
                { name: 'DUMORTIERITE', sciName: '(Aluminum Borate Silicate Oxide)' },
                { name: 'DUNDASITE', sciName: '(Hydrated Lead Aluminum Carbonate Hydroxide)' },
                { name: 'DYSCRASITE', sciName: '(Silver Antimonide)' }
            ],
            e: [
                { name: 'EDENITE', sciName: '(Sodium Calcium Magnesium Iron Aluminum Silicate Hydroxide)' },
                { name: 'EDINGTONITE', sciName: '(Hydrated Barium Aluminum Silicate)' },
                { name: 'ELBAITE', sciName: '(Sodium Lithium Aluminum Boro-Silicate Hydroxide)' },
                { name: 'ELPIDITE', sciName: '(Hydrated Sodium Zirconium Silicate)' },
                { name: 'EMERALD', sciName: '(variety of Beryl- Berylium Aluminum Silicate)' },
                { name: 'EMMONSITE', sciName: '(Hydrated Iron Tellurite)' },
                { name: 'EMPLECTITE', sciName: '(Copper Bismuth Sulfide)' },
                { name: 'ENARGITE', sciName: '(Copper Arsenic Sulfide)' },
                { name: 'ENSTATITE', sciName: '(Magnesium Silicate)' },
                { name: 'EOSPHORITE', sciName: '(Hydrated Manganese Aluminum Phosphate Hydroxide)' },
                { name: 'EPIDIDYMITE', sciName: '(Sodium Beryllium Silicate Hydroxide)' },
                { name: 'EPIDOTE', sciName: '(Calcium Iron Aluminum Silicate Hydroxide)' },
                { name: 'EPISTILBITE', sciName: '(Hydrated Calcium Aluminum Silicate)' },
                { name: 'EPSOMITE', sciName: '(Hydrated Magnesium Sulfate)' },
                { name: 'ERIONITE', sciName: '(Hydrated Potassium Sodium Calcium Magnesium Aluminum Silicate)' },
                { name: 'ERYTHRITE', sciName: '(Hydrated Cobalt Arsenate)' },
                { name: 'ESPERITE', sciName: '(Calcium Lead Zinc Silicate)' },
                { name: 'ETTRINGITE', sciName: '(Hydrated Calcium Aluminum Sulfate Hydroxide)' },
                { name: 'EUCLASE', sciName: '(Beryllium Aluminum Silicate Hydroxide)' },
                { name: 'EUCRYPTITE', sciName: '(Lithium Aluminum Silicate)' },
                { name: 'EUDIALYTE', sciName: '(Sodium Calcium Cerium Iron Manganese Zirconium Silicate Hydroxide Chloride)' },
                { name: 'EUDIDYMITE', sciName: '(Sodium Beryllium Silicate Hydroxide)' },
                { name: 'EUXENITE', sciName: '(Yttrium Calcium Erbium Lanthanum Cerium Uranium Thorium Niobium Tantalum Titanium Oxide)' }
            ],
            f: [
                { name: 'FAYALITE', sciName: '(Magnesium Iron Silicate)' },
                { name: 'FEDORITE', sciName: '(Hydrated Sodium Potassium Calcium Silicate Fluoride Chloride Hydroxide)' },
                { name: 'FELDSPAR', sciName: '(Group)' },
                { name: 'FERBERITE', sciName: '(Iron Tungstate)' },
                { name: 'FERRO-EDENITE ', sciName: '(Sodium Calcium Iron Magnesium Aluminum Silicate Hydroxide)' },
                { name: 'FERROGLAUCOPHANE', sciName: '(Sodium Iron Magnesium Aluminum Silicate Hydroxide)' },
                { name: 'FIEDLERITE', sciName: '(Lead Chloride Fluoride Hydroxide)' },
                { name: 'FLINT', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'FLUORAPATITE', sciName: '(the fluorine rich apatite)' },
                { name: 'FLUORITE', sciName: '(Calcium Fluoride)' },
                { name: 'FLUORRICHTERITE', sciName: '(Sodium Calcium Magnesium Iron Silicate Hydroxide Fluoride)' },
                { name: 'FORSTERITE', sciName: '(Iron Magnesium Silicate)' },
                { name: 'FRANCKEITE', sciName: '(Lead Tin Iron Antimony Sulfide)' },
                { name: 'FRANKLINITE', sciName: '(Zinc Manganese Iron Oxide)' },
                { name: 'FUCHSITE', sciName: '(the chromium-rich muscovite)' },
                { name: 'FULGARITE', sciName: '(lightning created Lechatelierite, Silicon Dioxide)' }
            ],
            g: [
                { name: 'GADOLINITE', sciName: '(Yttrium Iron Beryllium Silicate)' },
                { name: 'GAHNITE', sciName: '(Zinc Aluminum Oxide)' },
                { name: 'GALENA', sciName: '(Group)' },
                { name: 'GALENA', sciName: '(Lead Sulfide)' },
                { name: 'GARNET', sciName: '(Group)' },
                { name: 'GASPEITE', sciName: '(Nickel Magnesium Iron Carbonate)' },
                { name: 'GAYLUSSITE', sciName: '(Hydrated Sodium Calcium Carbonate)' },
                { name: 'GEODES', sciName: '(generally hollow sedimentary rocks)' },
                { name: 'GERSDORFFITE', sciName: '(Nickel Arsenide Sulfide)' },
                { name: 'GIBBSITE', sciName: '(Aluminum Hydroxide)' },
                { name: 'GLAUBERITE', sciName: '(Sodium Calcium Sulfate)' },
                { name: 'GLAUCOPHANE', sciName: '(Sodium Magnesium Iron Aluminum Silicate Hydroxide)' },
                { name: 'GMELINITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)' },
                { name: 'GOETHITE', sciName: '(Hydrated Iron Oxide)' },
                { name: 'GOLD', sciName: '(Au)' },
                { name: 'GOOSECREEKITE', sciName: '(Hydrated Calcium Aluminum Silicate)' },
                { name: 'GORMANITE', sciName: '(Hydrated Iron Magnesium Aluminum Phosphate Hydroxide)' },
                { name: 'GOSHENITE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)' },
                { name: 'GRAEMITE', sciName: '(Hydrated Copper Tellurate)' },
                { name: 'GRANITE', sciName: '(an igneous rock with visible crystals)' },
                { name: 'GRAPHITE', sciName: '(Carbon)' },
                { name: 'GRATONITE', sciName: '(Lead Arsenic Sulfide)' },
                { name: 'GREENOCKITE', sciName: '(Cadmium Sulfide)' },
                { name: 'GROSSULAR', sciName: '(Calcium Aluminum Silicate)' },
                { name: 'GYPSUM', sciName: '(Hydrated Calcium Sulfate)' },
                { name: 'GYROLITE', sciName: '(Hydrated Calcium Silicate Hydroxide)' }
            ],
            h: [
                { name: 'HACKMANITE', sciName: '(variety of Sodalite, Sodium Aluminum Silicate Chloride)' },
                { name: 'HALITE', sciName: '(Sodium Chloride)' },
                { name: 'HANKSITE', sciName: '(Potassium Sodium Sulfate Carbonate Chloride)' },
                { name: 'HARDYSTONITE', sciName: '(Calcium Zinc Silicate)' },
                { name: 'HARMOTOME', sciName: '(Hydrated Barium Potasium Aluminum Silicate)' },
                { name: 'HAUSMANNITE', sciName: '(Manganese Oxide)' },
                { name: 'HEDENBERGITE', sciName: '(Calcium Iron Silicate)' },
                { name: 'HEDYPHANE', sciName: '(Lead Calcium Arsenate Chloride)' },
                { name: 'HELIODOR', sciName: '(variety of Beryl, Berylium Aluminum Silicate)' },
                { name: 'HEMATITE', sciName: '(Iron Oxide)' },
                { name: 'HEMIMORPHITE', sciName: '(Hydrated Zinc Silicate Hydroxide)' },
                { name: 'HERDERITE', sciName: '(Calcium Beryllium Phosphate Fluoride Hydroxide)' },
                { name: 'HESSITE', sciName: '(Silver Telluride)' },
                { name: 'HESSONITE', sciName: '(variety of Grossular garnet)' },
                { name: 'HEULANDITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)' },
                { name: 'HIDDENITE', sciName: '(variety of Spodumene)' },
                { name: 'HILAIRITE', sciName: '(Hydrated Sodium Zirconium Silicate)' },
                { name: 'HINSDALITE', sciName: '(Lead Strontium Aluminum Phosphate Sulfate Hydroxide)' },
                { name: 'HODGKINSONITE', sciName: '(Manganese Zinc Silicate Hydroxide)' },
                { name: 'HOPEITE', sciName: '(Hydrated Zinc Phosphate)' },
                { name: 'HORNBLEND', sciName: '(Calcium Sodium Magnesium Iron Aluminum Silicate Hydroxide)' },
                { name: 'HOWLITE', sciName: '(Calcium Boro-Silicate Hydroxide)' },
                { name: 'HUEBNERITE', sciName: '(Manganese Tungstate)' },
                { name: 'HUMITE', sciName: '(Magnesium Iron Silicate Fluoride Hydroxide)' },
                { name: 'HUREAULITE', sciName: '(Hydrated Manganese Phosphate Hydroxide)' },
                { name: 'HYDROBORACITE', sciName: '(Hydrated Calcium Magnesium Borate)' },
                { name: 'HYDROMAGNESITE', sciName: '(Hydrated Magnesium Carbonate Hydroxide)' },
                { name: 'HYDROXYLAPATITE', sciName: '(the hydroxyl group rich apatite)' },
                { name: 'HYDROXYLBASTNASITE', sciName: '(Cerium Lanthanum Neodymium Carbonate Hydroxide Fluoride)' },
                { name: 'HYDROZINCITE', sciName: '(Hydrated Zinc Carbonate)' },
                { name: 'HYPERSTHENE', sciName: '(Magnesium Iron Silicate)' }
            ],
            i: [
                { name: 'ICE', sciName: '(Hydrogen Oxide)' },
                { name: 'IDOCRASE', sciName: '(alternate name of Vesuvianite)' },
                { name: 'IGNEOUS', sciName: '(rocks that solidified from magma)' },
                { name: 'ILVAITE', sciName: '(Calcium Iron Silicate Hydroxide)' },
                { name: 'ILMENITE', sciName: '(Iron Titanium Oxide)' },
                { name: 'INDICOLITE', sciName: '(blue variety of Elbaite tourmaline)' },
                { name: 'INESITE', sciName: '(Hydrated Calcium Manganese Silicate Hydroxide)' },
                { name: 'IOLITE', sciName: '(variety of Cordierite)' },
                { name: 'IRON', sciName: '(Fe)' }
            ],
            j: [
                { name: 'JADE', sciName: '(gem variety of both Jadeite and Nephrite (variety of Actinolite))' },
                { name: 'JADEITE', sciName: '(Sodium Iron Aluminum Silicate)' },
                { name: 'JAMESONITE', sciName: '(Lead Iron Antimony Sulfide)' },
                { name: 'JAROSITE', sciName: '(Potassium Iron Sulfate Hydroxide)' },
                { name: 'JASPER', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'JOAQUINITE', sciName: '(Barium Sodium Cesium Titanium Niobium Iron Silicate Hydroxide Fluoride)' },
                { name: 'JORDANITE', sciName: '(Lead Arsenic Antimony Sulfide)' }
            ],
            k: [
                { name: 'KAEMMERERITE', sciName: '(the chromium rich variety of cliniclore)' },
                { name: 'KAOLINITE', sciName: '(Aluminum Silicate Hydroxide)' },
                { name: 'KERMESITE', sciName: '(Antimony Oxysulfide)' },
                { name: 'KERNITE', sciName: '(Hydrated Sodium Borate)' },
                { name: 'KIDWELLITE', sciName: '(Hydrated Sodium Iron Phosphate Hydroxide)' },
                { name: 'KIESERITE', sciName: '(Hydrated Magnesium Sulfate)' },
                { name: 'KINOITE', sciName: '(Hydrated Calcium Copper Silicate)' },
                { name: 'KNAUFITE', sciName: '(alternate name for VOLBORTHITE, Copper Vanadate Hydroxide)' },
                { name: 'KOLWEZITE', sciName: '(Copper Cobalt Carbonate Hydroxide)' },
                { name: 'KORNERUPINE', sciName: '(Magnesium Aluminum Iron Boro-silicate Hydroxide)' },
                { name: 'KOTTIGITE', sciName: '(Hydrated Zinc Arsenate)' },
                { name: 'KOVDORSKITE', sciName: '(Hydrated Magnesium Carbonate Phosphate Hydroxide)' },
                { name: 'KTENASITE', sciName: '(Hydrated Copper Zinc Sulfate Hydroxide)' },
                { name: 'KULANITE', sciName: '(Barium Iron Manganese Magnesium Aluminum Phosphate Hydroxide)' },
                { name: 'KUNZITE', sciName: '(variety of Spodumene)' },
                { name: 'KUPLETSKITE', sciName: '(Potassium Sodium Manganese Iron Titanium Niobium Silicate Hydroxide)' },
                { name: 'KUTNOHORITE', sciName: '(Calcium Magnesium Carbonate)' },
                { name: 'KYANITE', sciName: '(Aluminum Silicate)' }
            ],
            l: [
                { name: 'LABRADORITE', sciName: '(Calcium Sodium Aluminum Silicate)' },
                { name: 'LARDERELLITE', sciName: '(Ammonium Borate Hydroxide)' },
                { name: 'LARIMAR', sciName: '(variety of Pectolite)' },
                { name: 'LAUEITE', sciName: '(Hydrated Manganese Iron Phosphate Hydroxide)' },
                { name: 'LAUMONTITE', sciName: '(Hydrated Calcium Aluminum Silicate)' },
                { name: 'LAURIONITE', sciName: '(Lead Chloride Hydroxide)' },
                { name: 'LAZULITE', sciName: '(Magnesium Aluminum Phosphate Hydroxide)' },
                { name: 'LAZURITE', sciName: '(Sodium Calcium Aluminum Silicate Sulfate)' },
                { name: 'LEAD', sciName: '(Pb)' },
                { name: 'LEADHILLITE', sciName: '(Lead Sulfate Carbonate Hydroxide)' },
                { name: 'LECHATELIERITE', sciName: '(Silicon Dioxide)' },
                { name: 'LEGRANDITE', sciName: '(Hydrated Zinc Arsenate Hydroxide)' },
                { name: 'LEIFITE', sciName: '(Hydrated Sodium Beryllium Aluminum Silicate Hydroxide Fluoride)' },
                { name: 'LEPIDOLITE', sciName: '(Potassium Lithium Aluminum Silicate Hydroxide Fluoride)' },
                { name: 'LEUCITE', sciName: '(Potasium Aluminum Silicate)' },
                { name: 'LEUCOCHALCITE', sciName: '(variety of Olivenite)' },
                { name: 'LEUCOPHANITE', sciName: '(Sodium Calcium Beryllium Silicate Fluoride)' },
                { name: 'LIBETHENITE', sciName: '(Copper Phosphate Hydroxide)' },
                { name: 'LIMESTONE', sciName: '(a common sedimentary rock)' },
                { name: 'LIMONITE', sciName: '(Hydrated Iron Oxide Hydroxide)' },
                { name: 'LINARITE', sciName: '(Lead Copper Sulfate hydroxide)' },
                { name: 'LINNAEITE', sciName: '(Cobalt Sulfide)' },
                { name: 'LIROCONITE', sciName: '(Hydrated Copper Aluminum Arsenate Hydroxide)' },
                { name: 'LITHIOPHILITE', sciName: '(Lithium Manganese Iron Phosphate)' },
                { name: 'LOLLINGITE', sciName: '(Iron Arsenide)' },
                { name: 'LORENZENITE', sciName: '(Sodium Titanium Silicate)' },
                { name: 'LARIMAR', sciName: '(variety of Pectolite)' },
                { name: 'LUDLAMITE', sciName: '(Hydrated Iron Magnesium Manganese Phosphate)' }
            ],
            m: [
                { name: 'MACPHERSONITE', sciName: '(Lead Sulfate Carbonate Hydroxide)' },
                { name: 'MAGNESITE', sciName: '(Magnesium Carbonate)' },
                { name: 'MAGNETITE', sciName: '(Iron Oxide)' },
                { name: 'MALACHITE', sciName: '(Hydrated Copper Carbonate)' },
                { name: 'MANGANBABINGTONITE', sciName: '(Calcium Manganese Iron Silicate Hydroxide)' },
                { name: 'MANGANESE', sciName: '(Mn)' },
                { name: 'MANGANITE', sciName: '(Manganese Oxide Hydroxide)' },
                { name: 'MARBLE', sciName: '(a metamorphic rock from limestone)' },
                { name: 'MARCASITE', sciName: '(Group)' },
                { name: 'MARCASITE', sciName: '(Iron Sulfide)' },
                { name: 'MASSICOT', sciName: '(Lead Oxide)' },
                { name: 'MELANITE', sciName: '(the black variety of Andradite Garnet)' },
                { name: 'MELANOPHLOGITE', sciName: '(Silicon Oxide with organic compounds)' },
                { name: 'MELANTERITE', sciName: '(Hydrated Iron Sulfate)' },
                { name: 'MENEGHINITE', sciName: '(Lead Antimony Sulfide)' },
                { name: 'MERCURY', sciName: '(Hg)' },
                { name: 'MESOLITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)' },
                { name: 'META-ANKOLEITE', sciName: '(Hydrated Potassium Uranyl Phosphate)' },
                { name: 'META-AUTUNITE', sciName: '(Hydrated Calcium Uranyl Phosphate)' },
                { name: 'META-TORBERNITE', sciName: '(Hydrated Copper Uranyl Phosphate)' },
                { name: 'META-URANOCIRCITE', sciName: '(Hydrated Barium Uranyl Phosphate)' },
                { name: 'META-VARISCITE', sciName: '(Hydrated Aluminum Phosphate)' },
                { name: 'META-ZEUNERITE', sciName: '(Hydrated Copper Uranyl Arsenate)' },
                { name: 'METAMORPHIC', sciName: '(rocks formed via heat and pressure)' },
                { name: 'METEORITES', sciName: '(primordial rocks that fell to Earth)' },
                { name: 'MIARGYRITE', sciName: '(Silver Antimony Sulfide)' },
                { name: 'MICA', sciName: '(Group)' },
                { name: 'MICROCLINE', sciName: '(Potasium Aluminum Silicate)' },
                { name: 'MICROLITE', sciName: '(Calcium Sodium Tantalum Oxide Hydroxide Fluoride)' },
                { name: 'MILARITE', sciName: '(Hydrated Potassium Calcium Aluminum Beryllium Silicate)' },
                { name: 'MILKY QUARTZ', sciName: '(variety of Quartz)' },
                { name: 'MILLERITE', sciName: '(Nickel Sulfide)' },
                { name: 'MIMETITE', sciName: '(Lead Chloroarsenate)' },
                { name: 'MINASGERAISITE', sciName: '- (Y) (Calcium Yttrium Beryllium Silicate)' },
                { name: 'MINIUM', sciName: '(Lead Oxide)' },
                { name: 'MIXITE', sciName: '(Hydrated Bismuth Copper Arsenate Hydroxide)' },
                { name: 'MOCTEZUMITE', sciName: '(Lead Uranyl Tellurite)' },
                { name: 'MOISSANITE', sciName: '(Silicon Carbide)' },
                { name: 'MOLDAVITE', sciName: '(variety of Tecktite: Meteoric Silica Glass)' },
                { name: 'MOLYBDENUM', sciName: '(the element Molybdenum)' },
                { name: 'MOLYBDENITE', sciName: '(Molybdenum Sulfide)' },
                { name: 'MONAZITE', sciName: '(Cerium Lanthanum Thorium Neodymium Yttrium Phosphate)' },
                { name: 'MONTEBRASITE', sciName: '(Lithium Sodium Aluminum Phosphate Hydroxide Fluoride)' },
                { name: 'MONTMORILLONITE', sciName: '(Hydrated Sodium Calcium Aluminum Magnesium Silicate Hydroxide)' },
                { name: 'MOONSTONE', sciName: '(variety of Oligoclase, Sodium Calcium Aluminum Silicate)' },
                { name: 'MORDENITE', sciName: '(Hydrated Calcium Sodium Potassium Aluminum Silicate)' },
                { name: 'MORGANITE', sciName: '(variety of Beryl, Berylium Aluminum Silicate)' },
                { name: 'MOSCHELLANDSBERGITE', sciName: '(Silver Mercury or Silver Amalgam)' },
                { name: 'MOTTRAMITE', sciName: '(Lead Copper Vanadate Hydroxide)' },
                { name: 'MURMANITE', sciName: '(Hydrated Sodium Titanium Niobium Silicate)' },
                { name: 'MUSCOVITE', sciName: '(Potassium Aluminum Silicate Hydroxide Fluoride)' }
            ],
            n: [
                { name: 'NAGYAGITE', sciName: '(Lead Gold Antimony Bismuth Telluride Sulfide)' },
                { name: 'NAHCOLITE', sciName: '(Sodium Bicarbonate)' },
                { name: 'NARSARSUKITE', sciName: '(Sodium Titanium Iron Silicate Fluoride)' },
                { name: 'NATROJAROSITE', sciName: '(Sodium Iron Sulfate Hydroxide)' },
                { name: 'NATROLITE', sciName: '(Hydrated Sodium Aluminum Silicate)' },
                { name: 'NEALITE', sciName: '(Lead Iron Arsenate Chloride)' },
                { name: 'NEPHELINE', sciName: '(Sodium Potassium Aluminum Silicate)' },
                { name: 'NEPHRITE', sciName: '(variety of Actinolite, Calcium Magnesium Iron Silicate Hydroxide)' },
                { name: 'NEPTUNITE', sciName: '(Potassium Sodium Lithium Iron Manganese Titanium Silicate)' },
                { name: 'NICKEL', sciName: '(the element Nickel)' },
                { name: 'NICKELINE', sciName: '(Nickel Arsenide)' },
                { name: 'NITER', sciName: '(Potasium Nitrate)' },
                { name: 'NITRATINE', sciName: '(Sodium Nitrate)' },
                { name: 'NORBERGITE', sciName: '(Magnesium Silicate Fluoride Hydroxide)' }
            ],
            o: [
                { name: 'OBSIDIAN', sciName: '(Volcanic Silica Glass)' },
                { name: 'OKENITE', sciName: '(Hydrated Calcium Silicate)' },
                { name: 'OLIGOCLASE', sciName: '(Sodium Calcium Aluminum Silicate)' },
                { name: 'OLIVINE', sciName: '(Group)' },
                { name: 'OLIVINE', sciName: '(Magnesium Iron Silicate)' },
                { name: 'OLIVENITE', sciName: '(Copper Arsenate Hydroxide)' },
                { name: 'ONYX', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'OPAL', sciName: '(Hydrated Silica)' },
                { name: 'ORPIMENT', sciName: '(Arsenic Sulfide)' },
                { name: 'ORTHOCLASE', sciName: '(Potasium Aluminum Silicate)' },
                { name: 'OSBORNITE', sciName: '(Titanium Nitride)' },
                { name: 'OSUMILITE', sciName: '(Hydrated Potassium Sodium Iron Magnesium Aluminum Silicate)' },
                { name: 'OTAVITE', sciName: '(Cadmium Carbonate)' }
            ],
            p: [
                { name: 'PACHNOLITE', sciName: '(Hydrated Sodium Calcium Aluminum Fluoride)' },
                { name: 'PALYGORSKITE', sciName: '(Hydrated Magnesium Aluminum Silicate Hydroxide)' },
                { name: 'PAPAGOITE', sciName: '(Calcium Copper Aluminum Silicate Hydroxide)' },
                { name: 'PARADAMITE', sciName: '(Zinc Arsenate Hydroxide)' },
                { name: 'PARASYMPLESITE', sciName: '(Hydrated Iron Arsenate)' },
                { name: 'PARAVAUXITE', sciName: '(Hydrated Iron Aluminum Phosphate Hydroxide)' },
                { name: 'PARISITE', sciName: '(Calcium Cerium Lanthanum Neodymium Carbonate Fluoride)' },
                { name: 'PECTOLITE', sciName: '(Sodium Calcium Silicate Hydroxide)' },
                { name: 'PENTLANDITE', sciName: '(Iron Nickel Sulfide)' },
                { name: 'PERICLASE', sciName: '(Magnesium Oxide)' },
                { name: 'PERIDOT', sciName: '(variety of Olivine)' },
                { name: 'PEROVSKITE', sciName: '(Calcium Titanium Oxide)' },
                { name: 'PHARMACOLITE', sciName: '(Hydrated Calcium Arsenate Hydroxide)' },
                { name: 'PHARMACOSIDERITE', sciName: '(Hydrated Potassium Iron Arsenate Hydroxide)' },
                { name: 'PHENAKITE', sciName: '(Berylium Silicate)' },
                { name: 'PHILLIPSITE', sciName: '(Hydrated Potasium Sodium Calcium Aluminum Silicate)' },
                { name: 'PHLOGOPITE', sciName: '(Potassium Magnesium Aluminum Silicate Hydroxide)' },
                { name: 'PHOSGENITE', sciName: '(Lead Carbonate Chloride)' },
                { name: 'PHOSPHOPHYLLITE', sciName: '(Hydrated Zinc Iron Manganese Phosphate)' },
                { name: 'PHOSPHURANYLITE', sciName: '(Hydrated Calcium Uranyl Phosphate Hydroxide)' },
                { name: 'PICROMERITE', sciName: '(Hydrated Potassium Magnesium Sulfate)' },
                { name: 'PIRSSONITE', sciName: '(Hydrated Sodium Calcium Carbonate)' },
                { name: 'PLANCHEITE', sciName: '(Hydrated Copper Silicate Hydroxide)' },
                { name: 'PLATINUM', sciName: '(Pt)' },
                { name: 'PLATTNERITE', sciName: '(Lead Oxide)' },
                { name: 'POLYBASITE', sciName: '(Silver Copper Antimony Sulfide)' },
                { name: 'POLYHALITE', sciName: '(Hydrated Potassium Calcium Magnesium Sulfate)' },
                { name: 'POLYLITHIONITE', sciName: '(Potassium Lithium Aluminum Silicate Fluoride)' },
                { name: 'POWELLITE', sciName: '(Calcium Molybdenate)' },
                { name: 'PRASIOLITE', sciName: '(variety of Quartz)' },
                { name: 'PREHNITE', sciName: '(Calcium Aluminum Silicate Hydroxide)' },
                { name: 'PRIMORDIAL', sciName: '(rocks formed before the Earth)' },
                { name: 'PROUSTITE', sciName: '(Silver Arsenic Sulfide)' },
                { name: 'PSEUDOBOLEITE', sciName: '(Lead Copper Chloride Hydroxide)' },
                { name: 'PSEUDOBROOKITE', sciName: '(Iron Titanium Oxide)' },
                { name: 'PSEUDOMALACHITE', sciName: '(Copper Phosphate Hydroxide)' },
                { name: 'PSILOMELANE', sciName: '(Manganese Oxide)' },
                { name: 'PUCHERITE', sciName: '(Bismuth Vanadate)' },
                { name: 'PURPURITE', sciName: '(Manganese Phosphate)' },
                { name: 'PYRARGYRITE', sciName: '(Silver Antimony Sulfide)' },
                { name: 'PYRITE', sciName: '(Iron Sulfide)' },
                { name: 'PYROAURITE', sciName: '(Hydrated Magnesium Iron Carbonate Hydroxide)' },
                { name: 'PYROCHLORE', sciName: '(Calcium Sodium Niobium Oxide Hydroxide Fluoride)' },
                { name: 'PYROLUSITE', sciName: '(Manganese Oxide)' },
                { name: 'PYROMORPHITE', sciName: '(Lead Chlorophosphate)' },
                { name: 'PYROPE', sciName: '(Magnesium Aluminum Silicate)' },
                { name: 'PYROPHYLLITE', sciName: '(Aluminum Silicate Hydroxide)' },
                { name: 'PYROXENE', sciName: '(Group)' },
                { name: 'PYRRHOTITE', sciName: '(Iron Sulfide)' }
            ],
            q: [
                { name: 'QUARTZ', sciName: '(Silicon Oxide)' },
                { name: 'QUETZALCOATLITE', sciName: '(Zinc Copper Tellurite Hydroxide)' }
            ],
            r: [
                { name: 'RAITE', sciName: '(Hydrated Sodium Calcium Manganese Titanium Iron Silicate Hydroxide)' },
                { name: 'RAMMELSBERGITE', sciName: '(Nickel Arsenide)' },
                { name: 'RAMSDELLITE', sciName: '(Manganese Oxide)' },
                { name: 'REALGAR', sciName: '(Arsenic Sulfide)' },
                { name: 'RHABDOPHANE', sciName: '(Hydrated Cerium Lanthanum Neodymium Phosphate)' },
                { name: 'RHENIITE', sciName: '(Rhenium Sulfide)' },
                { name: 'RHODIZITE', sciName: '(Potassium Cesium Beryllium Aluminum Borate)' },
                { name: 'RHODOCHROSITE', sciName: '(Manganese Carbonate)' },
                { name: 'RHODOLITE', sciName: '(variety of PYROPE garnet, Magnesium Aluminum Silicate)' },
                { name: 'RHODONITE', sciName: '(Manganese Iron Magnesium Calcium Silicate)' },
                { name: 'RICHTERITE', sciName: '(Sodium Calcium Magnesium Iron Silicate Hydroxide)' },
                { name: 'RIEBECKITE', sciName: '(Sodium Iron Magnesium Silicate Hydroxide)' },
                { name: 'ROCK CRYSTAL', sciName: '(variety of Quartz- Silicon Oxide)' },
                { name: 'ROCKBRIDGEITE', sciName: '(Iron Manganese Phosphate Hydroxide)' },
                { name: 'ROMANECHITE', sciName: '(Hydrated Barium Manganese Oxide)' },
                { name: 'ROSASITE', sciName: '(Copper Zinc Carbonate Hydroxide)' },
                { name: 'ROSE QUARTZ', sciName: '(variety of Quartz- Silicon Oxide)' },
                { name: 'ROSELITE', sciName: '(Hydrated Calcium Cobalt Magnesium Arsenate)' },
                { name: 'RUBY', sciName: '(variety of Corundum- Aluminum Oxide)' },
                { name: 'RUTILE', sciName: '(Titanium Oxide)' }
            ],
            s: [
                { name: 'SAFFLORITE', sciName: '(Cobalt Iron Arsenide)' },
                { name: 'SAINFELDITE', sciName: '(Hydrated Calcium Arsenate Hydroxide)' },
                { name: 'SAL AMMONIAC', sciName: '(Ammonium Chloride)' },
                { name: 'SAMARSKITE', sciName: '(Yttrium Cerium Uranium Iron Niobium Tantalum Titanium Oxide)' },
                { name: 'SANBORNITE', sciName: '(Barium Silicate)' },
                { name: 'SANDSTONE', sciName: '(a common sedimentary rock)' },
                { name: 'SANIDINE', sciName: '(Potasium Aluminum Silicate)' },
                { name: 'SAPPHIRE', sciName: '(variety of Corundum- Aluminum Oxide)' },
                { name: 'SARD', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'SARDONYX', sciName: '(variety of Quartz - Silicon Oxide)' },
                { name: 'SARTORITE', sciName: '(Lead Arsenic Sulfide)' },
                { name: 'SCAPOLITE', sciName: '(Sodium Calcium Aluminum Silicate Chloride Carbonate Sulfate)' },
                { name: 'SCHEELITE', sciName: '(Calcium Tungstate)' },
                { name: 'SCHMITTERITE', sciName: '(Uranyl Tellurite)' },
                { name: 'SCHOLZITE', sciName: '(Hydrated Calcium Zinc Phosphate)' },
                { name: 'SCHORL', sciName: '(complex Sodium Iron Boro-Aluminum Silicate)' },
                { name: 'SCHROCKINGERITE', sciName: '(Hydrated Sodium Calcium Uranyl Sulfate Carbonate Fluoride)' },
                { name: 'SCOLECITE', sciName: '(Hydrated Calcium Aluminum Silicate)' },
                { name: 'SCORODITE', sciName: '(Hydrated Iron Arsenate)' },
                { name: 'SCORZALITE', sciName: '(Iron Magnesium Aluminum Phosphate Hydroxide)' },
                { name: 'SEDIMENTARY', sciName: '(rocks formed via biochemical, clastic, or evaporative processes)' },
                { name: 'SELENITE', sciName: '(alternate name for Gypsum)' },
                { name: 'SELENIUM', sciName: '(Se)' },
                { name: 'SEMSEYITE', sciName: '(Lead Antimony Sulfide)' },
                { name: 'SENARMONTITE', sciName: '(Antimony Oxide)' },
                { name: 'SERANDITE', sciName: '(Sodium Manganese Calcium Silicate Hydroxide)' },
                { name: 'SERPENTINE', sciName: '(Iron Magnesium Nickel Silicate Hydroxide)' },
                { name: 'SHATTUCKITE', sciName: '(Copper Silicate Hydroxide)' },
                { name: 'SIDERITE', sciName: '(Iron Carbonate)' },
                { name: 'SILICON', sciName: '(Si)' },
                { name: 'SILLIMANITE', sciName: '(Aluminum Silicate)' },
                { name: 'SILVER', sciName: '(Ag)' },
                { name: 'SINHALITE', sciName: '(Magnesium Aluminum Borate)' },
                { name: 'SJOGRENITE', sciName: '(Hydrated Magnesium Iron Carbonate Hydroxide)' },
                { name: 'SKLODOWSKITE', sciName: '(Hydrated Magnesium Uranyl Silicate)' },
                { name: 'SKUTTERUDITE', sciName: '(Cobalt Arsenide)' },
                { name: 'SMITHSONITE', sciName: '(Zinc Carbonate)' },
                { name: 'SMOKY QUARTZ', sciName: '(variety of Quartz- Silicon Oxide)' },
                { name: 'SODALITE', sciName: '(Sodium Aluminum Silicate Chloride)' },
                { name: 'SPANGOLITE', sciName: '(Hydrated Copper Aluminum Sulfate Chloride Hydroxide)' },
                { name: 'SPERRYLITE', sciName: '(Platinum Arsenide)' },
                { name: 'SPESSARTINE', sciName: '(Manganese Aluminum Silicate)' },
                { name: 'SPHAEROCOBALTITE', sciName: '(Cobalt Carbonate)' },
                { name: 'SPHALERITE', sciName: '(Zinc Iron Sulfide)' },
                { name: 'SPHENE', sciName: '(Calcium Titanium Silicate)' },
                { name: 'SPINEL', sciName: '(Group)' },
                { name: 'SPINEL', sciName: '(Magnesium Aluminum Oxide)' },
                { name: 'SPODUMENE', sciName: '(Lithium Aluminum Silicate)' },
                { name: 'STAUROLITE', sciName: '(Iron Magnesium Zinc Aluminum Silicate Hydroxide)' },
                { name: 'STELLERITE', sciName: '(Hydrated Calcium Aluminum Silicate)' },
                { name: 'STEPHANITE', sciName: '(Silver Antimony Sulfide)' },
                { name: 'STIBARSEN', sciName: '(Antimony Arsenic)' },
                { name: 'STIBICONITE', sciName: '(Antimony Oxide Hydroxide)' },
                { name: 'STIBNITE', sciName: '(Antimony Sulfide)' },
                { name: 'STICHTITE', sciName: '(Hydrated Magnesium Chromium Carbonate Hydroxide)' },
                { name: 'STILBITE', sciName: '(Hydrated Calcium Aluminum Silicate)' },
                { name: 'STISHOVITE', sciName: '(Silicon Dioxide)' },
                { name: 'STRENGITE', sciName: '(Hydrated Iron Phosphate)' },
                { name: 'STRONTIANITE', sciName: '(Strontium Carbonate)' },
                { name: 'STRUNZITE', sciName: '(Calcium Zinc Arsenate Hydroxide)' },
                { name: 'STURMANITE', sciName: '(Hydrated Calcium Iron Aluminum Manganese Sulfate Tetrahydroxoborate Hydroxide)' },
                { name: 'SUGILITE', sciName: '(Potassium Sodium Lithium Iron Manganese Aluminum Silicate)' },
                { name: 'SULFUR', sciName: '(S)' },
                { name: 'SUNSTONE', sciName: '(variety of Oligoclase, Sodium Calcium Aluminum Silicate)' },
                { name: 'SUOLUNITE', sciName: '(Hydrated Calcium Silicate Hydroxide)' },
                { name: 'SUSANNITE', sciName: '(Lead Sulfate Carbonate Hydroxide)' },
                { name: 'SUSSEXITE', sciName: '(Manganese Borate Hydroxide)' },
                { name: 'SVANBERGITE', sciName: '(Strontium Aluminum Phosphate Sulfate Hydroxide)' },
                { name: 'SYLVANITE', sciName: '(Silver Gold Telluride)' },
                { name: 'SYLVITE', sciName: '(Potassium Chloride)' },
                { name: 'SYMPLESITE', sciName: '(Hydrated Iron Arsenate)' },
                { name: 'SYNCHYSITE', sciName: '(Calcium Cerium Lanthanum Neodymium Yttrium Carbonate Fluoride)' }
            ],
            t: [
                { name: 'TAAFFEITE', sciName: '(Beryllium Magnesium Aluminum Oxide)' },
                { name: 'TAINIOLITE', sciName: '(Potassium Lithium Magnesium Silicate Fluoride)' },
                { name: 'TALC', sciName: '(Magnesium Silicate Hydroxide)' },
                { name: 'TANTALITE', sciName: '(Iron Manganese Tantalum Niobium Oxide)' },
                { name: 'TANZANITE', sciName: '(gem variety of Zoisite)' },
                { name: 'TARBUTTITE', sciName: '(Zinc Phosphate Hydroxide)' },
                { name: 'TEALLITE', sciName: '(Lead Tin Sulfide)' },
                { name: 'TEKTITES', sciName: '(Meteoric Silica Glass)' },
                { name: 'TELLURIUM', sciName: '(Te)' },
                { name: 'TENNANTITE', sciName: '(Copper Arsenic Sulfide)' },
                { name: 'TEPHROITE', sciName: '(Manganese Silicate)' },
                { name: 'TETRAHEDRITE', sciName: '(Copper Antimony Sulfide)' },
                { name: 'THAUMASITE', sciName: '(Hydrated Calcium Silicon Carbonate Sulfate Hydroxide)' },
                { name: 'THENARDITE', sciName: '(Sodium Sulfate)' },
                { name: 'THOMSONITE', sciName: '(Hydrated Sodium Calcium Aluminum Silicate)' },
                { name: 'THORITE', sciName: '(Thorium Uranium Silicate)' },
                { name: 'THOROGUMMITE', sciName: '(Thorium Uranium Silicate Hydroxide)' },
                { name: 'TIN', sciName: '(Sn)' },
                { name: 'TINAKSITE', sciName: '(Titanium Sodium Potasium Silicate Hydroxide)' },
                { name: 'TINCALCONITE', sciName: '(Hydrated Sodium Borate)' },
                { name: 'TITANIUM', sciName: '(Ti)' },
                { name: 'TITANITE', sciName: '(alternate name for Sphene)' },
                { name: 'TOPAZ', sciName: '(Aluminum Silicate Fluoride Hydroxide)' },
                { name: 'TOPAZOLITE', sciName: '(the yellow variety of Andradite Garnet)' },
                { name: 'TORBERNITE', sciName: '(Hydrated Copper Uranyl Phosphate)' },
                { name: 'TOURMALINE', sciName: '(Group)' },
                { name: 'TREMOLITE', sciName: '(Calcium Magnesium Iron Silicate Hydroxide)' },
                { name: 'TRIDYMITE', sciName: '(Silicon Dioxide)' },
                { name: 'TRIPHYLITE', sciName: '(Lithium Iron Manganese Phosphate)' },
                { name: 'TRONA', sciName: '(Hydrated Sodium Bicarbonate Carbonate)' },
                { name: 'TSAVORITE', sciName: '(variety of Grossular garnet)' },
                { name: 'TSUMCORITE', sciName: '(Hydrated Lead Zinc Iron Arsenate)' },
                { name: 'TSUMEBITE', sciName: '(Lead Copper Phosphate Sulfate)' },
                { name: 'TURQUOISE', sciName: '(Hydrated Copper Aluminum Phosphate)' },
                { name: 'TYUYAMUNITE', sciName: '(Hydrated Calcium Uranyl Vanadate)' }
            ],
            u: [
                { name: 'ULEXITE', sciName: '(Sodium Calcium Borate Hydroxide)' },
                { name: 'ULLMANNITE', sciName: '(Nickel Antimony Sulfide)' },
                { name: 'URANINITE', sciName: '(Uranium Oxide)' },
                { name: 'URANOCIRCITE', sciName: '(Hydrated Barium Uranyl Phosphate)' },
                { name: 'URANOPHANE', sciName: '(Hydrated Calcium Uranyl Silicate)' },
                { name: 'URANOPILITE', sciName: '(Hydrated Uranyl Sulfate Hydroxide)' },
                { name: 'UVAROVITE', sciName: '(Calcium Chromium Silicate)' },
                { name: 'UVITE', sciName: '(complex Calcium Sodium Magnesium Iron Boro-Aluminum Silicate Hydroxide)' }
            ],
            v: [
                { name: 'VALENTINITE', sciName: '(Antimony Oxide)' },
                { name: 'VANADINITE', sciName: '(Lead Chlorovanadinate)' },
                { name: 'VARISCITE', sciName: '(Hydrated Aluminum Phosphate)' },
                { name: 'VAUXITE', sciName: '(Hydrated Iron Aluminum Phosphate Hydroxide)' },
                { name: 'VERMICULITE', sciName: '(Hydrated Magnesium Iron Aluminum Silicate Hydroxide)' },
                { name: 'VESUVIANITE', sciName: '(Calcium Magnesium Aluminum Silicate Hydroxide)' },
                { name: 'VESZELYITE', sciName: '(Hydrated Copper Zinc Phosphate Hydroxide)' },
                { name: 'VILLIAUMITE', sciName: '(Sodium Fluoride)' },
                { name: 'VIVIANITE', sciName: '(Hydrated Iron Phosphate)' },
                { name: 'VOLBORTHITE', sciName: '(Copper Vanadate Hydroxide)' }
            ],
            w: [
                { name: 'WALPURGITE', sciName: '(Hydrated Bismuth Uranyl Arsenate Oxide)' },
                { name: 'WARDITE', sciName: '(Hydrated Sodium Aluminum Phosphate Hydroxide)' },
                { name: 'WAVELLITE', sciName: '(Hydrated Aluminum Phosphate Hydroxide)' },
                { name: 'WELOGANITE', sciName: '(Hydrated Sodium Strontium Calcium Zirconium Carbonate)' },
                { name: 'WERNERITE', sciName: '(properly called Scapolite, Sodium Calcium Aluminum Silicate Chloride Carbonate Sulfate)' },
                { name: 'WHEWELLITE', sciName: '(Hydrated Calcium Oxalate)' },
                { name: 'WHITEITE', sciName: '(Hydrated Calcium Iron Manganese Magnesium Aluminum Phosphate)' },
                { name: 'WHITLOCKITE', sciName: '(Calcium Magnesium Iron Phosphate Hydroxide)' },
                { name: 'WILLEMITE', sciName: '(Zinc Silicate)' },
                { name: 'WITHERITE', sciName: '(Barium Carbonate)' },
                { name: 'WOLFEITE', sciName: '(Iron Manganese Phosphate Hydroxide)' },
                { name: 'WOLFRAMITE', sciName: '(Manganese Iron Tungstate)' },
                { name: 'WOLLASTONITE', sciName: '(Calcium Silicate)' },
                { name: 'WOODHOUSEITE', sciName: '(Calcium Aluminum Phosphate Sulfate Hydroxide)' },
                { name: 'WULFENITE', sciName: '(Lead Molybdenate)' },
                { name: 'WURTZITE', sciName: '(Zinc Iron Sulfide)' }
            ],
            x: [
                { name: 'XENOTIME', sciName: '(Yttrium Phosphate)' },
                { name: 'XONOTLITE', sciName: '(Calcium Silicate Hydroxide)' }
            ],
            y: [
                { name: 'YUKSPORITE', sciName: '(Hydrated Potassium Barium Sodium Calcium Titanium Silicate Fluoride Hydroxide)' }
            ],
            z: [
                { name: 'ZEOLITE', sciName: '(Group)' },
                { name: 'ZEUNERITE', sciName: '(Hydrated Copper Uranyl Arsenate)' },
                { name: 'ZINC', sciName: '(Zn)' },
                { name: 'ZINCITE', sciName: '(Zinc Manganese Oxide)' },
                { name: 'ZINKENITE', sciName: '(Lead Antimony Sulfide)' },
                { name: 'ZINNWALDITE', sciName: '(Potassium Lithium Iron Aluminum Silicate Hydroxide Fluoride)' },
                { name: 'ZIPPEITE', sciName: '(Hydrated Potassium Uranyl Sulfate Hydroxide)' },
                { name: 'ZIRCON', sciName: '(Zirconium Silicate)' },
                { name: 'ZOISITE', sciName: '(Calcium Aluminum Silicate Hydroxide)' }
            ]
        };
    }

    public getRandomMineral(letter: string) {
        return _.sample(this.minerals[letter]);
    }

}
